### ISSUE TITLE
Add --prefix key in order to customize naming of client-side templates

### ISSUE THREAD

**Issue by shabunc** [jadejs/jade#1097]
Currently compiling jade template to client-side has only one option  - to compile to function anonymous(locals)

Actually it will be very handy if we'll be able to set the name of variable we are assigning anonymous function. 

So, I believe we need something like
```jade -c --prefix "Views.prototype.someView = "```

which will compile to something like
```Views.prototype.someView = function() {...}```

Will be glad to make PR if this will be accepted.

**Comment by ForbesLindesay** [comment]
We support a load more options for custom naming of templates now.
