### ISSUE TITLE
Multiple blocks append in child layout block append and includes results in multiple bugs: blocks duplicated, with different orders

### ISSUE THREAD

**Issue by triccardi-systran** [jadejs/jade#1261]
The following examples are compiled using jade v0.35.0 and today's master (bd6233b61a408fd19c547442cac68e155da3dddc).

layout.jade
```jade
block scripts

block content
```

page2.jade
```jade
append scripts
  script console.log("page2");

append content
  p page2
```

page1-v1.jade
```jade
extends layout
append scripts
  script console.log("page1");

append content
  p page 1
```
page1-v1.html
```html
<script>console.log("page1");</script>
<p>page 1</p>
```
Up to here everything is OK.

page1-v2.jade
```jade
extends layout
append scripts
  script console.log("page1");

append content
  p page 1
  append scripts
    script console.log("page1 in content");
```
page1-v2.html
```html
<script>console.log("page1");</script>
<script>console.log("page1 in content");</script>
<p>page 1</p>
<script>console.log("page1 in content");</script>
<script>console.log("page1");</script>
```
__Issue 1__: block append in another block append duplicates the content of the inner block append, in different order furthermore.

page1-v3.jade
```jade
extends layout
append scripts
  script console.log("page1");

append content
  p page 1

include page 2
```
page1-v3.html
```html
<script>console.log("page2");</script>
<script>console.log("page1");</script>
<p>page 2</p>
<p>page 1</p>
```
__Issue 2__: append order is not the expected one: page 2 should be after page 1 in both script & content blocks.
With manual copy past of page2.jade instead of include page2.jade it works:
page1-v3bis.jade
```jade
extends layout
append scripts
  script console.log("page1");

append content
  p page 1

append scripts
  script console.log("page2");

append content
  p page 2
```
page1-v3bis.html
```html
<script>console.log("page1");</script>
<script>console.log("page2");</script>
<p>page 1</p>
<p>page 2</p>
```

page1-v4.jade (include inside append content)
```jade
extends layout
append scripts
  script console.log("page1");

append content
  p page 1
  include page2
```
page1-v4.html
```html
<script>console.log("page2");</script>
<script>console.log("page1");</script>
<p>page 1</p>
<script>console.log("page2");</script>
<script>console.log("page1");</script>
<p>page 2</p>
```
__Issue 3__: block scripts is duplicated like in __issue 1__, but the order is the same in the two copies...

This seems duplicated each time we append, directly or from an include:
page1-v4bis.jade (page 2 included two times + direct append)
```jade
extends layout
append scripts
  script console.log("page1");

append content
  p page 1
  append scripts
    script console.log("page1 in content");
  include page2
  append scripts
    script console.log("page1 in content after include page2");
  include page2
  append scripts
    script console.log("page1 in content after 2nd include page2");

```
page1-v4.html
```html
<script>console.log("page2");</script>
<script>console.log("page2");</script>
<script>console.log("page1");</script>
<script>console.log("page1 in content");</script>
<script>console.log("page1 in content after include page2");</script>
<script>console.log("page1 in content after 2nd include page2");</script>
<p>page 1</p>
<script>console.log("page1 in content");</script>
<script>console.log("page1");</script>
<script>console.log("page2");</script>
<script>console.log("page1");</script>
<script>console.log("page1 in content");</script>
<p>page 2</p>
<script>console.log("page1 in content after include page2");</script>
<script>console.log("page2");</script>
<script>console.log("page1");</script>
<script>console.log("page1 in content");</script>
<script>console.log("page2");</script>
<script>console.log("page2");</script>
<script>console.log("page1");</script>
<script>console.log("page1 in content");</script>
<script>console.log("page1 in content after include page2");</script>
<p>page 2</p>
<script>console.log("page1 in content after 2nd include page2");</script>
<script>console.log("page2");</script>
<script>console.log("page2");</script>
<script>console.log("page1");</script>
<script>console.log("page1 in content");</script>
<script>console.log("page1 in content after include page2");</script>
```

I have a use-case for this: a page.jade that extends layout.jade optionally includes multiple features, each feature has a css, scripts & content blocks to append to. Currently I'm forced to split each feature in 3 .jade files, one per block to implement, and include them at the top level of page.jade; but this doesn't work well either because of __issue 2__...

**Comment by ForbesLindesay** [comment]
Sorry this has taken so long.  Blocks will be totally overhauled as part of the 2.0.0 release.  Hopefully that will resolve the bug.

**Comment by tremendus** [comment]
Do we believe this issue to be closed? 

I have a layout, which includes a 'view'. The view includes a form and has a `block append scripts` which includes the JS needed to run that view include. 

The script ends up getting included twice - once under the view (incorrect) and once in the scripts block before the body close tag (correct) 

This is using gulp-pug ^3.2.0 which seems to pull current ^2.1.0 versions of the parser. If you need more code, I will post but its the same setup and symptoms as above.

**Comment by ForbesLindesay** [comment]
OK< I've written a test and it does look like this is still a problem.

**Comment by csakis** [comment]
I have just experienced this bug. It has been report in 2013 first. That was 4 years ago, and it still has not been fixed.

**Comment by renatodeleao** [comment]
Yup, still here.

**Comment by mslinn** [comment]
Very disappointing

**Comment by cspotcode** [comment]
All the block replacement/appending/prepending code needs to be rewritten
IMO.  Last I checked, it's full of side-effects.  It tries to convert an
AST containing blocks into the equivalent AST without blocks, but in doing
so destroys the original block structure, and it does it over multiple
passes.  There's no easy way to see the algorithm's comprehension of your
block hierarchy, so it's tough to debug or even document desired behavior.

It will be easier to reason about if a single pug transformation creates
its own tree-like comprehension of all blocks in all layouts.  This single
structure can be dumped, logged, or debugged.  Then a single traversal of
the root layout uses this structure to recursively expand blocks in one
pass.

**Comment by Robula** [comment]
I've just hit this also and now I am sad.

**Comment by lyoko17220** [comment]
Need a update
