### ISSUE TITLE
Explicit block definition

### ISSUE THREAD

**Issue by buschtoens** [jadejs/jade#1271]
Currently all three block statements (`block`, `append`, `prepend`) implicitly define a new block, if they can't already find a block with the same name in the extended layout.

This is problematic, when using blocks in a single file without a layout (and for includes, but that's another topic).

```
#test
  block test
    p 1

prepend test
  p 0
append test
  p 2
```
```html
<!-- expected output -->
<div id="test">
  <p>0</p>
  <p>1</p>
  <p>2</p>
</div>

<!-- actual output -->
<div id="test">
  <p>1</p>
</div>
<p>1</p>
<p>1</p>
```

This is caused by the ambigious use of the `block name` statement. On the one hand `block test` could create a new block in its current place, on the other hand it could replace all other occurences.

Apparently it does all together. Because changing `block test` to `append test` (which is short for `block prepare test`) leads to this rather funny result.
```html
<div id="test">
  <p>1</p>
</div>
<p>0</p>
<p>1</p>
<p>0</p>
<p>2</p>
<p>1</p>
```

IMHO blocks should get more explicit and so I made up my mind on this. (I'm rather sorry that this is somewhat f a cross-breed of a bug report and a Google Groups post.)

```
h1 The new block interface

h2 Block definitions, appending and prepending

// There now is only *one* way to define a block.
// (i.e. `append` and `prepend` are additional only and don't define blocks)
#only-nums
  block i-can-haz-alphanum
    // This definition can optionally have child nodes.
    p 1

// Blocks can be defined multiple times.
// They can also have different contents.
// Block defintions don't replace one another's content, like before.
// (optional)
#nums-and-an-a
  block i-can-haz-alphanum
    p a

// `block append` and `block prepend` still work as expected.
// The provided content is appended or prepended to all matched block definitions.
// However, `append` and `prepend` don't define blocks themselves.
// They are much like `mixin`s. They are there for the engine, but cannot be seen in the HTML.
block append i-can-haz-alphanum
  p 2

// `append` and `prepend` shorthands too still work as expected.
prepend i-can-haz-alphanum
  p 0

h2 Replacing

#dialogue
block dialogue
  p Bonjour!
prepend dialogue
  p Salut!
append dialogue
  p Au revoir.

// The `replace` mode has to be accessed explicitly.
// It replaces the original content and all appends and prepends that have happened before.
block replace dialogue
  p Luke, I am your father.

// Of course there's a shorthand.
replace dialogue
  p Nooo...

// Further appends and prepends still work.
prepend dialogue
  p Luke, I am your father.
append dialogue
  p Oh yes, I did a paternity test.
```
```html
<h1>The new block interface</h1>

<h2>Block definitions, appending and prepending</h2>

<div id="only-nums">
  <p>0</p>
  <p>1</p>
  <p>2</p>
</div>

<div id="nums-and-an-a">
  <p>0</p>
  <p>a</p>
  <p>2</p>
</div>

<h2>Replacing</h2>

<div id="dialogue">
  <p>Luke, I am your father.</p>
  <p>Nooo...</p>
  <p>Oh yes, I did a paternity test.</p>
</div>
```

I would implement this myself and make a PR, but I'm not familiar enough with Jade's internal engine to be able to safely do it all alone and not produce 20 new bugs by the way. Yet I think, that this shouldn't be too much of a change in the code. `append`, `prepend` and `replace` become something like a mixin (as in not yielding output) and the block engine gets a little twist so that multiple blocks of the same name are allowed.

I find this much more predictable than the original interface and would like to hear your thoughts on this.

**Comment by TimothyGu** [comment]
In short, **you cannot append a block in the same file.** EOD. If you want to append a block, then use `extends`. See also #1267.
