### ISSUE TITLE
status of dynamic features (extend, include, mixins)

### ISSUE THREAD

**Issue by jeromew** [jadejs/jade#1312]
Hello,

I have been looking around for the way to do "dynamic" things with jade while not duplicating templates :
 - white-labeling of sites
 - multiple layouts for the same contents
 - customization of widgets

My goal is not to change the "compile then render" jade workflow. It seems very important to keep this workflow for optimization purpose.

Recently @ForbesLindesay helped me add a new dynamic mixin call : 
    +#{ "prefix" + myVar }(var1,var2)
cf https://github.com/visionmedia/jade/pull/1308 for the PR.

Still, I have seen other people, like me, asking for
extends ..something dynamic here ...
include ..something dynamic here...

check https://github.com/visionmedia/jade/issues/843 for an interesting discussion on this. 2 options are given :

**option 1**:
before compiling, pre-generate a template file by prepending "extends whatever" to another template.
this way, jade will compile the freshly saved template.
cf https://github.com/visionmedia/jade/issues/843#issuecomment-11633874

**options 2**:
inherit the parser in order to override the resolvePath function. This is a way to use more complex algorithms for resolving the path and give jade a new look at the way templates are organized :

options: { parser: myParser }
extends virtual_layout
cf https://github.com/visionmedia/jade/issues/843#issuecomment-11633874

when you look at the code, resolvePath is systematically followed by a readFileSync

// extend

    var path = this.resolvePath(this.expect('extends').val.trim(), 'extends');
    if ('.jade' != path.substr(-5)) path += '.jade';
    var str = fs.readFileSync(path, 'utf8');

// include

    var path = this.resolvePath(tok.val.trim(), 'include');

    // has-filter
    if (tok.filter) {
      var str = fs.readFileSync(path, 'utf8').replace(/\r/g, '');
      str = filters(tok.filter, str, { filename: path });
      return new nodes.Literal(str);
    }

    // non-jade
    if ('.jade' != path.substr(-5)) {
      var str = fs.readFileSync(path, 'utf8').replace(/\r/g, '');
      return new nodes.Literal(str);
    }

    var str = fs.readFileSync(path, 'utf8');
    var parser = new this.constructor(str, path, this.options);
    parser.blocks = utils.merge({}, this.blocks);

so we could have an
**option 3**
add the possibility to configure a __pathReader__ option.
By default, it would do the same as today.
When configured, the pathReader function should return the content.
Better still, maybe this could become an async function. I don't know the complexity of making this async.

another option comes to mind if is it possible to re-inject a pre-parsed template in the parser (I don't know how complex this would be because of the append/prepend block feature).

**option 4**
allow extend and include to be called with variables containing references to in-memory pre-parsed templates.

What do you think of those 4 options ?

a synchronous **option 3** would be easy to patch I think (I could propose a PR) and it would seem clean to me to remove the hardcoded readFileSync from the code (my eyes rolled when I saw this function ;-)

Do you think the asynchronous case could be done ?
it seems to me that the whole parser is blocking ? would it make sense to make it non-blocking ? I'd like feedback on this maybe it can be done but I don't know if this is a direction jade wants to take.

Thanks for you help on this !

**Comment by ForbesLindesay** [comment]
Jade 2.0.0 will make it easy to override the loader/linker components and therefore achieve the desired features.

**Comment by arxpoetica** [comment]
@ForbesLindesay since we're in beta now (beta 6) how might one use the loader/linker to achieve dynamic includes?
