### ISSUE TITLE
Unmatched quotes in inline tags will fail to compile

### ISSUE THREAD

**Issue by lostfictions** [jadejs/jade#1346]
See the amended test at lostfictions/jade@8be21121f21bbb34e9f8a34bade5f262a7db9a38 for example.

Obviously problematic when trying to, say, use an apostrophe in an inline tag, as in #[em That's the one!]

**Comment by ForbesLindesay** [comment]
Inline tags are being overhauled as part of 2.0.0 so this should then be fixed.
