### ISSUE TITLE
Code duplication in compiled client javascript when using include/extend

### ISSUE THREAD

**Issue by michaek** [jadejs/jade#1382]
This issue follows from @bminer's comment on #323.

When multiple jade templates using (the same) include or extend are compiled using compileClient, the code generated by the included/extended files are duplicated. 

The increased filesize resulting from this duplication isn't ideal, though gzip will address that satisfactorily. However, the increased client memory use and evaluation time seems worth addressing through an improved approach.

I would suggest that templates used in include/extend should have an option to be defined on jade.templates[filename] instead of being inlined into the generated template function. As well, we should have an option specifying the file in which template definitions will be stored (without duplication).

I'll be happy to discuss any shortcomings of this approach, or to plan how I can best support implementing this.

Thanks!

**Comment by ForbesLindesay** [comment]
Jade 2.0.0 will have some kind of builtin support for this via `import` for mixins.  It will also allow providing custom linkers and loaders, which should make this possible to do in user space.  Please open a new issue after 2.0.0 has been released if you want any help getting that working.

**Comment by noahmiller** [comment]
Did pug 2 add any support for optionally avoiding code duplication on `include`'d mixins?
