### ISSUE TITLE
Separation of options from locals in API?

### ISSUE THREAD

**Issue by zbjornson** [jadejs/jade#1386]
Right now the jade methods take a combination of options and locals as the second argument:

    jade.render('string of jade', merge(options, locals));

This is a bit of an odd design decision to me. (1) I'm always merging two unrelated objects. (2) What if I want to have a local variable named "filename"?

Are you guys interested in making the options and locals separate arguments? I'm happy to fork and make this change if so.

**Comment by ForbesLindesay** [comment]
We currently support `jade.compile(src, options)(locals)` and `jade.compileFile(filename, options)(locals)`.  I think this is sufficient until support for doing this gets added to express.

**Comment by TimothyGu** [comment]
@ForbesLindesay EJS is doing this as `render(src, locals, options)`. Do you plan to deprecate the `render*()`?

**Comment by ForbesLindesay** [comment]
No, I plan to leave those with their current behaviour until something is settled on in express.  At that point we can see if it's possible to comply with express's plans in a backwards compatible way, and failing that we will release a 3.0.0 version with that breaking change.

**Comment by danneu** [comment]
Is it possible to reopen and rethink this now that it's been almost three years?

The current API makes it trivial to introduce collisions unknowingly.

I think the ideal API is `pug.renderFile(template, locals, options) -> Promise`.

But a backwards-compatible idea could be to introduce an `$options` key such that pug can first check for it: `options = options.$options || options`.

If there's a solution that already exists, I didn't see it.
