### ISSUE TITLE
unexpected strict mode reserved word

### ISSUE THREAD

**Issue by guileen** [jadejs/jade#1428]
unexpected strict mode reserved word
jade.js
line: 1424

```js
  /**
   * Yield.
   */

  yield: function() {  // <--- line 1424
    return this.scan(/^yield */, 'yield');
  },
```

This is test from a Android device browser.

I am use requirejs + jade to write my website, so at the debug time, I use jade.js compile jade at browser side.

I replace all the yield to __yield, it fixed, but I am not sure is it ok, some yield maybe is the  template language part code.

**Comment by ForbesLindesay** [comment]
yield is now in quotes, and the jade compiler doesn't support legacy browsers.  If you need to use jade in browsers you should compile the templates server side and then just render them on the client.
