### ISSUE TITLE
Failing test with latest transformers@3.0.0

### ISSUE THREAD

**Issue by jamielinux** [jadejs/jade#1444]
All tests pass fine with transformers@2.1.0, but updating to transformers@3.0.0 results in the following error:

```  
180 passing (2s)
  1 failing

  1)  include filter stylus:
     Error: test/cases/include-filter-stylus.jade:2
    1| style(type="text/css")
  > 2|   include:styl some.styl
    3| 

stylus:1
 > 1| @import "some-included"
   2| 

failed to locate @import file some-included.styl
```

The error disappears if changing `some.styl` contents to:
```
@import "./test/cases/some-included"
```

**Comment by ForbesLindesay** [comment]
Unfortunately transformers has breaking changes.  We will be overhauling filters as part of the 2.0.0 release.
