### ISSUE TITLE
Document support for multi-line strings

### ISSUE THREAD

**Issue by hlship** [jadejs/jade#1447]
The documentation doesn't cover this, but I've found that ending a line with a back slash allows a string to continue onto the next line, which is something you'd expect.

```
div(attr="foo \
  bar \
  baz")
```

compiles to

```
<div attr="foo   bar   baz"></div>
```

It would be nice if this was documented.

**Comment by eddiemonge** [comment]
Could it be extended with something like `\-` to remove the whitespace? Or get to the template literals soon?

**Comment by TimothyGu** [comment]
@eddiemonge said:
> Could it be extended with something like \- to remove the whitespace?

No, that would mean extending the JavaScript parser we use which is too complicated and non-standard.

> Or get to the template literals soon?

It already works if you have a JS engine that supports template literals (e.g. latest version of io.js).
