### ISSUE TITLE
[meta] make parser better suited for non-js code generators

### ISSUE THREAD

**Issue by Swatinem** [jadejs/jade#1480]
Jade currently has a very tight coupling between the parser and the compiler (code generator) that outputs a js function.
That makes it very painful to write code generators that output something other than a js function outputting an html string.

The problem is not just the jade language constructs itself, but that jade expressions *are* js and might not have literal translations to other languages/templates we might want to compile jade to.

A lot of things that are just `code` blocks right now should be better expressed in a well defined AST.

**Comment by ForbesLindesay** [comment]
Jade 2.0.0 will have overhauled lexers and parsers.
