### ISSUE TITLE
Indentation error with code blocks

### ISSUE THREAD

**Issue by aapokiiso** [jadejs/jade#1491]
The following syntax produces an "unexpected token indent" error in Jade 1.3.1: 

![jadebug1](https://cloud.githubusercontent.com/assets/2262772/2674179/d3142816-c0fc-11e3-9150-97d6bbbb48e1.png)

But removing the empty line between the if statement and the next bit of JS makes the syntax valid: 

![jadebug2](https://cloud.githubusercontent.com/assets/2262772/2674197/0306b688-c0fd-11e3-8d39-ffcd1c31dc69.png)

Is this happening to anybody else? I'll happily provide more information if needed.

**Comment by ForbesLindesay** [comment]
I don't get that error so I'm unable to reproduce.  Sorry
