### ISSUE TITLE
Conditionals not working for inheritance

### ISSUE THREAD

**Issue by guyht** [jadejs/jade#1498]
Conditionals using locals passed to the jade compiler are not working for template inheritance:

t1.jade

    if release == true
      extends t2
    else
      extends t3
    block content
      h1 Release is #{release}

t2.jade

    h1 This is t2
    block content

t3.jade

    h1 This is t3
    block content

base.jade

     extends t1
     block content append
        h1 Hi

Run command

    % jade -P -O '{ "release" : true }' base.jade

    % cat base.html

Expected

    <h1>This is t2</h1>
    <h1>Release is true</h1>

Actual

    <h1>This is t3</h1>
    <h1>Release is true</h1>

**Comment by ForbesLindesay** [comment]
This will throw a helpful error in jade@2.0.0

**Comment by guyht** [comment]
:+1:
