### ISSUE TITLE
Compilation issue with data attribute

### ISSUE THREAD

**Issue by viatsyshyn** [jadejs/jade#1501]
Hi, i was playing with jade online demo, and found following template

```jade
mixin T()
    
+T()(data-value= pageTitle)
```

fail to compile with message ```Unexpected token string «,», expected punc «,»```

I've digged a little and found that template is compiled to following

```javascript
jade_debug.unshift({ lineno: 0, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 1, filename: jade_debug[0].filename });
jade_mixins["T"]();
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: jade_debug[0].filename });
jade_mixins["T"].call({
attributes: {
    "data-value": (typeof (jade.interp = pageTitle) == "string" 
                          ? jade.escape(jade.interp) : jade.interp)",
    "class": ""}
});
jade_debug.shift();
jade_debug.shift();
```

And craches on the line with ```addWith(``` processing.

I guess the issues is caused by ```"``` on following line

```javascript
(typeof (jade.interp = pageTitle) == "string" ? jade.escape(jade.interp) : jade.interp)",
"class": ""}
```

If I write template ```+T()(data-value!= pageTitle)``` it compiles.

If I write ```+T()(class= pageTitle)``` it compiles.

**Comment by ForbesLindesay** [comment]
I'm unable to reproduce the issue on the latest version of jade.  I think we must have fixed it at some point.  Sorry for failing to respond.
