### ISSUE TITLE
Inline textarea bug

### ISSUE THREAD

**Issue by valtido** [jadejs/jade#1514]
if I do the following: `.row:	textarea(placeholder="Description")= item.description`

this will output raw text `(placeholder="Description") value=item.description`

expected `<textarea ...>...</textarea>`

however if I did 

    .row
          textarea(placeholder="Description")= item.description

It works fine.

Ask away if you should need anymore information 

I think it's just the `textarea` as my `input` are working fine as in 

`.row: input(value=item.title)`

**Comment by ForbesLindesay** [comment]
Closing as #1835 should fix this.
