### ISSUE TITLE
Programmatic inclusion of mixins?

### ISSUE THREAD

**Issue by braco** [jadejs/jade#1529]
I would like to include a collection of mixins at the server/express level that are made available to all templates.

I know this is possible with local functions, but is it possible with the mixin pattern?

edit: #855 is the closest issue I found to this.

**Comment by ForbesLindesay** [comment]
This is possible via just `include filename.jade` which will load any mixins in `filename.jade` into the current scope.  It will be made much cleaner as part of the move to 2.0.0 because we will be adding `import` syntax.
