### ISSUE TITLE
pretty: true generates illegal Whitespace in inline elements

### ISSUE THREAD

**Issue by paulpflug** [jadejs/jade#1578]
Hi,
I'm currently working on writing books with the help of jade: [paged-media-boilerplate](https://github.com/paulpflug/paged-media-boilerplate)

I implemented something, that works like the citing mechanism of latex, but there is a problem, when  `pretty: true` is activated:
```jade
p.
  some text#[cite key]
```
generates this:
```html
<p>some text
  <cite>"key"</cite>
</p>
```
The whitespace in front of the inline jade is illegal.
The browser output depends on the `pretty` option.

**Comment by ForbesLindesay** [comment]
The pretty option is generally recommended against.  Turn it off and everything should work fine.
