### ISSUE TITLE
`each value, key in ..` shows more stuff than it should..

### ISSUE THREAD

**Issue by laggingreflex** [jadejs/jade#1616]
I have a variable `user.stats` The contents of which are just 

    {
        "total_winnings": [6014, 12120, 16008, 16032, 14105, 261, 6, 21, 35, 800, 2414, 2791, 1793, 4339, 3525, 1358, 573, 1319, 6, 4, 6, 6, 8, 4, 6, 4, 6, 4, 6, 6, 6],
        "weighted_high_average_winning": 0,
        "weighted_average_winning": 11
    }

Which is what shows up when I do `#{JSON.stringify(user.stats)}`

But doing a `each value, key in user.stats` shows a lot of stuff that shouldn't be there

[![](http://i.imgur.com/wG8t47n.png)](http://i.imgur.com/wG8t47n.png)

A lot of those extra properties seem to be of parent's and siblings'..

**Comment by ForbesLindesay** [comment]
In 2.0.0 I plan to deprecate using `each` on an object.  I won't add a warning at this time and I won't remove support.  I will just recommend against its use in the documentation.  We may consider a new syntax in the future that only functions for arrays, as it would generate faster/more succinct code.
