### ISSUE TITLE
Operators should all be documented

### ISSUE THREAD

**Issue by dlowerre** [jadejs/jade#1620]
I am new to Jade, and I find it very frustrating that there appears to be no explanation in the docs for operators that have special meaning to Jade.  

i.e.  I only know the difference between #{} and !{} because I found a tutorial that just happened to mention it.  This should be well documented.

Also: there really should be a section on 'variables' in the docs.

**Comment by TimothyGu** [comment]
Already documented at http://jade-lang.com/reference/interpolation/ since a long time ago.
