### ISSUE TITLE
self.self.data (duplicated nesting) when import object via -O in cli

### ISSUE THREAD

**Issue by puzrin** [jadejs/jade#1652]
Wheh i load locals object via `-O` cli option, it's passed to template with additional `self.self.` nesting.

Example (data, yaml):

```yaml
self:
  demo1:
    a: 2
    b: 3
```

Then in template i have to write:

```jade
- var data = self.self.demo1 // duplicated `self` nesning
p= data.a
```

Should be:

```jade
- var data = self.demo1
p= data.a
```

If i remove root `self` property from object, then template locals not created at all.

Is it a bug or i do something wrong?

**Comment by TimothyGu** [comment]
This is fixed in the v2 branch as this is a breaking change. Closing for now.
