### ISSUE TITLE
same templates at client and server [best practice]

### ISSUE THREAD

**Issue by iliakan** [jadejs/jade#1680]
I couldn't find a better place for the discussion of best practices, so placing it here.

What is the best practice for using same jade templates on client and server?

The one I know well is to use browserify + jadeify(or browserify-jade) transform:
```js
var template = require('file.jade');
console.log( template(locals) }
```

...But this code works only on with browserify transforms, on client-side JS. On server-side, `require('file.jade')` would fail by default, because `file.jade` is not a node.js module.

Sure though, it is possible to create a special require handler for `.jade`-files (e.g. https://github.com/selfcontained/jadequire, but almost no stars), so that this kind of code works both on the client and the server.

Are there better practices for writing client + server code with jade?

**Comment by ForbesLindesay** [comment]
The best bet would be to add a browserify transform that worked to inline the results of calling `jade.compileFile` and then use that API everywhere.  The easiest (but hacky) way to do that would be to have a transform that just replaced `jade.compileFile` with `require` and then also run `jadeify`.  I would prefer a proper transform be written to handle `jade.compileFile` exactly like the server would.

**Comment by iliakan** [comment]
I'm using a special handler as of now.
So, `var template = require('file.jade').`

Works fine with webpack and jade-loader.

**Comment by mikeyhew** [comment]
Are you talking about using the same jade templates on the client and the server, or *writing javascript* that will run on the client and the server? In the latter case I suggest you update the title of this issue.

**Comment by ForbesLindesay** [comment]
brjade will fill this role.  You can tack the support for this feature at jadejs/brjade#3

**Comment by iliakan** [comment]
@ForbesLindesay just to note that people tend to migrate from browserify to webpack. Personally I have no problems with using jade with webpack as of now.

**Comment by ForbesLindesay** [comment]
Webpack is vastly inferior technology though, so I won't be actively supporting it.

**Comment by a7madgamal** [comment]
also might not be the best place for my question. However, I'm trying to know when or if there is a "pugify" version of "jadeify". any help is appreciated!
