### ISSUE TITLE
Need an API method like compileClient body with dependencies too

### ISSUE THREAD

**Issue by domenic** [jadejs/jade#1705]
Would help with making https://github.com/domenic/jadeify/pull/19 be one pass instead of two.

**Comment by ForbesLindesay** [comment]
I've added a slightly clunky api for this.  I feel like it's a bit dirty but probably best to just go with it as it solves a very real use case and people who don't need it should be able to just ignore the api they don't use.

It will be released as part of the next version of jade.

**Comment by domenic** [comment]
Would love a release with this.
