### ISSUE TITLE
Escaping and Multiline when using #[ ]

### ISSUE THREAD

**Issue by smaili** [jadejs/jade#1723]
I've run into a couple of issues when using the #[ ] syntax and I'm starting to think they may be bugs so I'm posting them here to confirm :)

Here's the two issues I'm experiencing:

 1. Using an apostrophe

        p.
            #[strong John's strong text] is really strong.

    Error message:

       `The end of the string was reached with no closing bracket found.]`

 2. Using multiple lines

        p.
            #[strong This strong text is really really long. This strong
            text is really really long. This strong text is really really
            long.]

    Error message:

       `The end of the string was reached with no closing bracket found.]`

I've tried solving both problems by adding `\` but no luck.

**Comment by ForbesLindesay** [comment]
This will be fixed in v2.0.0 (the new jade-lexer/jade-parser modules already have this problem fixed).  In the mean time:

```jade
p.
    #[strong John#{"'"}s strong text] is really strong.
```

Works, although it's a big ugly.

**Comment by paulpflug** [comment]
thanks for the workaround :)

looking forward for 2.0.0

**Comment by msmaili** [comment]
Yes, I second that. Thank you Forbes!

**Comment by msmaili** [comment]
Just out of curiosity, will 2.0 also allow multi-line commenting that does not actually end up in the rendered content?

Assuming no, would something like the following be possible to include in 2.0:

```
//*
My multi-line comment.
*//
```
This follows the current method of commenting by starting with `//`, but also adds the `*` to signal multiple lines. Off the top of my head, some possible variations in case the above can't be done, could be `//-*` or `//-/*`, but they feel a little lengthy :)

**Comment by netlovers** [comment]
You can use multi-line comments like this:
```jade
//-
  This is comment,
  and multi-line
```

**Comment by nachiketkumar** [comment]
I'm running into the same error with a `//` inside of a `#[code ...]`. For example:

`#[code git clone https://github.com/jadejs/jade.git]` results in an error message:

`The end of the string was reached with no closing bracket found.`

Escaping with `\`doesn't work. `#[code git clone https:/github.com/jadejs/jade.git]` works (only a single `/` after `https:`) and so does `#[code npm install jade]`.

Modifying it to:

`#[code= 'git clone https://github.com/jadejs/jade.git']`.

I guess tl;dr is a `//` can also cause the same error message.

**Comment by TimothyGu** [comment]
A work around is this:

```jade
#[code= 'git clone https://github.com/jadejs/jade.git']
```

**Comment by mrsean2k** [comment]
Use of `//` also affects cases where an embedded link is "self describing", i.e.

````jade
p This link to #[a(href="http://www.google.co.uk") http://www.google.co.uk] will fail
p But this #[a(href="http://www.google.co.uk") http:www.google.co.uk] will work
````

Continuations are predictably (but only in hindsight for me) fine:

````jade
p I believe 
  a(href="http://www.google.co.uk") 
    | http://www.google.co.uk
  |  will also work
````
If you need to do that sort of thing a lot, a `mixin` can help:

````jade
mixin linkit(url)
  a(href="#{url}") #{url}

//
// ... intervening code ...
//

p This also works #[+linkit('http://www.bing.com')] so hurrah for Jade
````
The mixin also has the advantage of cutting down the noise of duplication in the source where you want to embed deep links etc.

**Comment by ForbesLindesay** [comment]
This should be fixed in the master branch, which you can try via:

    npm install jadejs/jade

**Comment by mrsean2k** [comment]
A passing comment that a) the fix notwithstanding, I was surprised the inline mixin works and it feels like it should make other useful behaviour possible and b) in the space of a few weeks I've flipped from "why would I want to get to grips with another templating langage to "why can't I use this everywhere". Really neat design tradeoffs.

**Comment by ForbesLindesay** [comment]
Incidentally, you could write your mixin a bit more neatly as:

```jade
mixin linkit(url)
  a(href=url)= url
```

1. attributes are implicitly JavaScript expressions.  No need to use the interpolation syntax there.
2. `=` is the preferred way of making the entire content of a tag come from a JavaScript expression, interpolation is intended to be for handling simple expressions in the middle of large blocks of text.

**Comment by bretthayes** [comment]
The use of `#{"'"}` is quite ugly and can mess with syntax highlighting. You could always use an html entity for your apostrophe.

**Jade**:
```jade
p The #[strong chief&#39;s] golden warthog is still a mystery.
```

**HTML Output**:
```html
<p>The chief's golden warthog is still a mystery.</p>
```
