### ISSUE TITLE
Entities in Objects/JSON attributes are not properly encoded.

### ISSUE THREAD

**Issue by dantman** [jadejs/jade#1732]
When using the object/json attribute syntax (`div(data-json=json)`) strings containing an entity-like string are not properly encoded when output into the HTML attribute.

```js
$ node
> var jade = require('jade')
undefined
> var html = "These are &quot;quotation&quot; marks.";
undefined
> var json = { html: html };
undefined
> var template = 'html\n\
...   body\n\
...     div(data-json=json) ...\n\
... ';
undefined
> console.log(jade.render(template, { json: json }));
<html></html><body></body><div data-json='{"html":"These are &quot;quotation&quot; marks."}'>...</div>
undefined
```

This results in client side JS reading data-json to get `{"html":"These are "quotation" marks."}`, this results in a SyntaxError completely breaking the JSON attribute.

So & need to be encoded as &amp; in the process that stringifys json and outputs it.

**Comment by TimothyGu** [comment]
Closing as #1733 is closed.
