### ISSUE TITLE
Breaking out the components

### ISSUE THREAD

**Issue by ForbesLindesay** [jadejs/jade#1745]
I'm currently in the process of refactoring jade and splitting things out into separate components.  This should make things a bit cleaner for the jade forks such as react-jade and then-jade as they will be able to depend on just the components that they use.

## Current State

Currently the jade compiler looks something like this:

![old_jade](https://cloud.githubusercontent.com/assets/1260646/5126216/4a56a89c-70c3-11e4-86c8-4f0c52f6cadd.png)

The lexer is fairly simple in that it just takes a string as input and then acts as a stream of tokens.  The tight coupling with the parser makes it a bit brittle, but other than that it's not bad.

The parser is a huge messy beast.  It has a direct dependency on the lexer, rather than being given a stream or array of tokens.  Until recently it would send messages back to the lexer to tell the lexer about things like pipeless text.  This is a mad idea that we have now fortunately removed.  The parser is also responsible for resolving dependencies, so it recursively calls itself to parse each dependency, then links them together.  This means that there is no such thing as the abstract syntax tree of a jade file without including the dependencies.

## Proposal

My proposal is that we split out a separate "Linker" as many other languages would do.  The linker is responsible for joining the many separate ASTs together into one master AST to be given to the compiler.  This is currently the messiest (buggiest) bit of jade, so by putting it in its own module, everything else should get simpler and hopefully that will make it easier to maintain jade and find bugs.  The resulting system would look something like:

![new_jade](https://cloud.githubusercontent.com/assets/1260646/5126215/46a0996a-70c3-11e4-9370-429d8500f1a9.png)

Note that I have renamed what used to be called the Compiler to be called the Generator.  The key thing to note is that the lexer, parser, linker and generator have no inter-dependencies.  They are simply given an inert data structure (lexer: string of jade, parser: array of tokens, linker: collection of ASTs, generator: AST) and return another inert data structure (lexer: array of tokens, parser: AST, linker: AST, generator: string of JavaScript).  They also don't perform any file system operations, as all file system operations will be performed by the compiler (it will recursively read and parse files/dependencies).

**Comment by luin** [comment]
Has there been any progress on the issue?

**Comment by ForbesLindesay** [comment]
There is some, slow, progress being made.  I have a working implementation, but error handling needs a lot of work.

**Comment by Rush** [comment]
Cool! Looking forward to that version... Chrome has started printing out that sync loading of XHRs is gonna be deprecated but this is the only way I can load those includes right now (inside https://github.com/encharm/require-jade-ng)

Having it the async/promise way would fix it.

**Comment by ForbesLindesay** [comment]
This is now (mostly) finished.  Check out the master branch if you're interested.

**Comment by Rush** [comment]
Thanks for this work! Love jade. You wouldn't have plans to also do async, would you? :)
