### ISSUE TITLE
SVG version of logo

### ISSUE THREAD

**Issue by pedromaltez** [jadejs/jade#1785]
Can we have an official SVG version of the logo? It would help with HiDPI screens. Or maybe someone can tell me the font used and I can recreate it.

**Comment by TimothyGu** [comment]
I'll trace it if I have time

**Comment by TimothyGu** [comment]
Here: https://github.com/TimothyGu/test/blob/gh-pages/JadeFinal.svg (http://timothygu.github.io/test/JadeFinal.svg)

**Comment by TimothyGu** [comment]
Can't get Inkscape to use the thicker Futura Heavy font, so hope Medium is OK. Can't find a free Helvetica font so using Nimbus Sans L as the tagline (which comes bundled with Ghostscript on Ubuntu).

**Comment by jacobp100** [comment]
You can use Helvetica in the SVG if it's rasterised.

**Comment by pedromaltez** [comment]
@jacobp100 I think by free @TimothyGu meant which he couldn't download it for free. It doesn't come included with Ubuntu, and unless you source it through shady ways you have to pay for it. You don't want to rasterise it though (even if it's true that you can use it when rasterised). It's okay to use it (even in vector form) as long as the font isn't included with the file. So you can just convert the letters to dumb points once you're done playing with the font.

I actually spent a while trying to replicate the logo but I couldn't replicate the weird cut out effect. I could only get a flat 'jade', though it pretty much matched perfectly in shape. I think it's because the thicker Futura font is an OS X thing. Here's a png export of where I got to. Hard to see cause the original logo is almost all white.

![jade-logo](https://cloud.githubusercontent.com/assets/1254431/5636010/0b715486-95e6-11e4-84ad-34eba5d6f208.png)

**Comment by TimothyGu** [comment]
@pedromaltez I ended up redesigning the logo (especially the shade). See https://github.com/jadejs/jade/pull/1809#issuecomment-68622007

**Comment by jacobp100** [comment]
Sorry, I didn't mean rasterise. I meant convert the text to bezier curves.
