### ISSUE TITLE
Feature Request: @checkbox, @radio etc.

### ISSUE THREAD

**Issue by jacobp100** [jadejs/jade#1792]
Have built-ins mixins to make adding form elements easier. Use @ symbol to not conflict. A brief example would be.
```
builtin checkbox(name)
    label
        input(type='checkbox', value=name)
        block content
```

**Comment by q2dg** [comment]
+1

**Comment by alejonext** [comment]
@ForbesLindesay  This can be solved with a library

**Comment by ForbesLindesay** [comment]
@alejonext I agree.  What I do want is a better solution for importing libraries from jade files in npm.

**Comment by ForbesLindesay** [comment]
This will be solved in 2.0.0 via `import` declarations.

**Comment by alejonext** [comment]
@ForbesLindesay where is the documentation? or commit?

**Comment by ForbesLindesay** [comment]
doesn't exist yet.  I'm attempting to clear out all the issues as many are duplicates and then I will build a new roadmap.  Expect a roadmap within the next 48 hours.

**Comment by FranzSkuffka** [comment]
@ForbesLindesay `import` possible yet?
