### ISSUE TITLE
Optimise Attribute Order for Compression

### ISSUE THREAD

**Issue by jacobp100** [jadejs/jade#1793]
#a.b.c should render `<div class="b c" id="a">` over putting `id` first so GZip compression can compress the file more. `id` should be about the last item in the tag.

**Comment by alejonext** [comment]
I do not think that has to do, since in the DOM does not affect. The question is where affect that order?

**Comment by ForbesLindesay** [comment]
We could definitely consider doing this.  I don't think it should be a problem for anyone, but we should definitely not put it in until 2.0.0 as it could be a breaking change for some people.

**Comment by TimothyGu** [comment]
We can, but why? This kind of microoptimization isn't that useful. Plus *if* we are doing this @ForbesLindesay how can this be a breaking change?

**Comment by ForbesLindesay** [comment]
could be a breaking change for people generating xml or inspecting the actual text generated.  i.e. someone may be able to inspect the order of the attributes.  I think it's pretty minor but it's possible.

One option that I quite like would be to support doing this via a plugin in 2.0.0 as I intend to provide a way to add plugins that modify the AST.

**Comment by jacobp100** [comment]
It will probably break tests, but other than that, it's not a breaking change. The compression comes in as `<div class="` will be repeated a lot more, and that helps Gzip.

**Comment by TimothyGu** [comment]
@jacobp100, ah OK. The idea looks fine.

**Comment by TimothyGu** [comment]
PRs available: jadejs/jade-attrs#6 and jadejs/jade-runtime#16.
