### ISSUE TITLE
Duplicate class attributes

### ISSUE THREAD

**Issue by EloB** [jadejs/jade#1794]
Made a small test that duplicates class names.

https://gist.github.com/EloB/85f06cc95276223e2486

**Comment by EloB** [comment]
Is this the expected behaviour?

**Comment by ForbesLindesay** [comment]
No, it's a bug in our attribute merging that assumes the value passed to `&attributes` won't be reused (I think)

**Comment by EloB** [comment]
Okay

**Comment by ForbesLindesay** [comment]
This will be fixed in the next version of jade.

**Comment by EloB** [comment]
Thanks! :)
