### ISSUE TITLE
Lines starting with <tabs> <comma> are not parsed correctly

### ISSUE THREAD

**Issue by jlhffmn** [jadejs/jade#1800]
In a Jade file indented with tabs, I created an angucomplete-alt directive.  Since it had several attributes, I put a separate attribute on each line.  When I put the comma separators at the beginning of the line the commas were not removed by the Jade conversion to HTML.  

This error did not occur if the commas were at the end of the line or if the tabs were replaced with spaces.

**Comment by alejonext** [comment]
Using no commas
```
.content
    div(angucomplete-alt
        placeholder="Material auto-complete"
        pause="500"
        selected-object="MaterialInfo.Material"
        local-data="MaterialInfo.materialList"
        search-fields="key,description"
        title-field="key,description"
        match-class="angucomplete-highlight"
        minlength="3")
```
