### ISSUE TITLE
Directly render mixis

### ISSUE THREAD

**Issue by DinisCruz** [jadejs/jade#1811]
I just went though a number 'mixins related issues' but was not able to find a clean answer, so here is the question (sorry if there is an obvious solution).

**Is there a way to programmatically render mixins?**

I would like to create a web page that shows rendered mixins (with GET or POST data passed into the mixin as params). 

The objective is to allow the easy development of unit-tests that target that mixin (and quick browser visualisation of an mixin rendering)

**Comment by TimothyGu** [comment]
> Is there a way to programmatically render mixins?

Sorry but I don't really understand the question. mixins are part of the jade file, which I wouldn't call "programmatic." You can put a local in the mixin that gets resolved on rendering time, like this:

```jade
mixin test(subject)
  p Information on #{subject}
  p Query: #{req.params.query}
  p ID: #{req.params.id}
  p Requested URL: #{req.url}

- var someOtherVariable = 'blah'

+test(someOtherVariable)
```

with data like:

```js
locals.req = {
  url: 'http://example.com'
, params: {
    query: 'query'
  , id: 'uuid-1234'
  }
}
```

**Comment by TimothyGu** [comment]
If you mean using the mixin as a function in JavaScript, a regular Jade script without any mixin should be able to do that.

**Comment by DinisCruz** [comment]
What I needed was [something like this](https://github.com/TeamMentor/TM_4_0_Design/blob/master/node/services/Jade-Service.coffee#L77-L85)

```coffee
    renderMixin: (file, mixin, params)=>
      safeFile      = file.to_Safe_String()                   # only allow letter, numbers, comma, dash and underscore
      safeMixin     = mixin.to_Safe_String()
      dummyJade     = @.mixins_Folder.path_Combine('/tmp.jade')  # file to be provided to jade.compile (used to resolve the mixin file path)
      code = "extends #{@.mixin_Extends}    \n" +            # add html head and body (with TM css, but no nav bar)
             "include #{safeFile}.jade      \n" +            # imports mixin file
             "block content                 \n" +            # where rendered mixin will be placed
             "  +#{safeMixin}                 "              # mixin to render
      return jade.compile(code, {filename: dummyJade })(params)
```
which allowed me to render the mixins like this 

![](https://cloud.githubusercontent.com/assets/656739/5653069/d3365764-96ae-11e4-9049-0e64528ee0f1.png)

see https://github.com/TeamMentor/TM_4_0_Design/issues/212#issuecomment-69090060 for a couple more examples

**Comment by grrowley** [comment]
Oh no, I am so late to this issue but I know exactly what @DinisCruz means...I want to use pug to build a style guide. Also I want to adhere to atomic design. So...I have this mixin:

`mixin primary-button(tag, url, target, classes, text)
    #{tag}.btn.btn--primary(href=url, target=target, class=classes)
        if text
            text
        else if block
            block
        else
            | My Primary Button`

I want the mixin so I can use it inside molecules, components, and pages. But for the styleguide I would like to be able to just render the mixin.

@DinisCruz I found a work around by reading the file and using a regex to strip the mixin tag but this isn't worth sharing as it's super specific to a users knowledge.

**Comment by bora89** [comment]
The practical usage is very simple: use same mixin in the template and also if you need to update just that part - you can do that from the controller - no need additional pug file to wrap it and return it to the client. I talk about node server & HTMX in this example. Yes you can do it without mixin - but you are locked to the variables names used in the first render. Hope I was clear 😂
