### ISSUE TITLE
Mixin To String

### ISSUE THREAD

**Issue by jacobp100** [jadejs/jade#1812]
Proposal,
`%mixin(...)` returns the evaluated mixin as a string. E.g.
`p= %mixin` === `p: +mixin`

Use case:
```
script
    | var template = $('
    = (%mixin).replace('\n', '\\n').replace("'", "\\'")
    | ')
```

**Comment by jacobp100** [comment]
As an alternative to 1813

**Comment by ForbesLindesay** [comment]
I think the best bet might be to support runtime-filters so you could do something like:

```js
script
    | var template = $(
    :stringify
      +my-mixin
    | )
```
where `:stringify` is a filter that executes at runtime.

**Comment by jacobp100** [comment]
Thanks!

**Comment by ForbesLindesay** [comment]
Mixins are being overhauled as part of 2.0.0 and runtime filters are being actively considered.
