### ISSUE TITLE
File inclusion through filename-string hash

### ISSUE THREAD

**Issue by okvic77** [jadejs/jade#1815]
Is just a feature I'll love to see soon, or work me on that.

I don't have the files on a folder, the ones to be compile, I take them from the database. But the includes and extends files are all on the database. How I can revert the files to be used on Jade?

Like:
```node
var jade = require('jade');

var options = {
includeResolver: function(){},
extendResolver:function(){},
// or just
resovlerFile: function(){return text}
};
// Compile a function
var fn = jade.compile('string of jade', options);

// Render the function
var html = fn(locals);
```

Thanks.

**Comment by ForbesLindesay** [comment]
This is currently not possible.  Even if we added the API it wouldn't be very useful as database access should be asynchronous and jade compilation is always synchronous.  In jade 2.0.0 we will support passing a custom loader, which will do exactly what you're after.
