### ISSUE TITLE
Fix all the examples

### ISSUE THREAD

**Issue by TimothyGu** [jadejs/jade#1819]
Many examples don't work. The example test doesn't even work. It just tries to `require` it and exit normally it it breaks. That's not good.

TODO:
- [ ] Fix the test
- [x] csrf.js
- [x] dynamicscript.js

**Comment by ForbesLindesay** [comment]
I think I intended to put a `throw ex;` after https://github.com/jadejs/jade/blob/master/test/examples.js#L20.  I did definitely catch at least one bug while writing that test, so it must have worked at some point but I probably never committed that version.

**Comment by TimothyGu** [comment]
Yes, that is one of the bugs I want to fix. A second one is splitting the test into pieces so when one example fail other examples are tested as well. A third one (optional) is testing if the example outputs proper output.

**Comment by TimothyGu** [comment]
@ForbesLindesay If you have a branch with a working test, feel free to give a pointer.

**Comment by TimothyGu** [comment]
See #1821.

**Comment by ForbesLindesay** [comment]
no, I probably never actually committed it and even if I did it would probably be on a computer I don't even own now.
