### ISSUE TITLE
Cache overrides empty string

### ISSUE THREAD

**Issue by jenius** [jadejs/jade#1826]
So if you pass jade an empty string to render, and also pass it a `filename` in the options, rather than returning an empty string as you would expect, it reads the file and returns the file's contents. For example:

```js
console.log(jade.render('', { filename: 'some_file_path' }));
```

This will log out the contents of the file at the path, rather than an empty string. Any content at all in the string will negate this:

```js
console.log(jade.render('p hello', { filename: 'some_file_path' }));
```

This renders the correct string, regardless of whether that's actually the contents of the file, as you'd expect.

**Comment by samccone** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 
literally broke all my sites

**Comment by TimothyGu** [comment]
First, sorry about this. I broke something when cleaning up the caching a while ago.

Second, why in the world are you passing an empty string to jade, *with a file name set*? This is extremely counter intuitive.

**Comment by jenius** [comment]
Hahah I was wondering whether you would ask that or not. It's kind of a long story, but I promise there's a good reason behind it. The gist of it is that in the build system I work on, there are certain ways to override the compile pipeline with a different custom compile other than the default. If you do this, it zeros out the content for the main compile such that it doesn't compile twice. After this crazy bug chase I also have realized that I should just skip the compile altogether if there is an empty string coming in or an override, so I'm adding that in as well for the future :wink:

**Comment by TimothyGu** [comment]
OK then.

**Comment by jenius** [comment]
Thanks guys! :sparkling_heart:

**Comment by samccone** [comment]
:clap: thanks @TimothyGu your the best!
