### ISSUE TITLE
Add a way to compile jade expression to variable in unbuffered code

### ISSUE THREAD

**Issue by PerfectCarl** [jadejs/jade#1830]
I have created a [question on stackoverflow](http://stackoverflow.com/q/28034107/740464) about this and the general consensus is that it is not possible at the moment.

So I file a feature request in that effect.
What do you think about it?
Is it reasonable?

**Comment by TimothyGu** [comment]
I don't appreciate this idea. JS is JS. Jade is Jade. Mixing the two together in a JS statement looks weird and might be ambiguous in some cases.

**Comment by TimothyGu** [comment]
See my answer on SO. The workaround to https://github.com/jadejs/jade/issues/631#issuecomment-58777037 works there as well.

**Comment by ForbesLindesay** [comment]
This is not currently possible.  It may be made an option in jade 2.0.0 but would work slightly differently (i.e. named blocks for mixins)
