### ISSUE TITLE
docs on 'jade.compileFileClient'

### ISSUE THREAD

**Issue by ssbunny** [jadejs/jade#1832]
Add a description about `jade.compileFileClient` in the API docs.

**Comment by enlore** [comment]
I've put an entry in the docs for this method illustrating it's invocation and use, but I'm having trouble installing all of the deps for Jade ([ForbesLindesay/transformers](https://github.com/ForbesLindesay/transformers) in particular), which means that I can't fire up the docs site to see how my changes look.  I'll submit the pull request without actually viewing my changes if need be, but I feel like that's a really dumb idea.

As a disclaimer, let me say that this is my first time contributing to an open source project, so if I do anything stupid, please tell me.

**Comment by enlore** [comment]
Ah, nevermind.  Just figured out why transformers wasn't installing.  I'll fix that too in a bit.  Pull request coming shortly.

**Comment by TimothyGu** [comment]
> As a disclaimer, let me say that this is my first time contributing to an open source project, so if I do anything stupid, please tell me.

Nope, you did everything right. That's the power of open source.

**Comment by ssbunny** [comment]
> That's the power of open source.
但是解决不了语言问题，哈哈。

**Comment by TimothyGu** [comment]
For the uninitiated, @ssbunny said:

>> That's the power of open source.
> But the problem of i18n cannot be solved [this way]. Haha.

----

@ssbunny:

当然可以。说中文的人在那里都有 ;)

我如果有时间的话会更新中文的 Jade 参考。

----

@ssbunny,

Of course it can be solved. I believe at least the Jade community is fairly international (me!).

For example, there is a Chinese version of the documentation (API and language), albeit outdated, here: https://github.com/jadejs/jade/blob/master/Readme_zh-cn.md

I'll try to get it up-to-date if I find time.

**Comment by ssbunny** [comment]
被误会了。我的意思是解决不了我英文差的问题，不是说不能从技术上解决多语言问题。只是个玩笑。

**Comment by ForbesLindesay** [comment]
lol
