### ISSUE TITLE
Ability to pass child templates as strings

### ISSUE THREAD

**Issue by coolaj86** [jadejs/jade#1842]
Is there a way to not use the file system (at all)? Only strings?

For example, let's say you have the following `jadestr`:

```jade
include 'xyz.jade'
```

And I want to compile it without accessing the filesystem and provide the includes as options or locals object:

```javascript
jade.compile(
  jadestr
, { partials: {
      'xyz.jade': "div\n  div\n  include 'abc.jade''"
    , 'abc.jade': "h1 Happy Day!'"
    } 
  }
);
```

Is that possible? Or in the roadmap at all?

**Comment by ForbesLindesay** [comment]
No.  You can't do this, but in v2.0.0 you will be able to override the loader, which would let you do this fairly easily.
