### ISSUE TITLE
Multiple basedir values

### ISSUE THREAD

**Issue by bfred-it** [jadejs/jade#1844]
Is it possible to include from different folders? This would avoid having to go through a jungle of `../../../` or repeat a common folder often — say most files are in `app/templates` but many are in `assets/inline-scripts`.

Perhaps something a-la-$PATH: `basedir=app/templates:assets/inline-scripts`

**Comment by ForbesLindesay** [comment]
No, this is not supported.  If you find yourself doing this, I suggest attempting to simplify the structure of your views directories.  The intention is that you set your `basedir` value to the actual root directory of your application and then do things like:

```jade
extends /layouts/main-layout.jade

block content
  include /partials/navigation.jade
  script
    include /scripts/my-script.js
```

This makes the template easier to **read** because it's obvious from reading the template where you need to look to find the corresponding files.  If you have multiple look up like you suggest, you have to check through multiple directories to find the corresponding file.

**Comment by mikaelwikman** [comment]
Hi. I'm working at a major company and we need this feature for a shared component library. CoffeeScript can do it, Stylus can do it, so I don't see any reason why Jade should be any different.

Any chance this issue can be re-opened?

**Comment by mikaelwikman** [comment]
As we need this right away, we've made a patch to enable this feature. The patch simply splits the basedir by semicolon and searches each path in given order.

The patch is for v1.9.4. Sorry for the CoffeeScript.

```coffeescript
# This patches 'jade' library to allow multiple basedirs separated by comma

Parser = (require 'jade').Parser
fs = require 'fs'
p = require 'path'
dirname = p.dirname
basename = p.basename
join = p.join

# override resolvePath from Jade 1.9.4 (jade/lib/parser.js row 480)
Parser.prototype.resolvePath = (path, purpose) ->

    if path[0] != '/' and not @filename
        throw new Error('the "filename" option is required to use "' + purpose + '" with "relative" paths')

    if path[0] == '/' and not @options.basedir
        throw new Error('the "basedir" option is required to use "' + purpose + '" with "absolute" paths')

    if basename(path).indexOf('.') == -1
        path += '.jade'

    basedirs = @options.basedir.split(';')
    if path[0] == '/'
        newpath = null
        for b in basedirs
            p = join(b, path)
            if fs.existsSync(p)
                newpath = p
                break

        if newpath
            path = newpath
        else
            throw new Error("Could not find #{path} in any of the folders [#{basedirs.join(', ')}]")

    else
        path = join(dirname(@filename), path)

    return path

```
