### ISSUE TITLE
doctype error handling

### ISSUE THREAD

**Issue by tjsail33** [jadejs/jade#1845]
Had a mistake on my part the other day using multiple cursors where I opened a file, scrolled down, and long story short ending up modifying the `doctype html` line of my file to `?cache=1doctype html` and i was surprised when this didnt throw a jade error. Just a suggestion to make doctype checking more stringent.

**Comment by TimothyGu** [comment]
How is Jade supposed to know `?cache=1doctype` is meant to be `doctype`? It is understandable for Jade to need to warn on `doctype this-doctype-doesnt-exist` but I don't think it is Jade's responsibility to check every single tag.

**Comment by tjsail33** [comment]
Im not suggesting an autocorrect of the error, but i dont see why the checing for the doctype tag cant be made something like /^doctype (html,other1,other2)$/

**Comment by TimothyGu** [comment]
Are you suggesting to check every jade document for a doctype? Keep in mind that simple test cases like

```jade
p Paragraph
```

should work.

**Comment by tjsail33** [comment]
I guess that is fair. Possibly say if /doctype/ && /^doctype/ ? It could just be and'ed onto the check already performed. This is getting more complicated than I anticipated. That's what I get for being up so late I guess.

**Comment by TimothyGu** [comment]
OK, this discussion is getting nowhere. There is no check currently performed on `doctype`, nor do we plan to add any. Sorry for this terse comment as my eyes are half-closed as I am typing this.
