### ISSUE TITLE
Error when `exports` is undefined

### ISSUE THREAD

**Issue by monokrome** [jadejs/jade#1847]
I've run into an issue where [some][exa] [users][exb] of a project that I work on have seen `exports is not defined` in their browser when including `runtime.js`. After looking at `runtime.js`, it seems that it is using `exports` without even defining it or checking that it exists:

This line is causing an error when executed in a browser:
https://github.com/jadejs/jade/blob/master/lib/runtime.js#L15

It seems that jade is possibly making the assumption that all apps using the runtime are using common.js - or maybe jade's build process has changed and I need to include some other files?

[exa]: https://github.com/monokrome/jaded-brunch/issues/15
[exb]: https://github.com/monokrome/jaded-brunch/issues/14

**Comment by ForbesLindesay** [comment]
/lib/runtime.js is for CommonJS.  You need to just use /runtime.js as that has been precompiled using browserify to run in non-CommonJS environments

**Comment by ForbesLindesay** [comment]
This has always been the case

**Comment by monokrome** [comment]
Thanks for letting me know. The other one did work a year or so ago :)

**Comment by monokrome** [comment]
@ForbesLindesay Thanks for the help!
