### ISSUE TITLE
Support Polymer Syntax

### ISSUE THREAD

**Issue by CoreMaker** [jadejs/jade#1848]
Polymer has a syntax like this: ```div(id='backdrop', hidden?='{{ hasBackdrop }}')```

Is there a way to compile `?=` and print it out as it is?

I've tried using pipe text as shown in below:

```
div(id='backdrop',
    | hidden?='{{ hasBackdrop }}'
)
```

Result:
```<div id="backdrop" |="|" hidden?="{{ !hasBackdrop }}"></div>```

The result is near to what I want to get, but requires some post-processing workaround. So anyone knows how to solve this problem without using the pipe text? Thanks.

**Comment by CoreMaker** [comment]
Ok. I found the problem cause. For those who has the same problem, please bear in mind that DO NOT USE SINGLE QUOTE TO WRAP YOUR ATTRIBUTE VALUE. Thanks.

**Comment by ForbesLindesay** [comment]
This works completely fine as you originally suggested:

```jade
div(id='backdrop', hidden?='{{ hasBackdrop }}')
```

That works because we accept `?` as part of the key, so for example the following also works:

```jade
div(id='backdrop', hidden? ='{{ hasBackdrop }}')
```

but this doesn't:

```jade
div(id='backdrop', hidden ?='{{ hasBackdrop }}')
```

**Comment by CoreMaker** [comment]
Weird then. 'Cause the problem fixed after I've changed it to single quote. Anyway, thanks for the reply. :D
