### ISSUE TITLE
jade.selfClosing in Jade v2

### ISSUE THREAD

**Issue by TimothyGu** [jadejs/jade#1849]
Should we continue shipping jade.selfClosing in Jade v2?

See https://github.com/jadejs/jade/blob/master/lib/index.js#L25-L27 The recent update in void-elements made the `Object.keys` thing needed, which looks fairly ugly.

**Comment by hemanth** [comment]
I would vote for exporting the new object form.

**Comment by ForbesLindesay** [comment]
I vote for not exporting anything in v2.  People should not be modifying that list anyway.  If they need that list they can depend on void-elements directly.

**Comment by TimothyGu** [comment]
@ForbesLindesay said:

> I vote for not exporting anything in v2. People should not be modifying that list anyway. If they need that list they can depend on void-elements directly.

+1.
