### ISSUE TITLE
Dynamic Mixin Names?

### ISSUE THREAD

**Issue by CREEATION** [jadejs/jade#1852]
Hello!

So I just implemented "dynamic mixins" (https://github.com/jadejs/jade/issues/631#issuecomment-70590841), works fine.
What I'm trying to do is declaring them in an `each` iteration and append an index to the mixin name.

Something like this:

```jade
each item, index in data
    mixin #{'tab' + index}
```

Is that possible somehow?

**Comment by ForbesLindesay** [comment]
No.  It's not possible.  It's also probably a really bad idea, for all the same reasons you shouldn't create a function inside a loop in JavaScript.

Perhaps you could describe what you're attempting to achieve and we can try and figure out a better way of doing it?

**Comment by CREEATION** [comment]
Thanks for your reply!
I made a "tabs element" mixin:

```jade
mixin tabs(tabs)
	- var std_active = true
	- tabActive = function (t) { return t.active ? 'active' : '' }

	each tab, index in tabs
		if tab.active === true
			- std_active = false

	.rt-wrapper.tabs.retab
		ul.rt-tabs.tabs__head
			each tab, index in tabs
				if std_active && index === 0
					- tabs[index].active = true

				li.rt-tab.tabs__head-item(class=tabActive(tabs[index]))
					if tab.icon
						span.icon(class=tab.icon)
					span.tab-title= tab.title

		.rt-tabs-content.tabs_wrapper
			each tab, index in tabs
				.rt-tab-content.tab_content(class=tabActive(tabs[index]))
					+#{'tab' + indexString(index)}
```

and call it like this:

```jade
+tabs([
    { title: 'Tab 1' },
    { title: 'Tab 2' }
])
    mixin tab01
        h1 Wello Horld

    mixin tab02
        h1 Hello World
```

My problem here now is that I pass data to the template via a json file and want to create the content dynamically, so I can't just type out `mixin tab01` etc. as I don't know how many tabs there may be.

Do you have an idea how to achieve this? :(

**Comment by ForbesLindesay** [comment]
I would suggest inverting it:

```jade
mixin tabs(tabs)
    - var tabActive = function (t) { return t.active ? 'active' : '' }

    mixin tab(index)
        - tabs[index].body = block;
    block

    - tabs[0].active = tabs[0].active || !tabs.some(function (t) { return t.active; })
    .rt-wrapper.tabs.retab
        ul.rt-tabs.tabs__head
            each tab in tabs

                li.rt-tab.tabs__head-item(class=tabActive(tab))
                    if tab.icon
                        span.icon(class=tab.icon)
                    span.tab-title= tab.title

        .rt-tabs-content.tabs_wrapper
            each tab in tabs
                .rt-tab-content.tab_content(class=tabActive(tab))
                    - tab.body && tab.body()

+tabs([
    { title: 'Tab 1' },
    { title: 'Tab 2' }
])
    +tab(0)
        h1 Wello Horld

    +tab(1)
        h1 Hello World
```

The use of the internal `block` variable may break in 2.0.0, but If it does, there will definitely be a relatively easy fix for it.

**Comment by CREEATION** [comment]
Holy moly, thanks for your quick reply!
I just tested your code and now I get this: `Anonymous blocks are not allowed unless they are part of a mixin.`
Seems to be the lonely `block` on line 6. Any ideas? =(

**Comment by ForbesLindesay** [comment]
You can work around that bug by doing:

```jade
- block && block()
```

instead of just:

```jade
block
```

but it will be fixed in the next release.

As for the off by one error, remember that the indexing of the array is base `0`.

**Comment by CREEATION** [comment]
Thanks, that fixes the block bug.
Shouldn't this produce the right output (as I expect)?

```jade
- var data = [{ title: 'Tab 1' },{ title: 'Tab 2' }]

+tabs(data)
    each tab, index in data
        +tab(index)
            h1= tab.title
```

**Comment by CREEATION** [comment]
No idea? :(

**Comment by TimothyGu** [comment]
I'll take a look.

**Comment by CREEATION** [comment]
Thank you, I was trying to make it work the last 2 days without success :'(

**Comment by TimothyGu** [comment]
@CREEATION changing this:

```js
+tabs(data)
    each tab, index in data
        +tab(index)
            h1= tab.title
```

to 

```js
+tabs(data)
    each tab, index in data
        +tab(index)
            h1= this.title
```

makes it work.

The cause is some nasty JavaScript closure rules, so the value of `tab` is inherited from a closure that declares `tab` elsewhere in a loop; and because JS variables are function-wide the outdated tab just stayed there, causing `Tab 2` to be printed.

**Comment by CREEATION** [comment]
Awesome, thank you for your support! :+1: :raised_hands:

**Comment by TimothyGu** [comment]
@CREEATION No problem. Three (days) is the charm ;)

**Comment by ForbesLindesay** [comment]
Also, you can now update to the latest jade and remove the block hack :)
