### ISSUE TITLE
Why not each key, val  in Obj ?

### ISSUE THREAD

**Issue by kalasoo** [jadejs/jade#1853]
Now, jade supports iterations like

```jade
each val, key in {'a': 1, 'b': 2, 'c':3}
    ...
```

Why not use `each key, val`? This is more intuitive and consistent with many other languages.

**Comment by monolithed** [comment]
For example:

```js
Array#forEach(value, index, context)
```

**Comment by ForbesLindesay** [comment]
The reason is that the value is usually much more useful so the Metis optional.  It's conventional to put optional things last.  It's too late to change it now in any case.  Lots of people depend on it being the way it is.
