### ISSUE TITLE
Watcher unwatches after saving jade file with VIM

### ISSUE THREAD

**Issue by pavel** [jadejs/jade#1854]
The thing I've discovered after my pull-request #1851 was merged.
This affects only VIM users, and basically because of the awkwardness of VIM's save.

I'll fix it and create pull request.
Sorry for the inconvenience.

**Comment by TimothyGu** [comment]
Thanks for spotting this. I had the same experience when I was doing abff32cd5f5f02df4724031c139003cf56a42c96.

**Comment by pavel** [comment]
Also when saving with VIM, sometimes jade throws ENOENT error for a sec, and then another watch event arrives, and the file renders fine. I'll fix it as well, to  prevent this awkward error from being logged.

**Comment by TimothyGu** [comment]
Basically it seemed that vim deletes the file, resulting in an ENOENT and/or `fs.existSync()` failure.

**Comment by pavel** [comment]
@TimothyGu Right, that's what happening.
