### ISSUE TITLE
Does Jade support multiple file extends?

### ISSUE THREAD

**Issue by ivanjuras** [jadejs/jade#1856]
I want to alter one block from one extend file, and another block from the other extend file, all in the same file that will extend the other 2. Is this possible with Jade?

**Comment by ivanjuras** [comment]
For example, I have a post file: **mypost.jade**.

This post file will extend 2 files, **template-1.jade**, and **template-2,jade** like this:

extends template-1
extends template-2

Now, the template-1 file has a block called block-1, and template-2 file has a block called block-2.

In the mypost.jade file I will have code like this:

block block-1
  Do something.....

and somewhere else,

block block-2
  Do something else....

**Comment by TimothyGu** [comment]
I don't think so AFAIK. You can extend a file that extends another file, but not extending two files at once. Plus, implementation of it would be difficult.

**Comment by ForbesLindesay** [comment]
Can you give a complete example of what you would want?  Three jade files plus the desired html output.

**Comment by ivanjuras** [comment]
It's simple; it would be great if Jade was able to extend multiple other Jade files. Let me give you another example:

Say I have 2 Jade templates: **single-post.jade** and **category-list.jade**

Now, I would create **my-post.jade** with the actual content post inside of it. Also, I would extend the **single-post.jade** with the main content, and I would also extend **category-list.jade** with the post excerpt (maybe I'd append the excerpt).

My website would have a single-post.html - where the whole post would be, and the category-list.html, where all the posts in that category (their excerpts) would be.

**Comment by ForbesLindesay** [comment]
The thing you want is an include.  If `my-post.jade` extends `single-post.jade`, the resulting html file would be called `my-post.html`, and is the result of rendering `my-post.jade`.  What you want to do is have `my-post.jade` and then `include` it from both `single-post.jade` and `category-list.jade`.  If the text is not the same, you may want to have something like `my-post-summary.jade` as well.

Feel free to continue posting if you have questions, but I'm closing this as jade already has the feature you're actually after.

**Comment by ivanjuras** [comment]
@ForbesLindesay , I'm not quite sure what you mean, could you elaborate it a bit more please?

**Comment by ForbesLindesay** [comment]
Your goal is to write content into one jade file, then use that content in two other jade files.  Am I right?

**Comment by ivanjuras** [comment]
@ForbesLindesay, yes, but the two other files should be completely independent of themselves.

**Comment by wifiextender** [comment]
@ivanjuras 

**skeleton.jade** / boilerplate

```jade
doctype html
html(lang='en')
  head
    meta(charset='utf-8')
    meta(http-equiv='X-UA-Compatible', content='IE=edge')
    meta(name='viewport', content='width=device-width, initial-scale=1.0, maximum-scale=1.0')
    block Title
      title Hakuna Matata
  body
    block content
```

**single-post.jade**

```jade
extends ./skeleton.jade

block content
 ...
 ...
 ...
```

**category-list.jade**

```jade
extends ./skeleton.jade

block content
 ...
 ...
 ...
```

You can put stylesheets, scripts in a `block` and use **append** to add more content for the particular `block`.

Once you compile the templates into standalone html files they'll inherit and replace the `block` content.
