### ISSUE TITLE
Unescaped Buffered Block?

### ISSUE THREAD

**Issue by CREEATION** [jadejs/jade#1857]
Hello there!

In a mixin I use a block which gets populated with data from a JSON file.
Now that data also has for example `<br>` in it and they get escaped, which is bad.

```jade
mixin td
	td: span: block
```

How can I output the block unescaped with this mixin?
Also it's inline because otherwise there is unnecessary whitespace in the output.

**Comment by TimothyGu** [comment]
It's not the mixin's fault it is expanded:

```jade
mixin td
    td: span: block

+td
    != "<>"

+td
    = "<>"
```

```html
<td><span><></span></td>
<td><span>&lt;&gt;</span></td>
```

How you *call* mixin determines if it is escaped or not.

**Comment by CREEATION** [comment]
Oh boy, didn't had that in mind somehow.
Thank you!
