### ISSUE TITLE
More useful error message on `each`

### ISSUE THREAD

**Issue by morenoh149** [jadejs/jade#1858]
doing
```
each link in navLinks
  foo
```
where `navLinks` was undefined I got this error message
```
  express:router <anonymous>  : /% +0ms
  express:view lookup "500.jade" +1ms
  express:view stat "/Users/harrymoreno/programming/r3dm/shpesfba/templates/views/500.jade" +0ms
  express:view render "/Users/harrymoreno/programming/r3dm/shpesfba/templates/views/500.jade" +0ms
TypeError: /Users/harrymoreno/programming/r3dm/shpesfba/templates/layouts/default.jade:48
    46|           button.navbar-toggle.collapsed(type='button', data-toggle='collapse', data-target='#navbar-collapsable')
    47|             span.sr-only Toggle navigation
  > 48|             span.icon-bar
    49|             span.icon-bar
    50|             span.icon-bar
    51|           a.navbar-brand(href="/")
 
Cannot read property 'length' of undefined
    at jade_debug.unshift.lineno (eval at <anonymous> (/Users/harrymoreno/progra
```
is there any way to mention `each` instead or in addition to the `length` error?

**Comment by ForbesLindesay** [comment]
Adding additional detail to the error message is a possible option, but does come with a slight performance overhead.  What we should definitely be able to do is fix the line number it reports, so at least you would see the `each` being the line jade tells you has an error.  Is there any chance I could have a copy of the entire jade file so I can reproduce the problem and figure out why the line being reported is wrong?  Also, have you checked you're running the latest version of jade?

**Comment by morenoh149** [comment]
I wasn't running the latest but close 1.8.0 or so.
here's a reference to where I handled it https://github.com/r3dm/shpe-sfba/commit/14c93107bf439ee554cf81dea0ca95dedf46224e you can clone and rollback to the previous revision to see the error. You may have to supply a dummy s3 token to run the project.

**Comment by ForbesLindesay** [comment]
Thanks, this still occurs on latest.  A minimal example that demonstrates the problem is:

```jade
script.
  a
  a
  a
  a
  a
  a
= (
```

which produces the error:

```
Jade:2
    1| script.
  > 2|   a
    3|   a
    4|   a
    5|   a

Unexpected token )
```

even though the error is on the last line.

**Comment by ForbesLindesay** [comment]
With the latest version, this should now report the correct line number.
