### ISSUE TITLE
A logic-less/loop-less data format of jade, similar to YAML/XML/JSON?

### ISSUE THREAD

**Issue by gavinengel** [jadejs/jade#1862]
Jade has a great way to represent  attributes, that is missing from YAML and JSON:
```
h1 (title="foo", bar="baz"): "Lorem Ipsum"
```

I also like that Jade allows comments, while JSON doesn't.  I can see how a subset of jade without the logic, variables, and loops could be a useful filetype for storing data.  Perhaps one can think of Jade as similar to JavaScript, and this "Jade-lite" as like JSON.  It would also be nice to be able to represent simple arrays (without a key)  in Jade, which would be important for a data format.

Has there been any thought given to this idea of a separate "Jade-lite" file extension with explicitly no logic possible?

**Comment by rlidwka** [comment]
What's wrong with YAML?

**Comment by vendethiel** [comment]
"No attributes" (in the first sentence)

**Comment by rlidwka** [comment]
This yaml document would be the same:

```yaml
h1: {title: 'foo', bar: 'baz', content: 'Lorem Ipsum'}
```

So... what's wrong with it?

**Comment by ForbesLindesay** [comment]
@gavinengel there may be merrit to a new data storage format.  I would say attributes are a red herring here.  The key thing you need in a data storage format like this is to closely match the data model of popular programming languages (like JavaScript).  This is what JSON does extremely well.  If you want that format to be written/edited by humans, it's also useful if it has support for comments, as well as not requiring the verbose extra quotes around attributes.  Finally, there are a few things we might often want to store that JSON does not allow us to (e.g. Dates, Binary Data, Regular expressions, perhaps even functions but then we're in dangerous territory).  [json-literal](https://github.com/ForbesLindesay/json-literal) was my attempt at creating just such a format, but it's fair to say that it isn't that popular.

In general I would suggest:

 - for complex data, use JSON (It's a shame it doesn't have comments, but other than that it's pretty good)
 - for simple configuration, use [toml](http://demos.forbeslindesay.co.uk/toml/) (It's a really nice format designed specifically for writing configuration files)

In any case, this is definitely out of scope for jade.

**Comment by rlidwka** [comment]
> for complex data, use JSON (It's a shame it doesn't have comments, but other than that it's pretty good)

I would respectfully disagree. JSON is a data serialization format, not a config file format. Every time you try to write json by hand, you're doing it wrong.

It's not only about comments. JSON messes up with git diffs because of trailing commas, it doesn't support dates, has a lot of unnecessary double quotes. It isn't even a proper JS subset it claims to be.

But config format problem is already solved by YAML, JSON5, HJSON and dozens of other less popular formats, so I don't see any need for creating a new one.

**Comment by ForbesLindesay** [comment]
The reason I still ultimately suggest JSON is that:

1. YAML is absolutely **horrible**.  It has so many needless opportunities to get confused about what syntax is what, it's far easier to have something that at least resembles JavaScript.
2. All the other formats are sufficiently unpopular that they're not very useful for interop.

**Comment by gavinengel** [comment]
Thanks for consideration all.  I appreciate the pointing out of various other formats, json-literal, toml, json5, hjson.  I do see the merits of forcing a strict key-value system without attributes in data formats.  At the same time, I feel its a shame to lose information on what items are placed in the Jade/XML tag-attribute and not in the value.  There is some value to using attributes over child elements, although I can see why doing so makes using the data in programming languages, and storing it in databases, tougher/slower.  Maybe attribute metadata (like ARIA accessible or lang attributes) is a benefit to browser-only markup and not so much to databases. Shrug.  Even so, it would be nice to retain such information.

Not to beat a dead horse, as I think the Jade devs are understandably trying to close this ticket :-) Here is where something is lost in translation:

Orig Jade:
```jade
h1 (title="foo", bar="baz", lang="en"): "Lorem Ipsum" # I am a comment
```

Into JSON:
```json
{"h1": {"title": "foo", "bar": "baz", "lang": "en", "content": "Lorem Ipsum"}}
```

Back into Jade:
```jade
h1
  title: foo
  bar: baz
  lang: en
  content: Lorem Ipsum
```

They are different.  Anyways, I'll leave it at that.  Thanks.
