### ISSUE TITLE
v2: return promises

### ISSUE THREAD

**Issue by jonathanong** [jadejs/jade#1864]
would be nice :) for backwards compatibility, maybe we should just make it `require('jade/then')` for now.

**Comment by ForbesLindesay** [comment]
Jade is synchronous and Promises are for async so they don't make sense here.  We support callbacks for backwards compatibility and to match the interface that express supports, but they're not actually called asynchronously.

**Comment by jonathanong** [comment]
oi should probably stop using `.xxxxFile()` then and do that myself
