### ISSUE TITLE
Multiline variables

### ISSUE THREAD

**Issue by iliakan** [jadejs/jade#1865]
The issue existed before, but was closed cause @tj found "no reason" in it.
But actually, there must be a way to pass "presentation data" in templates. There is no contradiction multiline VS presentation at all.

Do I get it right that as of now one can't declare `- var` in multiple lines?

Is there a workaround like "including a js-file" ?

P.S.
```
- var obj = {
-   name: "Vasya",
-   age: 30
- }

each prop in obj
  p= prop
```

Compiles and works with `jade -D` (no-debug), but fails with debug. 

P.P.S.  I just want to let the colleague who does markup to specify "example data" for it w/o writing lots of JS. Any advice for that?

**Comment by TimothyGu** [comment]
@iliakan #796 reopened. This issue closed as a dupe.
