### ISSUE TITLE
Using markdown-it

### ISSUE THREAD

**Issue by JosefJezek** [jadejs/jade#1870]
Could you explain how to use markdown-it with Jade `include` instead of `marked`?

`include:md pages/home.md`

https://github.com/markdown-it/markdown-it/issues/57

**Comment by TimothyGu** [comment]
Jade uses transformers for markdown rendering, which only supports marked, supermarked, markdown-js, or markdown: https://github.com/ForbesLindesay/transformers/blob/2.1.0/lib/transformers.js#L425

Please file a bug in jstransformers/jstransformer#1. (jstransformer is the successor to transformers)

**Comment by JosefJezek** [comment]
Please add `markdown-it`, jstransformer support it now. ;-)

See https://github.com/jstransformers/jstransformer/issues/1#issuecomment-74781810

**Comment by JosefJezek** [comment]
Please Reopen issue.

**Comment by TimothyGu** [comment]
@JosefJezek It will be fixed with the release of Jade 2.0.0.

**Comment by JosefJezek** [comment]
:+1:
