### ISSUE TITLE
passing to a mixin data with the argument name "block" don't work 

### ISSUE THREAD

**Issue by sinsunsan** [jadejs/jade#1875]
When using "block" as the argument name of a mixin, the value is not passed
````jade
mixin signinBlock1(data)
  - console.log('the SIGNIN BLOCK !!!!!! block', data);

mixin signinBlock2(block)
  - console.log('the SIGNIN BLOCK !!!!!! block', block);

- var data = {id: "signin", text: "Create an account"};
+signBlock1(data)
//- >>> the SIGNIN BLOCK !!!!!! {id: "signin", text: "Create an account"}

+signBlock2(data)
//- >>> the SIGNIN BLOCK !!!!!! undefined
````

I was thinking that all arguments name was available when creating a mixin. 
Is it normal ? Or a bug ?
If it is normal, it should be documented....

**Comment by alejonext** [comment]
Well, the word `block`, is a key word for Jade if you change the word works.

**Comment by TimothyGu** [comment]
Yes it is reserved. See http://jade-lang.com/reference/mixins/#blocks

I think this is already documented fairly clearly that `block` is a keyword so I'm going to go ahead and close this.

**Comment by sinsunsan** [comment]
ah ok, it's impossible  to use it, because the "block" name can be used in the mixin content, and thus, there would have been no way to distingish the block as mixin argument from the block reserved word ...
But for example, as it is not possible to define mixin in mixin, using a argument name "mixin" would be allowed ? Of course, it's not the best name, but to be sure I've understood, if all jade reserved word are forbidden, or only the one that might be used in the context of a mixin.

mixin myAwesomeMixin(mixin)
   div(class=mixin.class)=mixin.text

Would fail ?

**Comment by alejonext** [comment]
If you can send a pull, to understand a little of what you are proposing. It would be much better!
