### ISSUE TITLE
Question: class as object

### ISSUE THREAD

**Issue by iliakan** [jadejs/jade#1876]
Is it possible to use an object of classes: conditions?

For example, now I have:
```jade
tag(class="lesson #{article.children ? 'level_1' : ''}")
```

That's ugly. Much better could be:
```jade
tag(class={lesson: true, level1: article.children})
```

Is something close doable?

**Comment by alejonext** [comment]
Would not it be better that way ??

```jade
- var classes =  [ 'lesson',  article.children ? 'level_1' : '' ];
tag( class=classes )
```

**Comment by TimothyGu** [comment]
I have to agree with @alejonext. The object syntax looks weird for me.

**Comment by iliakan** [comment]
The object syntax comes from libraries like React.JS and Angular.JS which use it extensively, it's actually more convenient.

**Comment by iliakan** [comment]
P.S. Did I miss the point? Is any flavor of such syntax available in Jade now? The text version is definitely the ugliest.

**Comment by TimothyGu** [comment]
@iliakan Yes I know the text version is ugly. I'm saying that the array method from @alejonext looks fine and that method is [supported by AngularJS](https://code.angularjs.org/1.3.14/docs/api/ng/directive/ngClass).

**Comment by iliakan** [comment]
I've seen mainly object notation in angular projects. But that's my experience only.

It'd be cool to have the array notation or the object notation or both.

**Comment by ForbesLindesay** [comment]
We already have both.  We've had the array notation for years and object notation since 1.8.0 (https://github.com/jadejs/jade/blob/master/History.md#180--2014-11-28)

**Comment by ForbesLindesay** [comment]
It's even in the documentation http://jade-lang.com/reference/attributes/

**Comment by TimothyGu** [comment]
Sorry for not spotting it sooner.

**Comment by iliakan** [comment]
Thank you so much @ForbesLindesay.
