### ISSUE TITLE
Comments added  variable is not compiled, the possibility of increasing?

### ISSUE THREAD

**Issue by icloudedu** [jadejs/jade#1878]
Comments added  variable is not compiled, the possibility of increasing?

**Comment by TimothyGu** [comment]
What do you mean by "comments added variable"? Can you give an example of 1. what you want in Jade, 2. what you want in HTML, and 3. what you get in HTML?

**Comment by alejonext** [comment]
I assume you do that
```jade
- var hello = "wolrd";
\\ This is my var #{hello}
```
But is it for?

**Comment by TimothyGu** [comment]
If so, then it is a dup of #1311.

**Comment by icloudedu** [comment]
```jade
- var hello = "wolrd";
<!--This is my var #{hello} -->
```
