### ISSUE TITLE
[Feature Request] jade --watch like a compass

### ISSUE THREAD

**Issue by GreanMaster** [jadejs/jade#1880]
first I'm sorry for my lang,

On jade we must have to fill argument every file after "jade --watch" like "jade --watch index.jade 404.jade" i think it not make any sense

On compass i just config path with "glob" (ex. ```path/to/file/**/*.sass``` not sure i use it long time) and  i just use "compass watch" command it will "watch" for change any file with glob pattern (ex. change, create, move,remove)

thank you very much :)

**Comment by TimothyGu** [comment]
You can execute `jade --watch *.jade` in a shell. Implementing glob patterns in Jade seems out of scope.

**Comment by ForbesLindesay** [comment]
There may be some (limited) argument for this on the grounds that windows does not support globs, but it does pass them through to the underlying program so that it can handle them internally.

**Comment by pluma** [comment]
FWIW, no need to implement glob patterns if [glob](https://www.npmjs.com/package/glob) and [minimatch](https://www.npmjs.com/package/minimatch) exist.
