### ISSUE TITLE
Jade's official icon?

### ISSUE THREAD

**Issue by cloud-walker** [jadejs/jade#1882]
Hi, i'm a fan of jade

I'm in progress with my sublime-text theme project: [sliver](https://github.com/cloud-walker/sliver-theme).

I'm a about to write down the sidebar icons, and I've noticed that there is no official jade icon...

I know is not a big issue, but I was wondering if it was planned...

Thanks in advance!

**Comment by ForbesLindesay** [comment]
Our official logo is http://jade-lang.com/logos/JadeBlack.svg but I would love us to have more of an icon style logo.  It just requires someone with some design skill picking it up.  I'm definitely happy to take suggestions :)

**Comment by cloud-walker** [comment]
I'm not a professional designer, but I think at something like the ruby-lang icon, just to offer my opinion...

I'll try something if I get the chance :)

**Comment by TimothyGu** [comment]
I would recommend using the "j" in the logo.

How is your subl theme going to look like? If it's monochrome I would recommend using the JadeBlack.svg, but if not you might have some luck using the logo on http://jade-lang.com/ (which is PNG unfortunately; I didn't get the chance of drawing it in Inkscape yet).

See #1785 and #1809.

**Comment by GarthDB** [comment]
@ForbesLindesay I'd like to help out with some branding. I'm a long time fan of both Jade and Stylus and I think they could both use a refresh. The logo should reflect the amazing flexibility of this project.

I started a while ago on some branding ideas and I've posted them to [Pixelapse](https://www.pixelapse.com/GarthDB/projects/Jade/jade_branding_options.ai). I actually ordered some of the rabbit stickers to see how they looked, and I'm pretty happy with them.

Let me know if this is something you'd like me to keep working on.

**Comment by GarthDB** [comment]
Probably doesn't hurt to post a screenshot in here:
![image](https://cloud.githubusercontent.com/assets/125516/7031730/f235e1c6-dd2a-11e4-91bb-b3de832d9ef1.png)

**Comment by greasan** [comment]
Please, not rabbits. :)

How about the stone with this amazing color?
Or some code oriented icons.

Let me know if you need help. I am not a logo designer but an educated media designer with little experience in logos and the right tools.

**Comment by GarthDB** [comment]
@greasan you don't like the rabbit?

The idea behind d, e, and f is to be like an east asian [seal](http://en.wikipedia.org/wiki/Seal_(East_Asia)). There are some great parts to using this metaphor:
* The higher quality seals are often made from Jade.
* They used a red ink (which gives us an additional color to contrast the obvious green).
* In some areas/time periods they were commonly square, which works nicely for a mark.

I went with the rabbit because of chinese zodiac - it was the animal for 2011, but technically Jade was started in 2010 so maybe we should look at using the tiger if we wanted to go with that.

Here's a photo of the stickers I made:
![img_8584](https://cloud.githubusercontent.com/assets/125516/7034793/3d3b5308-dd40-11e4-8865-c97ff292aef6.jpg)

**Comment by TimothyGu** [comment]
I really like the shape of the rabbit, but the mixing of color between green and red looks kinda odd. You might also want to consider keeping our current wordmark. Jade is supposed to be an elegant language, and I think the movements of rabbits are at least more elegant than those of tigers.

Full disclosure: I was born in the year of the rabbit so I have naturally inclined to use rabbit :)

**Comment by GarthDB** [comment]
@greasan I steered away from the code metaphors because they are a bit obvious, and not really a trend with frontend tools. Most are a bit playful or geometric. Flat and minimal are definitely in style. Here's a comparison of a few common tool logos:

### Sass
![image](https://cloud.githubusercontent.com/assets/125516/7035161/4312cad8-dd43-11e4-8ae9-ea644b7d74c0.png)
with it's iconic glasses 
![image](https://cloud.githubusercontent.com/assets/125516/7035179/67674bac-dd43-11e4-90b2-d2b54a8871aa.png)

### Bourbon
![image](https://cloud.githubusercontent.com/assets/125516/7035184/7515d1f6-dd43-11e4-9d51-d84c41e60e42.png)

### Jekyll
![image](https://cloud.githubusercontent.com/assets/125516/7035191/84204cf8-dd43-11e4-8f84-5402bd939b16.png)

### Grunt
![image](https://cloud.githubusercontent.com/assets/125516/7035221/c45d63f0-dd43-11e4-9cf4-c5bf6db36ff2.png)

### Ember
![image](https://cloud.githubusercontent.com/assets/125516/7035232/d736e578-dd43-11e4-9fc0-ea70896ad6ca.png)

### Foundation
![image](https://cloud.githubusercontent.com/assets/125516/7035241/e8d0c2c2-dd43-11e4-868b-4d0858b8bb9a.png)

### Bower
![image](https://cloud.githubusercontent.com/assets/125516/7035257/f3a2e6b2-dd43-11e4-88fe-b4010c764886.png)

**Comment by GarthDB** [comment]
@TimothyGu The mixing I'm using is a blend mode and a common printing technique. http://blog.spoongraphics.co.uk/articles/showcase-of-designs-made-with-cool-overprint-effects

**Comment by GarthDB** [comment]
It could actually be created using two stamps.

**Comment by GarthDB** [comment]
Another nice logo using a blend mode for [IFTTT](https://ifttt.com/):
![image](https://cloud.githubusercontent.com/assets/125516/7049594/f19df11a-ddd7-11e4-8e5d-97080cf0f7fe.png)

**Comment by ForbesLindesay** [comment]
I think d and e are my personal favourites.  Bunnies are far more cute and loveable than tigers, so I'm fine with the bunny personally.  I wonder if it shouldn't have more hard/clean/straight lines to match the minimalism that the language is aiming for?  Branding really isn't my thing though, so I'm happy to go with what other people think.

**Comment by GarthDB** [comment]
@ForbesLindesay we can have a clean icon mark that we can use in different cases. If we lose the rough edges it might lose the seal imagery a bit, but I could be wrong. I'll make the change and we can take a look.

**Comment by jbnicolai** [comment]
Wow, loving the icons you drew up, @GarthDB. I'm torn between C, E and F, but I think E is my favorite :)

**Comment by GarthDB** [comment]
Thanks @jbnicolai.  I think those are my favorites as well. I really like **E** but for things like a website header, **D**'s typeface might be more readable, and it's a bit stronger.

**Comment by ForbesLindesay** [comment]
My inclination was to go with **D** for the website header and README header, but use **e** for the [twitter profile](https://twitter.com/jade_templates) (which currently has the most garish shade of green I've ever seen as it's profile pic), stickers to hand out at conferences, the favicon and anywhere else that requires a square icon.  I really like the idea of how we could gradually scale that, reducing detail for smaller sizes (e.g. the favicon probably wouldn't need the "jade" text and could just be the red stamp with the bunny in it.

**Comment by jbnicolai** [comment]
@ForbesLindesay Completely agree!

**Comment by GarthDB** [comment]
@ForbesLindesay Here's a simplified path for the stamp. It smoothes out some of the rough edges, but still leaves the feeling of a stamp. 

![image](https://cloud.githubusercontent.com/assets/125516/7057349/ecfad030-de11-11e4-921d-e5f12a2ba381.png)

**Comment by GarthDB** [comment]
I could smooth out the bottom even a bit more, give me a second.

**Comment by GarthDB** [comment]
ok - here's a super smooth path @ForbesLindesay 
![image](https://cloud.githubusercontent.com/assets/125516/7057410/a2e3fd5e-de12-11e4-917d-a5de41b0908f.png)

**Comment by GarthDB** [comment]
Let me know what you think. If you don't have any more changes I can start putting together the formats you might need and a cohesive design for jade-lang.com

**Comment by GarthDB** [comment]
Also the source artwork is on [Pixelapse](https://www.pixelapse.com/GarthDB/projects/Jade/jade_branding_options.ai) if anyone wants to download and play with it.

**Comment by ForbesLindesay** [comment]
My slight OCD makes me want to join up the little gap in the bottom and smooth off the chunk that's taken out of the right hand side.  It might remove some of the character of the image though, which would be a shame, and I have no idea what other people would prefer.  Maybe we could try and A-B test a few options :smile:

**Comment by ForbesLindesay** [comment]
Really appreciate all the work you're putting into this. I'm really happy to be told that other people prefer the rougher edges if that's the case.

**Comment by GarthDB** [comment]
I'll play with that a bit tomorrow.


Don't stare at it too long, it'll start to look weird to you after awhile :)

**Comment by ForbesLindesay** [comment]
I wish I could look at it with fresh eyes, the more I stare the less sure I am as to what I authentically think.

**Comment by GarthDB** [comment]
I'll do some a,b,c comparisons and it'll help nail down what you prefer. It's easiest to tell a note is off when it's in the context of correct notes.



—

**Comment by GarthDB** [comment]
Here are some options:
![jade_branding_options_option 1](https://cloud.githubusercontent.com/assets/125516/7074781/6473b3ea-deba-11e4-9407-2a7971629ea3.png)
![jade_branding_options_option 2](https://cloud.githubusercontent.com/assets/125516/7074783/64767c42-deba-11e4-9bd8-b240f6222693.png)
![jade_branding_options_option 3](https://cloud.githubusercontent.com/assets/125516/7074782/647590fc-deba-11e4-934b-636f99984bc7.png)
![jade_branding_options_option 4](https://cloud.githubusercontent.com/assets/125516/7074784/647e06f6-deba-11e4-87b2-fbf99e816085.png)

And an animated gif, because they are fun:
![jade_branding_options](https://cloud.githubusercontent.com/assets/125516/7074721/de93861a-deb9-11e4-8319-bc74581776a5.gif)

**Comment by GarthDB** [comment]
On the spectrum, option 1 is closest to an actual seal mark:
![image](https://cloud.githubusercontent.com/assets/125516/7074825/9f2f87f2-deba-11e4-92a8-ad618bbc1486.png)

While option 4 is the cleanest.

**Comment by GarthDB** [comment]
I posted the options on dribbble as well and it was  [rebounded it](https://dribbble.com/shots/2013077-Jade-Seal). I really like it.

**Comment by ForbesLindesay** [comment]
I'm now leaning more towards option 1.  I think smoothing it out strips too much of the character away.  @jbnicolai @TimothyGu Do either of you have any opinions on this?

**Comment by GarthDB** [comment]
The rebound I posted above is like 1.5 :)

**Comment by ForbesLindesay** [comment]
I think 1.5 may be preferable to 1

**Comment by ForbesLindesay** [comment]
Are we ok to use that in terms of licensing?

**Comment by GarthDB** [comment]
Yup. We can have Jasmine turn it over.

**Comment by TimothyGu** [comment]
I'm OK with everything from 1-2.

**Comment by GarthDB** [comment]
![1.5](https://d13yacurqjgara.cloudfront.net/users/169279/screenshots/2013077/jade_seal_options.png)
I thought I would post the 1.5 mentioned above.

**Comment by ForbesLindesay** [comment]
Lets settle on 1.5.  I can't wait to get the website re-branded and finally give Twitter a proper icon :)

**Comment by TimothyGu** [comment]
Sounds good.

**Comment by GarthDB** [comment]
excellent - I would make one change.  It smoothes out just a parts of the rabbit does this work?

I'm putting together the social media images.  Also where is the repo for jade-lang.com? There's a `gh-pages` on the main repo, but it's an older site.

![jade_branding_final](https://cloud.githubusercontent.com/assets/125516/7092845/02e45004-df72-11e4-9047-806250f48812.png)

**Comment by TimothyGu** [comment]
@GarthDB no it's the current one.

**Comment by GarthDB** [comment]
oh I'm sorry, I had an old fork. I'll update with the main repo now.

**Comment by jbnicolai** [comment]
@ForbesLindesay @GarthDB I'm all for 1.5 as well!

**Comment by ForbesLindesay** [comment]
Looks awesome.  The source code for the website lives in the docs folder of the master branch.  It's a node.js website that we automatically build and push to go-pages after each release.

**Comment by GarthDB** [comment]
Ok. I'm working on a pull request with just the bare minimum to incorporate the new branding. I'll take some more time to work through some more cohesive design. I'll make sure to discuss the work openly.

Here is [a zip](https://dl.dropboxusercontent.com/u/113366/jade_avatar.zip) with twitter avatar and GitHub gravatar options.

I think we should be able to close this issue. I'll open new issues for new needs and work.

**Comment by GarthDB** [comment]
Let me know when the new avatars get posted, I'd love to tweet about it.

**Comment by GarthDB** [comment]
@cloud-walker back to your original question, here are the new official logos in svg format.
![Jade](http://garthdb.com/img/jade_branding/jade-01.svg)
![Jade](http://garthdb.com/img/jade_branding/jade-02.svg)
![Jade](http://garthdb.com/img/jade_branding/jade-03.svg)

**Comment by ForbesLindesay** [comment]
Awesome, twitter profile photo is published.  Any thoughts on cover photo/colour?

**Comment by GarthDB** [comment]
Yes, but they are just sketches for now. I'll flesh them out a bit with the website design.



—

**Comment by ForbesLindesay** [comment]
Awesome.  I've updated the README image as well, although I think it probably has slightly too much white space around it.  It looks fantastic on a mobile now.

**Comment by GarthDB** [comment]
I'll look at it with the website update.



—

**Comment by TimothyGu** [comment]
Looks very nice.

@ForbesLindesay said:
> although I think it probably has slightly too much white space around it

Yes same here, both on mobile and on desktop.

**Comment by GarthDB** [comment]
Made a pull request https://github.com/jadejs/jade/pull/1934 seriously, I think this should close this issue.

**Comment by acidjazz** [comment]
very proud of all this, i loved option D as well, nice work @GarthDB

**Comment by GarthDB** [comment]
@acidjazz thanks; still have more to do.

**Comment by cloud-walker** [comment]
Nice work! :smiley:
