### ISSUE TITLE
Option to escape angle brackets in text blocks?

### ISSUE THREAD

**Issue by evanw** [jadejs/jade#1884]
Not escaping angle brackets makes working with code really annoying:

```
pre.
  #include <iostream>
  int main() {
    std::cout << "hello world\n";
    return 0;
  }
```

This code generates the following undesirable output:

```
<pre>#include <iostream>
int main() {
  std::cout << "hello world\n";
  return 0;
}</pre>
```

What I want is something like this:

```
<pre>#include &lt;iostream&gt;
int main() {
  std::cout &lt;&lt; &quot;hello world\n&quot;;
  return 0;
}</pre>
```

It seems strange that angle brackets aren't escaped since I can already emit tags using the #[iostream] syntax if that's what I want. Is there a way to make jade compile text blocks as text?

**Comment by evanw** [comment]
I finally found a workaround. Add a custom filter using `jade.filters.escape = jade.runtime.escape` use it everywhere you have text content:

```
pre.
  :escape
    #include <iostream>
    int main() {
      std::cout << "hello world\n";
      return 0;
    }
```

If this is the intended solution, it would be very helpful to document the possibility of doing this on http://jade-lang.com/reference/plain-text/ since it's not obvious.

**Comment by chharvey** [comment]
I'm surprised this issue doesn't have a lot of support. There are many times in which one wants to demonstrate **HTML code** and needs the angle brackets escaped; it's painful to type and read when they have to be escaped manually.

**Comment by TimothyGu** [comment]
A -1 from me. How does Jade know if one wants to do this:

```html
<pre>hola from <strong>Timothy</strong></pre>
```

or if one wants:

```html
<pre>hola from &lt;strong&gt;Timothy&lt;/strong&gt;<pre>
```

?

Both are valid HTML, and have use case:

<pre>hola from <strong>Timothy</strong></pre>

<pre>hola from &lt;strong&gt;Timothy&lt;/strong&gt;<pre>

**Comment by ForbesLindesay** [comment]
This is what filters are for.  Jade has always supported inline html and I don't think it should remove support for inline HTML at this stage.  We will have built in support for an `escape-html` filter very soon.

**Comment by TokugawaTakesi** [comment]
@ForbesLindesay , 
Please at least leave us the possibility to write `&lt;`/`&gt;`  for code listings.

```
code.FunctionDeclaration.
   createArrayBasedOnOtherArray(originalArray: Array&lt;OriginalArrayElement&gt;, createNewArrayElement: (originalArrayElement: OriginalArrayElement) => NewArrayElement): Array&lt;NewArrayElement>&gt;
```

Would you please to keep this issue opened until adding `escape-html` filter?

**Comment by ForbesLindesay** [comment]
Since pug now uses jstransformers, you can install https://www.npmjs.com/package/jstransformer-escape-html and then:

```
pre
  :escape-html
    #include <iostream>
    int main() {
      std::cout << "hello world\n";
      return 0;
    }
```
