### ISSUE TITLE
SyntaxError: Unexpected token : , After fresh  install on Ubuntu 14.04

### ISSUE THREAD

**Issue by theblacksquid** [jadejs/jade#1885]
I have just made a fresh install of jade on an Ubuntu 14.04 machine using the 'sudo npm install jade -g' command on the terminal. After what looks like a successful install, it gives me [this](https://gist.github.com/theblacksquid/d0c57cbb491563d25528) output when I test it out using 'jade --help'.

I haven't been able to find any troubleshooting steps for this kind of error, but if this was an error encountered previously, I'd be happy to be redirected to it.

Thanks

**Comment by TimothyGu** [comment]
Hm for some reason it works perfectly fine here…

**Comment by ForbesLindesay** [comment]
What version of node.js are you using?

**Comment by theblacksquid** [comment]
sorry about the delay. I'm running on v0.4.12

**Comment by TimothyGu** [comment]
@theblacksquid 0.4.12 was released 4 years ago. We don't support such an old release. Plus IIRC Ubuntu 14.04 ships Node.js 0.10.25, so how exactly did you install Node.js?

We only support 0.10, 0.12, and io.js.

**Comment by theblacksquid** [comment]
I guess that explains it. I never installed it. It somehow came included with the machine. Thanks!!!
