### ISSUE TITLE
Rerendering dependencies does not work when child files are already watched

### ISSUE THREAD

**Issue by sodoku** [jadejs/jade#1888]
https://github.com/jadejs/jade/issues/1086 addressed watching father files and their children jade files. It does not work for me, if the children are already being watched. Please see the example for more explanations.

# Example

A `main.jade` which includes `a.jade` and `b.jade`

    ├── main.jade
    ├── includes/
        ├── a.jade (included from main.jade)
        ├── b.jade (included from main.jade)

## working

If I watch only the `main.jade`

```bash
jade -w *.jade
```

the files `a.jade` and `b.jade` are automatically watched (as they are a dependency from `main.jade`). If I change `a.jade`, `main.jade` will be rerendered.

## not working

If I watch all files

```bash
jade -w .
```

all files are being watched. But if I now change `a.jade`,  only `a.jade` will be rerendered. `main.jade` will  _not_ be rerendered.

**Comment by netlemur** [comment]
+1

**Comment by TimothyGu** [comment]
Darn it, now we actually have to build a tree of dependency.

**Comment by distilledhype** [comment]
I have the same issue. Is there a current workaround?

**Comment by TimothyGu** [comment]
@distilledhype not yet, until we merge my PR which will be in the next release (hopefully 2.0.0).

**Comment by distilledhype** [comment]
@TimothyGu OK. Good to know that it is fixed already though. Any idea when that will be?

**Comment by distilledhype** [comment]
@ForbesLindesay awesome that this is fixed now, but I assume I will have to wait until the release of Jade 2 in order to use it correct?

**Comment by ForbesLindesay** [comment]
You could try using the new https://github.com/jades/jade-cli which will replace the built in jade binary in 2.0.0.  It should already have all the updates.
