### ISSUE TITLE
-w make empty files

### ISSUE THREAD

**Issue by humbertocruz** [jadejs/jade#1894]
Hello,

I'm trying to use jade -w View/* and on the first render it's ok, but after this, every rerender produces a empty .html file. I'm using node 0.10.35

thanks

**Comment by humbertocruz** [comment]
Hi, well, i update the nodejs to 0.12 and now it is working. thanks

**Comment by TimothyGu** [comment]
We support Node.js 0.10, so I'm reopening this bug.

**Comment by TimothyGu** [comment]
Can you provide more information on how to reproduce this with Node.js 0.10? It works perfectly fine here. Also what OS are you using?

**Comment by humbertocruz** [comment]
Hello,

Sure, it's a Dreamhost VPN server with Debian 6.0.6 (Squeeze). But it's working after I upgraded the nodeJS to 0.12 and I can't test it with 0.10 anymore, sorry.

Humberto

**Comment by TimothyGu** [comment]
Oh well.
