### ISSUE TITLE
Feature Request: Defining a included file's name by variable

### ISSUE THREAD

**Issue by aegrey** [jadejs/jade#1897]
Currently, the ability to use a variable to specify the name of a file for include does not exist. Adding this feature would be beneficial!

Example:
```
    - var pages = ["one", "two", "three"]
    each val in pages
        //- #{val}
        div##{val}.container-fluid.section
            include ./pages/#{val}
```

See also: 
http://stackoverflow.com/questions/12132978/use-a-variable-in-a-jade-include
http://stackoverflow.com/questions/16579461/jade-doesnt-let-me-use-include-variable-in-a-mixin

**Comment by alejonext** [comment]
Can you give me an example

**Comment by TimothyGu** [comment]
This works:

```jade
//- index.jade
doctype html
html
  - var myVar = 'hola'
  include head
  body
    - var page = 'home'
    include body
```

```jade
//- head.jade
head
  title= myVar
```

```jade
//- body.jade
p This is #{page}.
```

```
jade --pretty index.jade
```

```
//- index.html
<!DOCTYPE html>
<html>
  <head>
    <title>hola</title>
  </head>
  <body>
    <p>This is home.</p>
  </body>
</html>
```

**Comment by aegrey** [comment]
@alejonext I updated the question I realized after reading it that it could be written in a way that made more sense. :) I also forked the repo to take a look at the code directly and see if it was even a possibility as I've not done so before.

**Comment by TimothyGu** [comment]
@aegrey oh you mean that. Sorry for the misunderstanding.

**Comment by TimothyGu** [comment]
@aegrey This is not supported for several reasons.

See:

- #416
- #569 
- #839 (with two [actually just one] workarounds)
- #843 
- #1312 (roadmap)
- #1433 
- #1481 
- #1893

**Comment by aegrey** [comment]
@TimothyGu Thanks! :) I should have searched closed tickets first. I see it's done at compile so that makes total sense. Appreciate your response!
