### ISSUE TITLE
You can't use "umlaute" in class/id shortcuts

### ISSUE THREAD

**Issue by HoffmannP** [jadejs/jade#1904]
e.g.

    #bücher(data-role="main")

results in

    <div id="nichtVerl">ängert(data-role="main")

**Comment by TimothyGu** [comment]
Dup of #1796

**Comment by ForbesLindesay** [comment]
I think this is aufficiently different to merit reopening.  These are part of people's language in a way that emoji aren't.

**Comment by ForbesLindesay** [comment]
On further reading of HTML specs, unicode only seems to be supported if escaped anyway, which doesn't seem like a sensible way to write code.  These kinds of mistakes will throw helpful error messages in 2.0.0 so we can always re-think how we handle this in the future.
