### ISSUE TITLE
Add an option to silent CLI

### ISSUE THREAD

**Issue by humbertocruz** [jadejs/jade#1905]
It's possible to do something like this ?

jade -w -E ctp Views/* -E html webroot/*

And jade generate ctp and html files for each directory ?

thanks

**Comment by TimothyGu** [comment]
No I don't think so. You can use two commands though at the same time.

**Comment by humbertocruz** [comment]
Yes, but the problem is the -w option.

**Comment by TimothyGu** [comment]
Wouldn't two `-w` work?

**Comment by humbertocruz** [comment]
Well, I tried here with a shell script and ending each command with &. It's working fine. Maybe a -s --silent option should be fine to avoid the "rendered" messages. Thanks

**Comment by pavel** [comment]
@humbertocruz Let's assume you have this script in your `package.json`:
```
{
  "scripts": {
    "build-html": "jade -w -E html webroot/*"
  }
}
```

For linux you can use: `npm run build-html > /dev/null` and you'll get all the stdout supressed.
For windows you can use: `npm run build-html >nul`.

**Comment by ForbesLindesay** [comment]
Moving to jade-cli project
