### ISSUE TITLE
Hierarchy is not preserved when in watch mode

### ISSUE THREAD

**Issue by yfr** [jadejs/jade#1906]
Started with `-w -H` to watch for changes compiles the correct hierarchy on first run but not when compiling the watched file again.

**Comment by sodoku** [comment]
Maybe related: https://github.com/jadejs/jade/issues/1888

**Comment by TimothyGu** [comment]
Yes I think it's #1888's fault. I'll fix it today.

**Comment by sodoku** [comment]
Awesome! Thank you very much

**Comment by TimothyGu** [comment]
Actually this is a separate bug. A fix for #1888 is already in the works. Will get to this soon.

**Comment by yfr** [comment]
I found that the `rootPath` in `renderFile` is not preserved in watch mode. When i save the `rootPath` in the `options.rootPath` object everything works fine. This might be an ugly hack. But maybe something fiddle around with.

**Comment by yfr** [comment]
Ah now i see you already made a pull PR. Nevermind
