### ISSUE TITLE
Error: cannot find module 'acorn/util/walk'

### ISSUE THREAD

**Issue by david-j-park** [jadejs/jade#1910]
I'm trying to use jade 1.9.2 in an express 4 app on node 0.10.13. Everything is installed via npm. This code:

`var jade = require('jade');`

throws the error `cannot find module 'acorn/util/walk'`. 

The same is true if I set jade as the view engine and try to render a page with `res.render()`.

**Comment by TimothyGu** [comment]
First, this is not a bug in Jade, as Jade does not use acorn in any way. It is most probably a bug in [acorn-globals](https://github.com/ForbesLindesay/acorn-globals), which does uses acorn/util/walk. Please file the bug there.

Second, it does not seem possible for this error to occur. Acorn did change its directory layout in acorn@1.0.0, but in acorn-globals' package.json acorn is pinned to ^0.11.0…

**Comment by ForbesLindesay** [comment]
This error occurs if you have an out of date version of npm.  Update to the latest version of npm and you won't have the problem anymore.  I've also updated acorn-globals now so it should be fixed if you delete node_modules then re-install.
