### ISSUE TITLE
Fix SVG logo on iOS

### ISSUE THREAD

**Issue by TimothyGu** [jadejs/jade#1912]
For some reason the main Jade text is hidden on iOS, probably because of the the shadow filter (unconfirmed).

![image](https://cloud.githubusercontent.com/assets/1538624/6884332/ac8c0af0-d5a1-11e4-918d-6f6ff043cc91.jpg)

**Comment by ForbesLindesay** [comment]
This should be naturally taken care of by #1912

**Comment by GarthDB** [comment]
Pretty sure you can close this one too.
