### ISSUE TITLE
single class and attribute order

### ISSUE THREAD

**Issue by szexigexi** [jadejs/jade#1914]
i would like to preserve attribute order in this case:
```jade
- var myClass = 'foo'
a(class=myClass, href='bar.html') this foo goes to bar
```

result:
```html
<a href="bar.html" class="foo">this foo goes to bar</a>
```

expected result:
```html
<a class="foo" href="bar.html">this foo goes to bar</a>
```

i think this could be related to the merging of the class attributes.

**Comment by TimothyGu** [comment]
See #1793.

> i think this could be related to the merging of the class attributes.

I believe that is the most probable cause.

**Comment by TimothyGu** [comment]
Is there any specific reason why you would like this to be implemented?

**Comment by skrzyszewski** [comment]
Apart from gzip advantages mentioned in the referenced issue [#1793](https://github.com/jadejs/jade/issues/1793), it would be great to have html attributes rendered in particular order for easier reading, see [Code Guide by @mdo](http://codeguide.co/#html-attribute-order).

**Comment by szexigexi** [comment]
@TimothyGu i recreate a lot of html in jade in a project and use diff to compare the original and the compiled html. everything seems perfect except the href attribute.

**Comment by ForbesLindesay** [comment]
This is specific to the `class` attribute, which we always append on the end.  I don't personally have the desire or time to look into this.  If someone wants to have a go, the relevant code is in https://github.com/jadejs/jade/blob/master/lib/compiler.js in the `attrs` function.

**Comment by skrzyszewski** [comment]
Anyone with the right skill set feeling like having a try?

**Comment by TimothyGu** [comment]
I don't think we can *preserve* the location of `class`, since it is possible that `class` is in many places: `&attributes`, `.class`, `(class='a')`. It just isn't practical to preserve the order for the sake of preserving it. Reordering the attributes for the sake of optimization is more sound however, and I'm closing this issue in favor of #1793.
