### ISSUE TITLE
Reserved words as jade variables now breaking due to with(js) dependency

### ISSUE THREAD

**Issue by jackspaniel** [jadejs/jade#1915]
https://github.com/ForbesLindesay/with/issues/7

https://github.com/marijnh/acorn/issues/235

FYI - in case anyone else sees this. I guess the with guys are working on it.

**Comment by hawkerboy7** [comment]
Due to acorn changing to 1.0.1 nodemodules "with" and "constantinople" give an error: 
```
Error: Cannot find module './state' from 'bla/bla/bla/acorn/dist'
```

**Comment by TimothyGu** [comment]
This is fixed by #1920.

**Comment by ForbesLindesay** [comment]
This should now be fixed if you clear all caches and re-install jade.

@hawkerboy7 your issue is an entirely separate issue that should be fixed by https://github.com/marijnh/acorn/pull/242

**Comment by ForbesLindesay** [comment]
Both issues should now be fixed if you re-install.

**Comment by hawkerboy7** [comment]
Yes all appears to be working! Thank you! =D
