### ISSUE TITLE
inline javascript gets confused by blank lines

### ISSUE THREAD

**Issue by gilesbowkett** [jadejs/jade#1916]
(Or, technically, the inline JavaScript feature gets confused when it encounters lines which are not blank, but which are preceded by dashes, and which represent blank lines of JavaScript.)

Everything's cool if I inline this code:

```jade
- function foo(bar) {
-   doStuff();
- }
```

But this code gets me dashes on my web page:

```jade
- function foo(bar) {
-
-   doStuff();
-
- }
```

The blank lines in the script have `-` and no spaces. You can use `-` plus any number of spaces as the start of a blank line, just not `-` on its own.

This also works:

```jade
- function foo(bar) {

-   doStuff();

- }
```

**Comment by gilesbowkett** [comment]
also, this:

```jade
- for (var i = 0; i < 100; i++) {
-
-   doStuff(i);
-
- }
```

puts about 200 dashes in the output.

**Comment by meodai** [comment]
for more than one line of JS it would be nicer to have something like #1919 anyway.

**Comment by TimothyGu** [comment]
@gilesbowkett said:
> Everything's cool if I inline this code:

> ```jade
- function foo(bar) {
-   doStuff();
- }
```

Actually, this is NOT supported. See #796. For example, the following would not work:

```jade
- function foo(bar) {
-   doStuff(
-   );
- }
```

You just got lucky that in your case every line can have a valid statement appended to it. See generated JS:

```js
function foo(bar) {
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: jade_debug[0].filename });
doStuff();
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: jade_debug[0].filename });
}
```

But in my case:

```js
function foo(bar) {
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: jade_debug[0].filename });
doStuff(
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: jade_debug[0].filename });
);
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: jade_debug[0].filename });
}
```

>
> But this code gets me dashes on my web page:
>
> ```jade
- function foo(bar) {
-
-   doStuff();
-
- }
```

Odd. It throws an error here with Jade 1.9.2:

```
Jade:2
    1| - function foo(bar) {
  > 2| -
    3| -   doStuff();
    4| -
    5| - }

unexpected text -
-  
```

> This also works:
>
> ```jade
> - function foo(bar) {
>
> -   doStuff();
>
> - }
> ```

Again this is another lucky case, and is not supported.

**Comment by ivanjuras** [comment]
Is this going to be implemented in the near future?

**Comment by ForbesLindesay** [comment]
We need to get better at supporting multi-line JavaScript.  We currently only support multi-line if the line break is directly inside a BlockStatement.  So what you're attempting to do **is** generally supported.  Not supporting blank lines is just a quirk of the lexer.  We can fix that pretty easily.  The problem of supporting multi-line expressions more generally as @TimothyGu points out, is much much harder.  It would require a complete overhaul of how we deal with errors in jade.  What we need to do is move away from inserting debugger statements and instead generate a source map.

**Comment by ForbesLindesay** [comment]
The dashes will be treated as block-code as part of the upgrade to jade@2.0.0
