### ISSUE TITLE
JS blocks

### ISSUE THREAD

**Issue by meodai** [jadejs/jade#1919]
for now every line of JS needs to be prefixed with `-`

```jade
- var foo, bar;
- for = "bar";
- bar = "foo";
```
it would be very useful to have something like this:

```jade
---
  var foo, bar;
  for = "bar";
  bar = "foo";
---
```
This would make it nicer to write larger chunks of JS in your jade files.

**Comment by TimothyGu** [comment]
See #796.

**Comment by meodai** [comment]
@TimothyGu yes its related. As mentioned in #761 I like the idea of having:

```jade
-
  var foo, bar;
  foo = "bar";
  bar = "foo";
```

we can close this issue than bun I think the title of #761 is miss-leading.
