### ISSUE TITLE
Cannot render `include` templates in loop

### ISSUE THREAD

**Issue by dopatraman** [jadejs/jade#1924]
Suppose I have a local variable that is a list of paths to include blocks:
```
locals = {
    templates: ['src/includes/header.jade', 'src/includes/footer.jade']
}
```
and my template is structured like this:
```
html
    head
        each template in paths
            include template
```

I get an error that says:
```
ENOENT, no such file or directory 'template.jade'
```

It seems to be reading the variable `template` (which should be a path, src/includes/header.jade) as the actual name of the file. How do I render include blocks in a loop?

**Comment by TimothyGu** [comment]
You are trying to include files **dynamically** through a loop. Dynamic inclusion is not supported.

See:

- #416
- #569 
- #839 (with two [actually just one] workarounds)
- #843 
- #1312 (roadmap)
- #1433 
- #1481 
- #1893
- & cetera

**Comment by dopatraman** [comment]
Is this a feature slated for a future release?

**Comment by TimothyGu** [comment]
@dopatraman No. See all those tickets.

**Comment by dopatraman** [comment]
thanks for the response
