### ISSUE TITLE
Variables is defined before `extends` keyword couldn't be used (got `undefined`)

### ISSUE THREAD

**Issue by hoangddt** [jadejs/jade#1930]
Hi, I got this problem.
The variable I define before `extends` keyword can't be used (got `undefined`). 
Here is the code snippet

```jade
//- simplePageTemplate.jade
- var a = "Hello from variable"
doctype
html
	head
		block title
			title This is default title
		block head
	body
		h2 #{a}
		block content
```

```jade
//- index.jade
- var config = "Hello from variable before extends"

extends simplePageTemplate

block content
	p #{config}
	#{config}
```

The output `index.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <title>This is default title</title>
  </head>
  <body>
    <h2>Hello from variable</h2>
    <p></p>
    <undefined></undefined>
  </body>
</html>
```

Why the variable couldn't be used inside a file have extends keyword?
How to solve that problem, any solution?
Sorry for my bad English!

**Comment by ForbesLindesay** [comment]
You need to put the variable declaration inside a block:

```jade
//- simplePageTemplate.jade
- var a = "Hello from variable"
block config
doctype
html
    head
        block title
            title This is default title
        block head
    body
        h2 #{a}
        block content
```

```jade
//- index.jade
extends simplePageTemplate

block config
  - var config = "Hello from variable before extends"
block content
    p #{config}
    #{config}
```

This will give you a proper error message in v2.0.0

**Comment by terrycloth** [comment]
Judging by the number of similar issues, this is a fairly common point of confusion. It's how *I* found my way to this issue. When a page extends a template, and variables set in the page need to be usable in the template, put the variables in a block... Now that I've read about it, it makes sense, but I don't think I would ever have guessed to try this.

@ForbesLindesay, I feel like your solution here should be added to the documentation.
