### ISSUE TITLE
Whitespace in textarea

### ISSUE THREAD

**Issue by shrenikp** [jadejs/jade#1931]
[This commit](https://github.com/jadejs/jade/commit/0a78e7ff81253b9b2bd8b2f699ceb98d07882aeb) doesn't seem to be merged. Still having the whitespace issue in `textarea` as per #500

**Comment by ivanjuras** [comment]
+1, doesn't seem to be working for me either.

**Comment by ForbesLindesay** [comment]
Pull request welcome.

**Comment by TimothyGu** [comment]
#1935

**Comment by groenroos** [comment]
+1. @ForbesLindesay

**Comment by ForbesLindesay** [comment]
`'textarea'` should be marked as whitespace sensitive in the same way that `'pre'` is in https://github.com/jadejs/jade-code-gen/blob/master/index.js
