### ISSUE TITLE
Make Jade use my own file reader to load layouts?

### ISSUE THREAD

**Issue by callumlocke** [jadejs/jade#1933]
I want to use `jade.compile('string of jade', options);` but I want to provide my own "readFile" function which Jade should use instead of `fs.readFile` when it encounters an `extends`. This way, I could use Jade as part of an in-memory pipeline of preprocessing phases.

Is there a way to do this? If not, would you accept a PR that adds this as a new option?

**Comment by ForbesLindesay** [comment]
If you look at the code in master.  It should be fairly easy to fork this module and replace `jade-load` with your own custom implementation.  Supporting that process was part of the goal of 2.0.0

**Comment by callumlocke** [comment]
I don't think it's possible the way you described. The jade-load module's `read()` method doesn't actually get used because it gets [overridden by jade](https://github.com/pugjs/jade/blob/e7c7052112aaa8ef9b0146520fa273b3f032cddc/lib/index.js#L76-L81).

I would like to make my own fork but it's not obvious to me what to do. If supporting this was part of the goal of v2, can you reopen this issue?
