### ISSUE TITLE
Unbuffered comments can break indented blocks...

### ISSUE THREAD

**Issue by flynx** [jadejs/jade#1944]
**Here is a simple example:**

```jade
if 123
  div some text...
//- comment documenting the else branch...
else
  span some other text...
```

**Result:** this code breaks with the following error pointing to the else keyword:
```
Unexpected else without if
```

**Expected behavior:** unbuffered comments should not affect block handling...

**A bit of motivation:** unbuffered comments are mostly used to document the actual template and are neither needed nor rendered in the HTML, thus should behave as traditional comments (no-op elements) and be simply ignored and dropped by the lexer/translator.

*BTW, this is not an issue for normal "comments" as they translate to HTML comments and their indent is significant and indicates their position in the resulting tree.*

Thanks!

**Comment by Hubro** [comment]
I came to report this. Commenting on code blocks like this is something I do almost every day, so this bug is very disruptive.
