### ISSUE TITLE
Documentation unclear on available filters

### ISSUE THREAD

**Issue by tomxtobin** [jadejs/jade#1945]
The documentation is unclear on what filters you can use. Maybe we can link to the [transformers package](https://github.com/ForbesLindesay/transformers), or include the list from there?

**Comment by albertorestifo** [comment]
:+1:  Also, adding a couple of lines explaining how to add your owns

**Comment by TimothyGu** [comment]
For the record, we are now using JSTransformers rather than transformers for filters.

**Comment by TimothyGu** [comment]
This has been fixed in 0e432d676c2cfabcce1f407339fb0e63bdb57287/#1996.
