### ISSUE TITLE
How to create a config file for jade?

### ISSUE THREAD

**Issue by pinggod** [jadejs/jade#1948]
Now, I have two files, as follows:

```jade
//- demo.jade
include _opt.jade

doctype html
html 
    head
        title= opt.title
    body 
        h1= opt.h
```

and another file : 

```jade
//- _opt.jade
- var title = "hello";
- var h = "world";

- var opt = {title: title, h: h};
```

As you can see, the `_opt.jade` is to config the `demo.jade`，but the format of  `_opt.jade` is too verbose, Could anyone have good idea to improve it?

I particularly like the format of JSON, and i want to write this file just like: 

```jade
- var opt = {
    title: "hello",
    h: "world"
}
```

Of course, this format can't be parsed in jade now. Do you have good idea? 

Looking forward any reply!

**Comment by TimothyGu** [comment]
See also #796. I haven't tried, but I think `require`ing a JSON file should work. But the easiest way is to just pass in the configuration as locals.

**Comment by pinggod** [comment]
@TimothyGu  Thanks.
