### ISSUE TITLE
Dynamic Include

### ISSUE THREAD

**Issue by adius** [jadejs/jade#1955]
It should be possible to pass the include string in a variable.

http://stackoverflow.com/questions/12132978/use-a-variable-in-a-jade-include

**Comment by TimothyGu** [comment]
No.

See:

- #416
- #569 
- #839
- #843 
- #1312
- #1433 
- #1481 
- #1893
- #1924
- #1938 

A few of them are related to dynamic extends, which are of the same nature as dynamic includes.

**Comment by adius** [comment]
Sorry for bringing this up again. I'm too stupid to search. Had accidentally filtered the results so that none of them showed up. Will check them out. Thanks
