### ISSUE TITLE
Meta: Release proposal 1.10.0

### ISSUE THREAD

**Issue by alubbe** [jadejs/jade#1956]
I would like to get a new release out soon, maybe by the end of the week. I've only just joined so please help me in completing the changelog ;)
My feeling is that we should bump the minor version due to jstransformers, the hierarchy flag and a a new default for express in production mode.

Proposed  changelog:
- Now supports jstransformers, which allows improved handling of embedded languages such as Coffee-Script @ForbesLindesay
- CLI: added a flag to keep directory hierarchy when a directory is specified @TimothyGu
- disabled 'compileDebug' flag by default when used with express in production mode @alubbe
- CLI: now use jade.compileFile internally @TimothyGu
- Fixed a memory leak on modern versions of Chrome as well as node 0.12 and iojs @alubbe

List of all relevant commits:
fd5566f updated tests to work with new version of v8
76c63b6 disable compileDebug for express' production env
23fe2df fixed memory leak caused by compileDebug flag
e7eb9f1 Remove duplicated lib-cov from gitignore
d1fc2f6 added new logo to the header and tweaked the link color to match
00e9029 Add support for jstransformers, deprecate Transformers
73e840e Update the README logo
b1a57e8 Cosmetics
89034ad CLI: use jade.compileFile*
10272b9 Factor out rendering function selection
8b3206f CLI: fix -H with watch mode
24628e1 CLI: More accurate --hierarchy handling
905d42d CLI: Add comments on complicated path handling
6603972 docs/stop: Remove file query hack
d6c0f71 Fixed invalid link in the doc
cac81d5 Grammar fixes.
dccfefb Test io.js instead of a specific minor version
764787f Add client-compilation example
a6fde72 Update to latest jQuery and Bootstrap versions
c766494 Remove git submodules
0c994c8 Fixed small typo
60065e3 Use an option --hierarchy to enable the new directory behavior
11059e8 Fix typos in docs/views/reference/interpolation.jade.
285882f Proper spelling for "cross-site scripting" with period
20dbc4a Proper spelling for "cross-site scripting" with period
aaab796 (docs) sanatize->sanitize
43b2863 docs/api: Escape double spaces
a6c9f77 mention jade2php in readme
4eab8a7 Travis: test with Node.js 0.12 io.js 1.1 instead of Node.js 0.11
ec2f578 Remove unused markdown dep
a2337ea Update marked

**Comment by ForbesLindesay** [comment]
Also:

 * deprecate Transformers support in filters (to be removed in 2.0.0)
 * update website @GarthDB

Other than that, it all looks great.  Go for it when you're ready :)

**Comment by TimothyGu** [comment]
@alubbe said:
> - CLI: added a flag to keep directory hierarchy when a directory is specified @TimothyGu

You might want to mention that this behavior will be the default in 2.0.0.

> - disabled 'compileDebug' flag by default when used with express in production mode @alubbe

Does this require a major bump?

> - CLI: now use jade.compileFile internally @TimothyGu

You can leave this out since we were pretty much using an inlined version of that function anyway.

Rest sounds good to me.

**Comment by GarthDB** [comment]
:shipit:

**Comment by ForbesLindesay** [comment]
> Does this require a major bump?

I don't think it should require a major version bump because it is only a change to our behaviour in an error-case, and even then it only changes the error message.

**Comment by ForbesLindesay** [comment]
Looks like this was released

**Comment by GarthDB** [comment]
Was there an issue with the website?

**Comment by alubbe** [comment]
Btw, how do we update http://jade-lang.com/? It does not seem to use gh-pages

**Comment by ForbesLindesay** [comment]
@GarthDB no, I will publish it when I get a chance if @alubbe  doesn't :)

@alubbe You have to run `node release.js` which will build it from the "docs" directory and then commit it to gh-pages automatically (providing you put a JSON stringified GitHub token in ".release.json").  This needs documenting somewhere/improving.  I plan on moving the docs to a separate repo at some point as permissions can then be separate and it will be easier to combine docs for jade/react-jade/then-jade etc. into one website.

**Comment by alubbe** [comment]
just ran exactly that - I think it worked ;)
