### ISSUE TITLE
Converting a ejs page to jade

### ISSUE THREAD

**Issue by bghanem** [jadejs/jade#1957]
I've been trying to include this ejs page in my jade-based app and so far I haven't succeeded:

![screen shot 2015-05-18 at 11 45 11](https://cloud.githubusercontent.com/assets/12040292/7698556/1e1d02de-fe09-11e4-922d-4d9eb9272776.png)
And here's the rest of it (the part that doesn't appear in the first screenshot)
![screen shot 2015-05-18 at 11 45 44](https://cloud.githubusercontent.com/assets/12040292/7698566/2eee50ae-fe09-11e4-8ff4-dbf0dfb4b6da.png)
 Here's what I've done:

1. Inspect element, copy the html code of the ejs page and then convert it to jade using an online html to jade converter. Needless to say that the converted code didn't work.

2. I then tried to create a simple html link that onclick would take the user to that ejs page. That's not a very secure option.

3. Now, I'm trying to create the same page from scratch using jade. So if you don't think converting the ejs file to jade is possible, would anybody tell me where can I read about jade and be able to create the same page?

**Comment by ForbesLindesay** [comment]
Jade has a reference at: http://jade-lang.com/reference/ which details most of jade's features.  There shouldn't be any special security concerns with having an app that has both ejs and jade in it, so you could just have both.
