### ISSUE TITLE
Can I reference DOM element in if statement?

### ISSUE THREAD

**Issue by avalanche1** [jadejs/jade#1960]
Like this
```jade
if #element1 '(if #element1 exists)'
  p#element2
```

**Comment by ForbesLindesay** [comment]
No.  I'm afraid I'm not entirely sure what that would mean? At the point the if statement is reached, the page hasn't been rendered yet, so how would it determine whether `#element1` exists?

**Comment by avalanche1** [comment]
well, I need to render (or not) DOM node 'B' based on the value of node "A".
Is that possible with Jade?

**Comment by ForbesLindesay** [comment]
but when is node A rendered?  Is it rendered as part of the jade template?

**Comment by avalanche1** [comment]
Actually I'm using Meteor, so it's a meteor template.
Node A is rendered before node B.

**Comment by ForbesLindesay** [comment]
Where is it rendered to though?  If it's already in the actual dom you can just do `document.getElementById('element1')` like you normally would, but if it's just in the same DOM template then it hasn't really been rendered, it's just been added to a long string.  Why not just do something like:

```jade
- var shouldRenderX = true || false;
if shouldRenderX
  #element1

// some time later

if shouldRenderX
  p#element2
```

It will probably produce clearer code if you separate the "state" from the "DOM"/"HTML".  In general, the DOM/HTML is one of the worst places to store state as it gets really hard to reason about.

**Comment by avalanche1** [comment]
Well, Meteor encourages using state in DOM; e.g. the following is a ubiquitous practice inside html: `{{#if Meteor.user}}` - if true renders some html if user is logged in.
As for our topic - I think you making it more complicated than it is.
I have the following simple `index.jade` with no templates whatsoever:
```jade
input#elem1
'then I need the following:'
if #elem1.val()='A' then
    label#elem2 input=A
```
I know I can do this in my js file, but I was looking for a simpler solution.

**Comment by TimothyGu** [comment]
How is Jade supposed to know what `#elem1.val()` is? Jade is a server-side templating engine. It doesn't know any client-side information.

**Comment by ForbesLindesay** [comment]
@TimothyGu Remember that jade can also be rendered client side.

@avalanche1 The example of `{{#if Meteor.user}}` is explicitly not storing state in the HTML.  Instead it is storing the state in a separate "Meteor" object.  In this case I would suggest doing something like this:

```js
var value = 'Initial Value';
function render() {
  document.body.innerHTML = myTemplate({value: value});
}
render();
document.getElementById('elem1').addEventListener('change', function () {
  // update state stored in a JavaScript "model"
  value = document.getElementById('elem1').value;
  // re-render to pick up any updates
  render();
}, false);
```

```jade
input#elem1(value=value)
if value === 'A'
    label#elem2 input=A
```

**Comment by avalanche1** [comment]
@ForbesLindesay ok, I've got your solution. thank you for it)
