### ISSUE TITLE
Using Jade to build JavaScript (or something else)

### ISSUE THREAD

**Issue by wamoyo** [jadejs/jade#1962]
Hi,

So, my goal here is to use Jade to compress and minify JavaScript on the fly. Stylus does this beautifully with CSS. I edit my .styl files, rich with comments, and spaced out nicely, but they all compress nicely into a single CSS file before they run. Jade does the same thing for HTML.

Ideally, I'd like to be able to interrupt jade, and tell it to concat and uglify the javascript files referenced in a jade template. It should probably concat any files listed adjacent to one another. JS at the top stays at the top, JS at the bottom stays at the bottom.

If this is totally outside the scope, my dearest apologies. Feel free to close the issue. I thought it was a natural place to achieve performance without damaging the development experience.

**Comment by TimothyGu** [comment]
By JavaScript, do you mean inline script or script referenced with `<script src>`? If it is inline, you can use the uglify-js filter. If it is in a separate tag, you can probably override the compiler, but that is kind of complicated so you probably shouldn't do that until Jade 2.0.0, which makes it a lot easier to do so.

**Comment by wamoyo** [comment]
I was thinking script references. Got it. Guess I can edit the HTML string in some custom middleware.

**Comment by TimothyGu** [comment]
Jade 2.0.0 will support things like [this](https://github.com/jadejs/jade-walk) to make walking the AST and figuring out all the script tags easy. But of course you can always parse the HTML.

**Comment by wamoyo** [comment]
Thanks, @TimothyGu!
