### ISSUE TITLE
Allow new lines in the attributes text

### ISSUE THREAD

**Issue by drulia** [jadejs/jade#1969]
Currently all text inside attribute has to be written in a single line and this reduces readability quite greatly when you have a long attributes. It is especially painful when you use libraries like knockout, that tend to utilize single `data` attribute to receive all values.

It would be really great if we could split something like this:

```a.link(data-bind="text: $data.text, click: $parent.actionOnClick, css: {visible: $data.isElementVisible}, attr: {href: $data.displayUrl}")```

into much more readable:

```
a.link(data-bind="
    text:  $data.text,
    click: $parent.actionOnClick,
    css: {
        visible: $data.isElementVisible },
    attr: {
        href: $data.displayUrl }")
```

Thanks

P.S.
I know that you can use `\` just before new line, and it helps, but it is a source for bugs as well.

**Comment by TimothyGu** [comment]
Does ES6 template strings not work?

```jade
a.link(data-bind=`
    text:  $data.text,
    click: $parent.actionOnClick,
    css: {
        visible: $data.isElementVisible },
    attr: {
        href: $data.displayUrl }`)
```
