### ISSUE TITLE
How do I assign mixin(block)  to a Javascript variable

### ISSUE THREAD

**Issue by evmek** [jadejs/jade#1980]
Hi ,
I want to read the values ​​in the mixin block on JavaScript,

My sample ,
```
mixin iButton(value)
   - var v =  value || attributes.value || block;
   - attributes.value = v;
   input(type="button")&attributes(attributes)

+iButton("Send")                                       is OK
+iButton(value="Send")                            is OK
+iButton Send                                           is Error
```

Do you have any idea about this ?

**Comment by TimothyGu** [comment]
You can't achieve that in the current Jade architecture. Plus, for now all access to the `block` variable are considered unsupported. In Jade 2.0.0 you might be able to do the following:

```jade
mixin iButton
  | var v = block && block() || ""
  input(type="button" value=v)&attributes(attributes)

+iButton Send
```

but I would really recommend just using the `value` attribute.

**Comment by ForbesLindesay** [comment]
Also, why not:

```jade
mixin iButton(value)
   input(type="button" value=v)

+iButton("Send")                                       is OK
+iButton(value="Send")                            is OK
+iButton Send                                           is Error
```

`&attributes` is a sledgehammer, don't use it when you just need to hammer in a nail.  It's not escaped, so you have to be very careful when using it.
