### ISSUE TITLE
Cannot install. Errorno -13

### ISSUE THREAD

**Issue by ARSENALDev** [jadejs/jade#1984]
Trying to install Jade on my Macbook Pro and cannot seem to get it to work. I have tried multiple different commands and none them seem to work. I am extremely new to Terminal so please bare with me!

Heres what I get:

Chads-MacBook-Pro:~ CTrujillo$ npm install jade -g
npm ERR! tar.unpack untar error /Users/ARSENAL/.npm/jade/1.10.0/package.tgz
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "jade" "-g"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path /usr/local/lib/node_modules/jade
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/jade'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/jade']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/jade',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/jade',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ARSENAL/npm-debug.log

**Comment by jbnicolai** [comment]
This is not an issue related to jade. You're trying to install a package globally (`npm install -g`) but seem not to have the sufficient rights to do so. Either perform this as a user that has these rights (root, using e.g. sudo) or change the target path.

See https://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo for more information.
