### ISSUE TITLE
last <2.0.0 release

### ISSUE THREAD

**Issue by alubbe** [jadejs/jade#1988]
Right now, we have block code, more accurate error and a lot of performance improvements in the pipeline. 

I'd like to start a discussion here about what we want in that last <2.0.0 release.
Personally, I'd like a decision on https://github.com/jadejs/jade/pull/1977, release 1.11.0 and then focus on 2.0.0. Thoughts?

**Comment by ForbesLindesay** [comment]
#1977 is a breaking change.  It must wait until 2.0.0 is released.

**Comment by alubbe** [comment]
Agreed. With that decision of wanting it but not for 1.x, is there anything else we should wait for or are we good to release a 1.11.0?

**Comment by ForbesLindesay** [comment]
I think we're good to go
