### ISSUE TITLE
Add string Interpolation in var definitions 

### ISSUE THREAD

**Issue by kryptt** [jadejs/jade#1991]
I would expected 
```jade
- var x = "test#{param}" 
```
to work

**Comment by ForbesLindesay** [comment]
I think we should consider deprecating support for interpolation in attributes, that should make it clearer that interpolation is just for long blocks of text.  String concatenation works just fine in JavaScript.

**Comment by kryptt** [comment]
Hmm, I see where you are coming from... 

the trend is to _add_ interpolation, not remove/deprecate it. It is a useful feature after all...

My guess is that `-` gets delegated straight to javascript and there is no clear way to do interpolation properly across contexts.. 

How about, altering the interpolation to ES6 quasilteral style ?
and ensuring jade goes through an ES6 pipeline? 
(http://wiki.ecmascript.org/doku.php?id=harmony:quasis)

**Comment by izatop** [comment]
It's will be nice if you would added ES6 string templates to Jade.

**Comment by ForbesLindesay** [comment]
ES6 templates will probably be implemented as part of jade@2.0.0, and should already work if you use the latest versions of iojs

**Comment by izatop** [comment]
Well don! It's working wih iojs. Thank you!

**Comment by llafuente** [comment]
I may have another issue related.

I want to "re-interpolate" a string that came from my app (`label` and `error`)

```jade
- label = 'foo'
- error = '#{foo} is too short'

span= label
span!= label

span= error
span!= error
span
  #{ error }

```

In any case i cant find the way yo have my desired output
```html
<span>foo is too short</span>
```

Is this possible ?

**Comment by ForbesLindesay** [comment]
we don't do interpolation in JavaScript, only in attributes (recommended against) and blocks of text.

I'm not sure what you're actually trying to achieve.  You can produce:

```html
<span>foo is too short</span>
```

by simply writing:

```jade
span foo is too short
```

or if you already have `label` declared and want to use the value of `label` you can do:

```jade
span= label + ' is too short'
```

or

```jade
span #{label} is too short
```

**Comment by llafuente** [comment]
My usage is mostly multi-language.

I have a PO file that contains my string with the replaces.

Something like:
> "#{data.label} is too short, at least #{data.constraints.minlength} characters"

At the end I want
> Name is too short, at least 5 character

what I need is an extra interpolation.

**Comment by ForbesLindesay** [comment]
That would require an extra level of interpolation at runtime.  This would be hugely costly.  You should use a separate step to convert your strings into functions and then just call those functions from your jade.

**Comment by phaux** [comment]
Wouldn't it make sense to allow

```jade
-
  :coffee
    # coffee script goes here
    x = 42
    s = "the number is #{x}"

span= s
```

Or a dedicated operator alternative to `-` and `=` just for coffee script. Like this

```jade
//- buffered CoffeeScript block
span== arr.map(x -> x+1).join " #{s} "
//- unbuffered block
-- x = foo ? bar ? 0
//- as property value
span(class=="some-class #{status ? 'disabled'} other-class")
```
