### ISSUE TITLE
Include :verbatim and other available filters in docs

### ISSUE THREAD

**Issue by markpalfreeman** [jadejs/jade#1994]
I spent 20-30min searching online for how to display code while maintaining white space, nesting, and tabs before finding the `:verbatim` filter in a Github comment.

I think the Jade docs should contain a more thorough list of available filters, such as `:verbatim`.

I can send a PR given some direction.

**Comment by ForbesLindesay** [comment]
We are now using the jstransformers project, so we should provide a link to https://github.com/jstransformers for now, and update this to link to the jstransformers website once that's finished.

You should be able to do just fine with:

```js
pre
  code.
    // my code for display goes here
```

You shouldn't need verbatim.

Note that you will want something like the `escape-html` filter if you wish to display code that includes `<` and `>` characters

**Comment by markpalfreeman** [comment]
Ah! JS Transformers... that's super helpful to know.
I'll add a line for that so people can know the options available.

**Comment by TimothyGu** [comment]
Dup of #1945.
