### ISSUE TITLE
what do periods mean aside from class declaration?

### ISSUE THREAD

**Issue by Huanzhang89** [jadejs/jade#2000]
In the introduction to Jade theres some code that says 
```jade
p.
        Jade is a terse and simple templating language with a
        strong focus on performance and powerful features.
```

what is the difference of using p and p. ?

**Comment by TimothyGu** [comment]
`p.` means that the following **block** is treated as plain text instead of a tag hierarchy. It is explained in http://jade-lang.com/reference/plain-text/, under "Block in a Tag."

Examples:

```jade
p ABC
DEF
```

```html
<p>ABC</p><DEF></DEF>
```

-----

```jade
p
  ABC
  DEF
```

```html
<p><ABC></ABC><DEF></DEF></p>
```

-----

```jade
p.
  ABC
  DEF
```

```html
<p>ABC
DEF</p>
```

**Comment by Huanzhang89** [comment]
Thank for clarifying that :+1:
