### ISSUE TITLE
comment will render as inline will break some grunt tasks.

### ISSUE THREAD

**Issue by redyyu** [jadejs/jade#2002]
'//' comment on 'img' will render comment as inline, after run some grunt task might eat everything in side the inline comment.

etc, the comment output like   <img ....> <! ---end xxxxxxx -->   the img will eat by some grunt task for minify.

there is one word against another. You might say thats the grunt task problem. 
but I think it's a Jade should never render comment with inline at all.
What's inline comment for good? I don't understand...

**Comment by ForbesLindesay** [comment]
Give us an example of some jade, the html it currently renders, and the html you think it should render.

**Comment by ForbesLindesay** [comment]
This is probably an issue with a grunt task and not related to jade.

**Comment by redyyu** [comment]
```jade

// comment
img(
src="...."
alt="xxx"
)
// end comment

```

will render as 
  <img src="..." alt="xxx"><! -- end comment -->

```jade

// comment
div xxxxxx
// end comment

```

will render as 
 
<div> xxxxxx </div>
<! -- end comment -->

Are you sure the problem is cause by grunt task not related to jade.
the grunt task is run jade parse rendered as this format.
