### ISSUE TITLE
Custom components in Jade

### ISSUE THREAD

**Issue by divamgupta** [jadejs/jade#2004]
I was wondering if Jade allows us to create custom components. I'm not talking about mixins.

e.g 

```jade
comment
    h1 Hello world
    h2 hey
```

should convert to:

```jade
.someDiv
   .someOtherDiv
        p some other default text
         h1 Hello world
         h2 hey
```

So here we have created a custom element named comment that would compile to the source elements of that element.

**Comment by TimothyGu** [comment]
No. Unfortunately currently mixins and includes are the only ways to go.

**Comment by divamgupta** [comment]
Has some fork added this feature as it would be really productive.

**Comment by TimothyGu** [comment]
In jade@2 it would be a lot easier to override the code generator, thus making it very easy to support custom components.

**Comment by jeromew** [comment]
Maybe I misunderstand, but are you aware of mixin blocks ?

    mixin comment()
      .someDiv
        .someOtherDiv
          p some other defaut text
            block

    +comment()
      h1 Hello world
      h2 hey

**Comment by TimothyGu** [comment]
Wait… my email client messed up the indentation. See @jeromew's comment.
