### ISSUE TITLE
Render partial HTML using jade

### ISSUE THREAD

**Issue by divamgupta** [jadejs/jade#2005]
I have this file

```jade
div Hello
```

I get the output on rendering
```html
<html> <div> Hello </div> </html>
```

But I only want 
```html
<div> hello </div>
``` 
as the output.

How can I achieve this?

I also want to know how to compile the jade for browser so that I only get the tags specified in the jade file not <html> tags

**Comment by jeromew** [comment]
Are you sure that jade adds the `html` tag ? Tyring on http://jade-lang.com/demo/ does not show create the html tag.

maybe you are looking in the developer console of a brower (in which case, the browser might have added the html tag, not jade)

**Comment by divamgupta** [comment]
In express.js, using res.render() it does.

**Comment by jeromew** [comment]
i can't help you more on this without seeing the code. I doubt jade is adding this and would be surprised.
Are you using a recent version of jade ?

**Comment by TimothyGu** [comment]
Question timed out. Closing.
