### ISSUE TITLE
extend bug?

### ISSUE THREAD

**Issue by zhoukekestar** [jadejs/jade#2007]
```
if (ajax)
  +content
else
  extend ../common/layout.jade
  block content
    +content
```
----------------------------------------------
It always return "content + layout"

**Comment by TimothyGu** [comment]
`extend` and `include` are always static – that is, you cannot use them anywhere except at the root level. In this case however, the extend should probably report an error.

**Comment by zhoukekestar** [comment]
No error reported. If i use ```include```, no block can be used - that is, i have to code like this:
```
include head
my content
include foot 
```
What a pity..

**Comment by ForbesLindesay** [comment]
It will report an error in v2.0.0 of jade.
