### ISSUE TITLE
named parameters

### ISSUE THREAD

**Issue by askucher** [jadejs/jade#2008]
It is good to have possibility to pass named parameters as follow

```Jade

mixin input(type, required, min, max)
   input(type=type min-length=min ...)

+input(type="textbox")

```

it means developer will be able to easy transform native html element into angular material or something else without changing a lot of code and keeping native html as standard of templating

**Comment by siman** [comment]
:+1:

**Comment by tkachenko1503** [comment]
you can do
`mixin input(type, required)
   input(type=attributes.type)

+input(type="textbox")`

**Comment by askucher** [comment]
Cool!
