### ISSUE TITLE
jade + sass in one file

### ISSUE THREAD

**Issue by askucher** [jadejs/jade#2010]
Hi.

Please consider idea to combine jade and sass in one file with possibility to compile as html and as css

```Jade
.app
  max-width: 20px
  position: relative
  .navbar
    position: absolute
```

And it would be good if to add sublime editor possibility to hide lines with sass and layout

**Comment by alubbe** [comment]
In general, you can use filters to achieve this http://jade-lang.com/reference/filters
I don't think the sass support is entirely up-to-date (however, support for scss and stylus are).
If you npm install jstransformer-sass, you can use old sass syntax to write code like this:
```jade
h1 some html

style
  :sass
    .app
      :max-width 20px
      :position relative
      .navbar
        :position absolute
```
