### ISSUE TITLE
link or script bug

### ISSUE THREAD

**Issue by kfstudio** [jadejs/jade#2016]
Hi,

When i pass a list of link to the jade template to list my specific css or js, i see the html rendering with correct syntax, but there is an output error in console (see file attached).
If i modify the name (href for link or src for script), i have no error in console.

Is there any issue for this bug or maybe i do something wrong ?

![bug-jade](https://cloud.githubusercontent.com/assets/6827481/8612066/dc52911c-26ca-11e5-98e9-aa27cbac21f7.png)

**Comment by ForbesLindesay** [comment]
Some additional request is causing the jade template to be rendered a second time.  In the second render `headlink` is set to `undefined`.  This could be caused by the fact that browsers automatically request `/favicon.ico` or it could be one of your script/link tags is actually resulting in the jade being rendered instead of loading a script/style

**Comment by kfstudio** [comment]
I don't think so, because if i change the name of 'href' in 'ref' or anything else for exemple, it work fine without error.
For that i think there is something with href/src.

**Comment by ForbesLindesay** [comment]
Changing href or src will stop the browser requesting those urls, so one of those must be rendering your template

**Comment by jadaradix** [comment]
+1 to it being <code>favicon.ico</code>. You could test that the <code>/</code> request always works by using wget or curl on the command line. Or better yet, <code>console.log(req);</code> to confirm it's not hitting <code>/</code> when you get the error. We can't see the rest of your code, but I presume there's another route or a wildcard (<code>*</code>) route for handling a 404 (I usually do it that way), and in one of these <code>headlink</code> is empty. Feel free to Pastebin your code, else I am very sure this is not a jade issue, and the issue should be closed.
