### ISSUE TITLE
NPM INSTALL JADE, "Foo Bar" dir name with space error

### ISSUE THREAD

**Issue by brusci** [jadejs/jade#2017]
package.JSON doesn't work with directory name spaces:
    "name": "Foo Bar" in package.JSON
    npm ERR! Invalid name: "Foo Bar"

**Comment by rlidwka** [comment]
Yes, npm doesn't work with spaces in package names. So don't put spaces in there.

If you want to ask why, here is an npm issue tracker: https://github.com/npm/npm/issues

This issue has nothing to do with jade. _\*closing\*_
