### ISSUE TITLE
Updating value of textarea from expressJS issue

### ISSUE THREAD

**Issue by awaemmanuel** [jadejs/jade#2018]
Hello team, 

Please advise how I can dynamically update the value of a textarea from my ExpressJS app. I can do it easily for text fields using value variable, from app.js, but not the text area.

And since I don't have acces to the DOM object, I cannot use document.getElementById("myTextArea").value = "Some text here returned dynamically";

Please advise.

**Comment by alubbe** [comment]
It's related to how HTML works. textarea does not use text found in ```value```, instead it uses the text found in its body. So the equivalent of 
```jade
input(value=someVariable)
```
is
```jade
textarea=someVariable
```

**Comment by awaemmanuel** [comment]
Hello Alubbe,

Thanks for your response.

So in my someTemplate.jade, can I do something like you've advised above like

textarea=someVariable( rows="5" name="someTextArea") ?

**Comment by alubbe** [comment]
Yes, almost. You'll want to first specify the attributes before you specify the body. You can use either
```jade
textarea(rows="5" name="someTextArea")=someVariable
```
or
```jade
textarea(rows="5" name="someTextArea") some pre-filled content
```
or  even
```jade
textarea(rows="5" name="someTextArea") Say hello to #{someVariable}
```

**Comment by awaemmanuel** [comment]
Worked like a charm alubbe.

Thanks and thanks again.

**Comment by awaemmanuel** [comment]
Please feel free to close.

**Comment by tawkin** [comment]
thank you

**Comment by meljoum** [comment]
thanks bro

**Comment by princemokut** [comment]
Thanks so much for this info.
I had to be using DOM to handle this and it really made my code bulky. Thank again.
