### ISSUE TITLE
Include partial template but object variables found undefined

### ISSUE THREAD

**Issue by Alfred-Lu** [jadejs/jade#2019]
Node 0.10.x, expressjs 4.13.1 using Jade 1.11.0.

In route js, try to pass an object variable to the template, and display this variable in a partial included jade template

route js
```javascript
var foo = [
{'a': 1, 'b': {'x': 1}},
{'m': 2, 'n': {'y': 2}}
];
res.render('home', {bar: foo});
```
home.jade
```
- var vals = bar;
include partial.jade
each val in vals
  p= val.a // should be 1, and display 1
  p= val.b.x // should be 1, and display 1
```
partial.jade
```
each val in vals
  p= val.a // should be 1, and display 1
  p= val.b.x // should be 1, but shows error for unknown property 'x' of undefined
  p= val.b // should be an object, and display {'x': 1} like a string
```
In home.jade, all attributes of the object shows correct as they should be.
But for the included jade template, it can only display the first level of an object, the second level of the object causes undefined error.

**Comment by Alfred-Lu** [comment]
Sorry, the code I provided seems not work as it says. In my actual project, situation is more complicated. But I tested the variable 'vals' in home.jade and same code in partial.jade, home.jade is good, but partial.jade runs error: 'Cannot read property 'x' of undefined'

**Comment by ForbesLindesay** [comment]
Can you provide an actual example that demonstrates the error?
