### ISSUE TITLE
There is a jade.compileWithDependenciesTracked() method?

### ISSUE THREAD

**Issue by pateketrueke** [jadejs/jade#2020]
This is my actual _solution_:

```js
var view = jade.compileClientWithDependenciesTracked(source, options);

var params = {
  render: jade.compile(source, options),
  deps: view.dependencies
};
```

I really need save those references and later call `render()` to finally join all the things.

Doing this is very nasty I'm sure.

What can I do?

**Comment by timmfin** [comment]
You don't need it. The `jade.compile(...)` returns a function _with_ a `dependencies` property. So:

```js
var out = jade.compile(source, options);
var params = {
  render: out,
  deps: out.dependencies
};
```

Look at [the tests](https://github.com/jadejs/jade/blob/7f3c4b18bdd0c08ae678cc61b939f58bcee63494/test/jade.test.js#L1152-L1186) to see more examples.
