### ISSUE TITLE
Apostrophe breaks inline #[a(href="") links]

### ISSUE THREAD

**Issue by ebsen** [jadejs/jade#2021]
I don't know what these are called where you inline an HTML tag with the `#[]` syntax but if you have a single-quote (`'`) between the `[` and `]` marks, you'll generate the error

> The end of the string was reached with no closing bracket found.

even if the line includes one.

Here's a [quick pen to demonstrate](http://codepen.io/eriklebsen/pen/rVrYXm). I get the same issue locally.

**Comment by TimothyGu** [comment]
This is a duplicate of the first part of #1723

**Comment by TimothyGu** [comment]
A workaround:

```jade
p This #[a(href="http://jade-lang.com/") inline hyperlink works].
p This #[a(href="http://jade-lang.com/")= "one's broke"].
```

**Comment by ebsen** [comment]
Oh! Didn't know about the that. Thanks.

Sorry for the duplicate. Totally missed #1723.
