### ISSUE TITLE
Jade should not bail after the first error 

### ISSUE THREAD

**Issue by robbyoconnor** [jadejs/jade#2025]
If I have a file with 10 errors, jade should collect and report all 10 errors -- as of current -- it just bails and reports **ONLY** the first error

**Comment by ForbesLindesay** [comment]
Jade's compiler is statefull.  What this means is that when it has encountered an error, it has no reliable way to continue parsing the file in order to look for other errors.  If we did attempt to do this, you would see hundreds of meaningless errors for each real error.

**Comment by robbyoconnor** [comment]
Okay :crying_cat_face:
