### ISSUE TITLE
How can I set pretty without polluting app.locals?

### ISSUE THREAD

**Issue by waynebloss** [jadejs/jade#2026]
It seems like the official way to set the `pretty` option is to put it in app.locals. However, that means I can never have my own variable called `pretty`, which gets exposed to my views.

Is there another way to set this option without polluting app.locals?

**Comment by TimothyGu** [comment]
If you are using Jade directly, you can do:

```js
var options = { pretty: true }
var locals = {}
jade.compile(str, options)(locals)
```

instead of

```js
var locals = { pretty: true }
jade.render(str, locals)
```

If you are using Express 4, there is no way to achieve that.

**Comment by waynebloss** [comment]
Thanks @TimothyGu. I am using jade directly in this case, so that will work for me.

I'm a little embarrassed that didn't occur to me sooner, but I had just gotten done working another view engine that had a problem rendering strings that used `extends` with relative paths because it didn't have a nice `filename` option like jade has.
