### ISSUE TITLE
Update attributes documentation? - commas and attributes

### ISSUE THREAD

**Issue by nathanhleung** [jadejs/jade#2029]
Are commas between attributes needed?  (Like this: `link(href='styles.css', rel='stylesheet')`)  According to #662, support for attributes without commas was added, but according to the documentation [here](http://jade-lang.com/reference/attributes/) commas with attributes are still needed.  If some clarification could be provided that would be great!

Thanks.

**Comment by ForbesLindesay** [comment]
The commas are now optional.  We should update the docs to reflect that

**Comment by 18nleung** [comment]
Ok, thanks for the response!  Should I close this issue or do you want it to be kept open until the docs or updated?

**Comment by ForbesLindesay** [comment]
Keep it open.  Thanks
