### ISSUE TITLE
Conditional classList Syntax

### ISSUE THREAD

**Issue by thr0w** [jadejs/jade#2033]
There is a better mode to write conditional classes?

Example: I always want decotador class but sometimes I wanna checked class and once selected class on some items.

```jade
-
  var items = [
    { text: 'One',   checked: true  }
  , { text: 'Two',   checked: false }
  , { text: 'Three', checked: true  }
  ]
- var selectedItem = items[0];

ul
  each item in items
    div(class=[ 'decotador',selectedItem==item?"selected":"",item.checked?"checked":"" ])
      span= item.text
```

Maybe something like that

```jade
-
  var items = [
    { text: 'One',   checked: true  }
  , { text: 'Two',   checked: false }
  , { text: 'Three', checked: true  }
  ]
- var selectedItem = items[0];

ul
  each item in items
    .[decotador,selectedItem==item?"selected",item.checked?"checked"]
      span= item.text
```

**Comment by jinchizhong** [comment]
Hi friend,

This may help:

    mixin xxx(active, checked)
      div(class=[active?'active':null,checked?'checked':null])&attributes(attributes)
        block
    
    + xxx(true, true).decotator para1
    + xxx(true, false).decotator para2
    + xxx(false, true).decotator para3
    + xxx(false, false).decotator para4

result:

    <div class="active checked decotator">para1
    </div>
    <div class="active decotator">para2
    </div>
    <div class="checked decotator">para3
    </div>
    <div class="decotator">para4
    </div>

**Comment by TimothyGu** [comment]
There is indeed a better way: using an object rather than an array for classes

```jade
-
  var items = [
    { text: 'One',   checked: true  }
  , { text: 'Two',   checked: false }
  , { text: 'Three', checked: true  }
  ]
- var selectedItem = items[0];

ul
  each item in items
    .decotador(class={
      selected: selectedItem === item,
      checked: item.checked
    })
      span= item.text
```

**Comment by thr0w** [comment]
Thank you @TimothyGu , thats great!!!
