### ISSUE TITLE
support i18n directly in jade

### ISSUE THREAD

**Issue by jinchizhong** [jadejs/jade#2036]
Hi everyone,

Support i18n is painful in background,  and it not good for SEO in frontground.
Can we let jade support i18n directly?

    h1 Hello world
    p What a good day!
    p Today is my #{age} birthday.
    p There are #{n} apple(s).

=> 

    @h1 Hello world
    @p What a good day!
    @p Today is my #{age} birthday.
    @(n)p There are #{n} apple(s).

=>

    <h1><%= __('Hello world') %></h1>
    <p><%= __('What a good day!') %></p>
    <p><%= __('Today is my #{age} birthday.') %></p>
    <p><%= __('There are #{n} apple(s).', n) %></p>

If you are feeling this is good, I can write for this.

best regards

**Comment by TimothyGu** [comment]
You can override the Parser in order to support something like this.

**Comment by vai** [comment]
coupling template updates to localisation data updates isn't wunderbar usually?

**Comment by rlidwka** [comment]
Right now, you can define a helper for i18n and use it:

```jade
h1= t('Hello world')
p= t('What a good day!')
p= t('Today is my #{age} birthday.', age)
p= t('There are #{n} apple(s).', n)
```

Do you just want a syntax sugar for this, or are there some disadvantages for this approach I don't know about?

**Comment by vai** [comment]
agreed. i18n is very app specific.

**Comment by TimothyGu** [comment]
Closing since there is consensus to not support it.
