### ISSUE TITLE
Set this to the locals object when interpolating a function

### ISSUE THREAD

**Issue by taco-indenbosch** [jadejs/jade#2037]
A locals object passed to the function generated by Jade from a template can contain functions. These functions can be evaluated just fine, as long as they do not use 'this', as that is not set and is therefore the window object (in a browser, at least).

If we look at the following example:

	var obj={
		value: 123,

		getValue: function() {
			return this.value;
		}

	};

	console.log("Value", obj.getValue());

	var template="| #{getValue()}";
	var func=jade.compile(template, {});

	console.log("Expansion", func(obj));

The first logged value is 123, as expected. The second one is not, it is undefined.

It would be extremely useful if this were to work. In order for this to work (in the case above) the this of the call the getValue caused by #{getValue} should be obj passed to func generated by Jade.

**Comment by ForbesLindesay** [comment]
To do this, you should pass the object as a named local.  e.g.

```js
var obj={
    value: 123,

    getValue: function() {
        return this.value;
    }

};

var template="| #{obj.getValue()}";
var func=jade.compile(template, {});

console.log("Expansion", func({obj: obj}));
```

**Comment by taco-indenbosch** [comment]
Hi Forbes Lindesay,
  
 I am using this as a workaround. However, it is less than elegant. Is there a reason this could not be made to work without the named local?
  
 with kind regards,
 Taco.
  
  

----------------------------------------

**Comment by ForbesLindesay** [comment]
Yes.  It would require analysing the entire AST to find all function calls, then add runtime logic to figure out what value to use for this.  Added to which, it makes your code much clearer and easier to read if it's `objectName.getValue()` rather than `getValue()` with a magic implicit `this`
