### ISSUE TITLE
jade variable parse problem

### ISSUE THREAD

**Issue by hongqi** [jadejs/jade#2038]
i write in my router:
router.get('/detail', function(req, res, next) {
    res.render('fkdetail', {
        title: "fucktitle",
        fuck: "fuck"
    });
});

at template fkdetail:
#{title}

at html:
it being a tag: <fucktitle></fucktitle>
not the value: fucktitle

**Comment by hongqi** [comment]
the tag is:
![dd](https://cloud.githubusercontent.com/assets/3354923/9131103/48891b60-3d1b-11e5-88d6-542b5e8896d8.png)

**Comment by ForbesLindesay** [comment]
Try and keep your language civil if possible.

That syntax is tag interpolation.  Either use

`= title`

Which buffers the title or

`| #{title}`

Which marks the line as plain text, then interpolates within that plain text.

**Comment by hongqi** [comment]
thanks for you reply.
sorry about my uncivil language.
