### ISSUE TITLE
Jade Truck Factor

### ISSUE THREAD

**Issue by gavelino** [jadejs/jade#2040]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Jade** and obtained a value of **2**.

The developers responsible for this TF are:

TJ Holowaychuk - author of 56% of the files
Forbes Lindesay - author of 37% of the files

To validate our results, we would like to ask **Jade** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Jade**?

(b) Do you agree that **Jade** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Jade** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by TimothyGu** [comment]
Hi,

(a) **No.** TJ has been away from Jade for quite some time now. @ForbesLindesay is considered the main maintainer/developer of Jade.

(b) **No.** If Forbes left the project, we would surely lose our most experienced developer. But, I believe that the rest of @jadejs will be able to carry on the maintainership of Jade.

(c) **Yes.** Jade has excellent documentation for its syntaxes and APIs. Although the internals are not documented as well as they probably should be, the modularized approach of Jade makes it easy to pick up small pieces of Jade at a time, and it would be easy for new developers to find the thing they want to work on to fix a particular bug fairly quickly. Plus, again I think even without Forbes the rest of us are competent enough to at least keep Jade working and active.

**Comment by ForbesLindesay** [comment]
I agree with everything in @TimothyGu's assessment here.  Although being hit by a truck would be a great loss to me personally :smiley_cat:, and (I like to think) a great loss to the jade project, things would continue.

There is a fairly clear roadmap in #1834 of what I feel needs doing to get us ready for releasing 2.0.0.  These tasks are laid out clearly enough that many people could pick them up and get started.  We have a fairly open permissions model, which means that there are many people who can add/remove new contributors and publish new versions.  We also have a pretty comprehensive test suite, which makes experimentation fairly safe for new developers.  As @TimothyGu pointed out, the modularized code base allows you to learn in chunks.

I'm going to close this as it is not an open bug/feature request and your question has been answered.  Feel free to continue to comment though, and I'd be happy to hear from other contributors to see if they also feel there are enough people capable of taking over from me if I suddenly disappear.

**Comment by alubbe** [comment]
@gavelino Two things to note:
1) Maybe there is a better metric than using authorship of files. Assuming you are using git you could increase the granularity to what author last edited each line of code (using git blame) and aggregate that. I would assume your number for TJ would be greatly reduced.
2) What version did you base your calculation on? Just very recently jade was modularized into a bunch of sub-projects, so all files you find within this repo have been greatly reduced and only represent a small section of the whole codebase.

Irregardless of your method of calculation, the truck factor is probably two - being Forbes and Timothy. Having said that, there has been an onboarding of additional maintainers who, while they may not have as deep of an end-to-end understanding they usually understand one of the aforementioned modules very well. For example, I do not fully understand the lexer and parser, but have a very good understanding of the code-gen and runtime. So with this modularization, we are actively working on reducing the impact of losing Forbes and/or Timothy.

**Comment by gavelino** [comment]
@alubbe 
>What version did you base your calculation on?

We are using a version of the repository cloned on February 25th, 2015.

**Comment by alubbe** [comment]
I would recommend that you update your repo to https://github.com/jadejs/jade/commit/31966399f86b15159f2ff47dff99fbf4c92fadd5 and to use line authorship rather than file authorship. Would be interesting to see what numbers you get.
