### ISSUE TITLE
Allow use of js in extends

### ISSUE THREAD

**Issue by ferhtgoldaraz** [jadejs/jade#2044]
I attached a function in locals to resolve paths, intending to use it on extends. for example:

```jade
extends "#{module('showcase')}"
```

I think this would let the file and project structure be more separated from jade workings.
It would let people that have asked for multiple folders in extends and the like implement their own alterantives.

Is there a way to do this now?

I saw #1567, and it seems to be related. Doesn't look like a big change. Since some of the blocking ssues for 2.0.0 might take some time, maybe this could be considered for 1.x.x, as it doesn't seem to imply a breaking change, provided it happens to be of interest of course.

If the functionalilty to manipulate the parser is supposed to cover this kind of circumstances, how can I find out more about how to use (more like play with) it?

Thanks anyway

Also, maybe it's evident for some other unknown reason, but the basedir option is not listed as an option in the api documentation. It may be a good idea to add it.

**Comment by ForbesLindesay** [comment]
Search for "Dynamic Extends" in the issue tracker.  You will find that I have explained time and time again why it's really difficult to implement this performantly.
