### ISSUE TITLE
Attributes containing brackets

### ISSUE THREAD

**Issue by panicbit** [jadejs/jade#2050]
While playing with Angular 2 I noticed that attributes, when surrounded by brackets, invoke some weird parsing behaviour, e.g.:

```jade
input([foo]='foo' [bar]='bar')
```
results in

```html
<input [foo]="bar"/>
```

and

```jade
input([foo]='foo' (bar)='bar')
```

results in

```
Assigning to rvalue (4:40)
```

This problem can be worked around using the &attributes syntax, but it would be really nice if it would work without that.

**Comment by TimothyGu** [comment]
This is a difficult case to solve. For example:

```jade
input(foo='foo' [bar]='bar')
//- since `'foo' [bar]` is equivalent to `'foo'[bar]`
input(foo='foo'[bar]='bar')
//- which is equivalent to
input(foo=('foo'[bar]='bar'))
//- which is equivalent to
input(foo='bar')
```
?

A work around you can use is quoting the attribute names:

```jade
input('[foo]'='foo' '[bar]'='bar')
input('[foo]'='foo' '(bar)'='bar')
```

Since the bug is impossible to fix and a logical work around exists, I'm going to close this issue now.

**Comment by panicbit** [comment]
I don't quite understand the reasoning behind that equivalence but I think quoting attribute names is good enough. Thanks! :+1:

**Comment by ForbesLindesay** [comment]
Yes, or in your original example, jade thinks you want to call a string.  If you're using any special characters in key names you should always quote them.
