### ISSUE TITLE
Update main documentation for v2

### ISSUE THREAD

**Issue by TimothyGu** [jadejs/jade#2052]
These are the documentation-related things I really want to fix before releasing v2. Some of them are more important than others.

## Done

- [x] #1719
- [x] #1945
- [x] #2029 (9cc207fedd64326a3147d4d91b2c3ff98792c151)
- [x] #1447 (#2093)
- [x] document the additional options for `jade.compile`
- [x] update the installation procedure of `jade-cli`

**Comment by Laoujin** [comment]
`document the additional options for jade.compile`

The documentation talks about the following options: `debug, cache, compiler and parser` but I didn't find these in jade/lib/index.js. I did find: `basedir and inlineRuntimeFunctions` there.

**What exactly do you want to do?**

- **Present the parameters for each function separately?** (for example `compileClientWithDependenciesTracked` has a bit different parameters compared to `compile` so I guess the statement "options - All API methods take the following set of options:" is no longer valid?

- or **Update the parameters for compile only?**

**Comment by TimothyGu** [comment]
To answer your question:

> Present the parameters for each function separately?

^^ this. I'll probably say that "these options are available for xxxxx function only"

**Comment by TimothyGu** [comment]
The rest has been fixed in 131a0bc...8f918ff.
