### ISSUE TITLE
Double slashes in "inline tags" doesn't work

### ISSUE THREAD

**Issue by bratanon** [jadejs/jade#2053]
Lets say I want to link to google and I what the clickable text to be the full URL "https://www.google.com"

Then I would do this

```
p.
  Lorem ipsum dolor #[a(href="https://www.google.com") https://www.google.com] sit amet
  consectetur adipiscing elit.
  Proin condimentum, lacus eu convallis tincidunt.
```

But for some reason, the double slashes in the text (not href) breaks the jade parser.

"The end of the string was reached with no closing bracket found."

**Comment by TimothyGu** [comment]
This has been fixed in Jade master branch, and the fix will be published
with the upcoming jade@2.0.0. In the mean time you can use a work around
like `p #[a(href='...')= 'http://blah']`. There's also already an issue
filed for this somewhere but I can't find it right now…

**Comment by TimothyGu** [comment]
Ah here it is: https://github.com/jadejs/jade/issues/1723#issuecomment-123344407

Don't use the suggestion to `npm install jadejs/jade` though (not right now at least) since this repo's dependency status is currently a mess.
