### ISSUE TITLE
Vulnerability in child dependency

### ISSUE THREAD

**Issue by Stono** [jadejs/jade#2059]
Hi,
We have particularly stringent checking of packages and their child dependencies and our pipeline just broke because of this:

```
 jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5', patched in '2.4.24'
```

Because of https://nodesecurity.io/advisories/uglifyjs_incorrectly_handles_non-boolean_comparisons

**Comment by TimothyGu** [comment]
In the next version of jade we won't be using `transformers` anymore, so this bug is already fixed.

**Comment by Stono** [comment]
@TimothyGu do you have an ETA release date then?

**Comment by Stono** [comment]
For those who aren't willing to have vulnerable modules this shrinkwrap will force update the child dependency for you:

```
{
  "name": "your-project",
  "version": "1.0.0",
  "dependencies": {
    "jade": {
      "version": "1.11.0",
      "from": "jade@>=1.11.0 <1.12.0",
      "dependencies": {
        "transformers": {
          "version": "2.1.0",
          "from": "transformers@2.1.0",
          "dependencies": {
            "uglify-js": {
              "version": "2.4.24",
              "from": "uglify-js@>=2.2.5 <2.3.0"
            }
          }
        }
      }
    }
  }
}
```

**Comment by TimothyGu** [comment]
No, not yet, but I guess when https://github.com/jadejs/jade/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0 is empty 2.0.0 will be out :)

**Comment by OmgImAlexis** [comment]
Is there any ETA on this now? That link is now empty. 1.11.0 is the latest on npm at the moment.

Ref: https://github.com/mishoo/UglifyJS2/issues/751

**Comment by ForbesLindesay** [comment]
The updated link is now: https://github.com/jadejs/jade/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.0.0+-+Modules+and+Plugins%22

I had planned to release this weekend, but I'll be away so won't have time to clear up the remaining issues.  The ETA is therefore 7th November.

**Comment by piotrd** [comment]
Hi there,

Any update on releasing this, @ForbesLindesay?

**Comment by mitselek** [comment]
+1
