### ISSUE TITLE
Access and manipulate the 'DOM'

### ISSUE THREAD

**Issue by tenry92** [jadejs/jade#2060]
I would like to access and manipulate the 'DOM' before I actually render it.

For example, from javascript, I'd like to manipulate all links (selector 'a') extending href by the parameter '?debug' if in debugging mode.

**Comment by TimothyGu** [comment]
How are you using Jade? With Node.js or in the browser?

**Comment by tenry92** [comment]
I'm using it with node.js/io.js.

**Comment by TimothyGu** [comment]
Jade doesn't offer any facility for that. It's not possible either to manipulate DOM before you even have a rendered HTML.
