### ISSUE TITLE
how to make three posts in one row ? 

### ISSUE THREAD

**Issue by cloudzhong** [jadejs/jade#2061]
I am not sure if this is the right place to ask questions.

I tried several ways , it not works.
I want one .row div outside 3 div , when iterating posts.
but the code below only can get first dive in .row div....

    each post, index in posts
        if index%3 == 0 
            div(class="row")
                div(class="span4")
                    h2
                        a(href="/u/#{post.user}") #{post.user} 說
                    p
                        small= post.time
                    p= post.post
        else
            div(class="span4")
                h2
                    a(href="/u/#{post.user}") #{post.user} 說
                p
                    small= post.time
                p= post.post

and the code below , will only show 1/3 of the posts

    each post, index in posts
        if index%3 == 0 
            div(class="row")
                div(class="span4")
                    h2
                        a(href="/u/#{post.user}") #{post.user} 說
                    p
                        small= post.time
                    p= post.post

**Comment by TimothyGu** [comment]
Jade doesn't have a native syntax for what you are describing, but you could do something like this:

```jade
each post, index in posts
    if index % 3 === 0 
        | <div class="row">
    div(class="span4")
        h2
            a(href="/u/#{post.user}") #{post.user} 說
        p
            small= post.time
        p= post.post
    if index % 3 === 2 || index === posts.length - 1
        | </div>
```

or

```jade
- var index = 0
while index < posts.length
    .row
        each post in posts.slice(index, index + 3)
            - index++
            .span4
                h2
                    a(href="/u/#{post.user}") #{post.user} 說
                p
                    small= post.time
                p= post.post
```

or

```jade
-
    function group(arr) {
        return arr.reduce(function (out, cur, i) {
            var row = i / 3 | 0
            if (!out[row]) out[row] = [cur]
            else           out[row].push(cur)
            return out
        }, []);
    }

each row in group(posts)
    .row
        each post in row
            .span4
                h2
                    a(href="/u/#{post.user}") #{post.user} 說
                p
                    small= post.time
                p= post.post
```

**Comment by cloudzhong** [comment]
Hi Timothy Gu,
Thank you very much
Cloud
