### ISSUE TITLE
How to create a custom markup without DOM tag embracing it

### ISSUE THREAD

**Issue by ekkapob** [jadejs/jade#2063]
How can I produce the result below using Jade? 

I'd like to create HTML with {% ...  %} which doesn't have a tag embracing it. Every time I do, Jade put my {%} in string.

I am not sure if my question might have already been answered. If so, please give me the link.
Thank you.

````
<table>
  <tr>
    {% for product in products %}
    <td>
      some info
    </td>
    {% endfor %}
  ...
````

**Comment by netlovers** [comment]
How about http://jade-lang.com/reference/iteration/ ?

**Comment by ekkapob** [comment]
Thank you but I don't want to create HTML elements here. I just need the text of {% for product in products %} and {% endfor %} in my output HTML. The end point is email marketing engine which requires this elements in HTML.

**Comment by netlovers** [comment]
Okay, then I guess the piped text is what you are looking for:
http://jade-lang.com/reference/plain-text/

**Comment by ekkapob** [comment]
Thanks a lot! I am closing this issue.
