### ISSUE TITLE
Default parser in options.parser throws TypeError: tokens must be passed to TokenStream as an array

### ISSUE THREAD

**Issue by bit-seq** [jadejs/jade#2069]
I read up upon jades parser with the motivation to manipulate the ast to automatically insert content on specific recognized patterns. At least the modularisation seemed promising, [the api allows to specify an option which overrides the default parser][1]. However my custom parser (a simple wrapper) failed with errors as well as a pristine jade-parser.

    var jade = require('jade');
    var jade-parser = require('jade-parser');

    var options = {
      parser: jade-parser
    };
    try {
      var html = jade.compile('Some sample text', options)({});
    } catch(err) {
      // TypeError: tokens must be passed to TokenStream as an array. 
      console.log(err);
    }

As far as I understand, the parser retrieves input that's lexed already with stripped off comments, it must be simply replaceable with other parsers providing the same interface. However, the thrown error raises since the unchanged sample text reaches the parser.
Is there an issue? `jade-parser` in the latest version is a dependency of jade. This is another point why I thought that there's nothing changed by specifying the said parser manually.

Thanks in advance!

  [1]: http://jade-lang.com/api/

**Comment by TimothyGu** [comment]
jade-parser is part of jade@2.0.0; it's not compatible with jade 1.*.

**Comment by TimothyGu** [comment]
To clarify, jade 2.0.0 is the future release of jade.
