### ISSUE TITLE
Extra pixels after using Pretty = true !

### ISSUE THREAD

**Issue by omidgolparvar** [jadejs/jade#2070]
When I use pretty=true to make output source code human readable, it adds extra pixels at right side of elements. 
this is without Pretty=true
![screen shot 2015-09-02 at 12 37 41](https://cloud.githubusercontent.com/assets/5128342/9625972/7839b762-516f-11e5-856f-4cd5797705e2.png)

and this is with that.
![screen shot 2015-09-02 at 12 37 08](https://cloud.githubusercontent.com/assets/5128342/9625985/8d40cba0-516f-11e5-885f-9a43e13d3072.png)

I tried also '\t' (pretty = '\t'), but no difference. :(
How can I fix this?

**Comment by bloodyowl** [comment]
it seems your elements are styled as `inline-block`, which is whitespace-sensible. you can fix this problem using CSS, by setting the parent font-size to `0`, and resetting it a your elements level (using `1rem` or `16px` for instance). another solution is to use a negative margin-left, although this is a more fragile solution.

**Comment by ForbesLindesay** [comment]
Don't use pretty mode.  Pretty mode is only for debugging/documentation.  You should probably just use the element inspector in your web browser for that anyway.
