### ISSUE TITLE
Add an "unparsed" variation similar to "unescaped" to allow for regex in attributes.

### ISSUE THREAD

**Issue by howardroark** [jadejs/jade#2071]
I would like to set  html data attributes to regular expressions, but because jade removes all `\` characters I end up having to write the regex attribute in a way where it becomes unreadable because of the need to escape them.

It would be great if there was a variance of `!=` that was truly unescaped in that Jade does nothing to it at all.  Maybe call it "unparsed" or something...  `==` would be nice.

Mention of this same issue can be found here...

http://stackoverflow.com/questions/26655320/how-to-use-pattern-attribute-in-jade-template

**Comment by TimothyGu** [comment]
How would you have a " character in such "unparsed" attribute though? This whole thing is already achievable with the current architecture, that is standardized by JavaScript.

**Comment by TimothyGu** [comment]
Also see [my comment](https://stackoverflow.com/questions/26655320/how-to-use-pattern-attribute-in-jade-template#comment52641840_26655321) to the SO question.

**Comment by howardroark** [comment]
Hey @TimothyGu !  You will have to excuse me as my knowledge of the JavaScript are likely a lot less advanced than yours, and my ability to discuss it is limited. I am not entirely sure what you mean about the `"` character.

Maybe it would be better to describe it as a desire to have a "raw" html attribute without any interference and need to escape...

#### Currently...
```
input(data-pattern="\w\s\d")
```
outputs to
```
<input data-pattern="wsd" />
```

#### The desire would be for this...

```
input(data-pattern=="\w\s\d")
```
to output
```
<input data-pattern="\w\s\d" />
```
