### ISSUE TITLE
UglifyJS has security vulnerabilities (as reported from NSP)

### ISSUE THREAD

**Issue by valeriansaliou** [jadejs/jade#2072]
Hello,

Looks like Jade v1.11.0 doesn't pass NSP security test anymore (which breaks my builds and may break others builds).

The reason is that one of the dependencies it's using (uglifyjs v2.2.5) has been discovered as vulnerable a few days ago.

NSP suggests v2.4.24 to be used instead, which is no more vulnerable.

Would it be possible to bump up uglifyjs in the next release of Jade?

Cheers and thanks for the great work!

**Comment by valeriansaliou** [comment]
Crap, uglifyjs is a dependency of transformers which is a dependency of Jade itself.

Gotta report it to transformers too, at least you can check if you can bump up the transformers dependency to an upper version.

**Comment by TimothyGu** [comment]
Jade 2.0.0 will be released without this vulnerability. Jade 2.0.0 will also discontinue using transformers.
