### ISSUE TITLE
Self Closing Tags should be respected in HTML, especially in SVG

### ISSUE THREAD

**Issue by ryanvfung** [jadejs/jade#2082]
I am using Jade v1.11.0 through Node.js
While the DOCTYPE specified is HTML, Jade should still respect self closing tags (e.g.: `<path/>`, `<rect/>`, `<circle/>`, etc.)  especially in embedded XML types such as SVG (maybe also MathML).

Related to #1510

Example Jade input:
```jade
doctype html
html
  head
  body
    svg(width="200px", height="230px", version="1.1", xmlns="http://www.w3.org/2000/svg", xmlns:xlink="http://www.w3.org/1999/xlink")
      <circle cx="100" cy="100" r="100" fill="#000" />
      <circle cx="100" cy="100" r="95" fill="#ff0" />
    svg(width="200px", height="230px", version="1.1", xmlns="http://www.w3.org/2000/svg", xmlns:xlink="http://www.w3.org/1999/xlink")
      circle/(cx="100", cy="100", r="100", fill="#000")
      circle/(cx="100", cy="100", r="95", fill="#ff0")
```
produces the following HTML output:
```html
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <svg width="200px" height="230px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
      <circle cx="100" cy="100" r="100" fill="#000" />
      <circle cx="100" cy="100" r="95" fill="#ff0" />
    </svg>
    <svg width="200px" height="230px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
      <circle cx="100" cy="100" r="100" fill="#000">
      <circle cx="100" cy="100" r="95" fill="#ff0">
    </svg>
  </body>
</html>
```
When rendered, the following is shown:
![2015-09-12 23-05-41](https://cloud.githubusercontent.com/assets/2174715/9834038/dd8e26da-59a2-11e5-833a-51496b1ed463.png)

As shown by the example render, the output is interpreted differently.
The produced HTML looks almost identical, but because the circle tag is not closed, parsers such as Google Chrome will keep them open and the second circle tag is a child of the first circle tag, causing incorrect / unexpected results.
Both SVG tag contents should have identical Jade outputs if self closing tags are respected.

**Comment by TimothyGu** [comment]
PR available at jadejs/jade-code-gen#15.
