### ISSUE TITLE
Special symbols

### ISSUE THREAD

**Issue by LinkOut** [jadejs/jade#2085]
I have set:

```jade
doctype html
html
    head
        meta(charset='utf-8')
```

When i try to show a "©", it does not work.

**Comment by TimothyGu** [comment]
Your input file does not have any `©` in it.

**Comment by LinkOut** [comment]
That is a template i am using for all pages, on the other page i am using someting like this:

div
                        strong Copyright
                        |  Example Company © 2014-2015

The output is : �

**Comment by TimothyGu** [comment]
I can't reproduce this. With:

```jade
doctype html
html
    head
        meta(charset='utf-8')
    body
        div
            strong Copyright
            |  Example Company © 2014-2015
```

the output for me is

```html
<!DOCTYPE html><html><head><meta charset="utf-8"></head><body><div><strong>Copyright</strong> Example Company © 2014-2015</div></body></html>
```

and the HTML renders like

![image](https://cloud.githubusercontent.com/assets/1538624/9878654/a5e791bc-5b78-11e5-9a6b-592b3f666b1d.png)

**Comment by ForbesLindesay** [comment]
Doesn't look like this is a jade bug.  Feel free to continue the discussion.

I suspect checking what the html output looks like in view-page-source to see if it still looks correct in the source.

**Comment by LinkOut** [comment]
I'm doing the same as you do, i have made a file called: test.jade and the content of that file is that you typed up there. My outpur is this one:

<!DOCTYPE html><html><head><meta charset="utf-8"></head><body><div><strong>Copyright</strong> Example Company � 2014-2015</div></body></html>

**Comment by TimothyGu** [comment]
Can you do a hexdump of both the input jade file and the output html file? If you are on a POSIX system try `od -A x -t x1z test.jade` and `od -A x -t x1z test.html`.

**Comment by LinkOut** [comment]
How to do that hexdump on windows?

**Comment by ForbesLindesay** [comment]
An alternative, create a GitHub repo with the jade file in it and a script to run to build the html file.

**Comment by LinkOut** [comment]
Ok i will create a repo for that, i am using Node JS & Express + Jade

**Comment by LinkOut** [comment]
https://github.com/LinkOut/jade-test 
there is the testing repo

**Comment by jeromew** [comment]
You can see on the raw file : https://raw.githubusercontent.com/LinkOut/jade-test/master/views/index.jade

that your editor encoded the file using the iso-8859-15 encoding and not utf-8.

When rendered in a browser using the utf-8 encoding, this raw file shows the question mark character, which is typical of a non ascii character encoded using iso-8859-15 shown using an utf-8 character.

When the browser is forced to use a iso-8859-15 encoding, the copyright sign is displayed correctly.

**Comment by LinkOut** [comment]
Thanks for the answer but in my IDE i have those 2 settings under : Editor > File Encodings 
IDE Encoding: UTF-8
Project Encoding: UTF-8

This is not correct?

**Comment by jeromew** [comment]
Is this Eclipse ? can you check the "File encoding" of this specific file ?
In any case, the raw file that github shows is not correct ; you need to understand and fix this before we can say anything regarding Jade.

**Comment by LinkOut** [comment]
Seems is not a jade problem since as i said if i change the file encoding manually, the problem disappears. 
I am not using eclipse, but WebStorm from IntelliJ.

**Comment by DinaTaklit** [comment]
Another option is to use the special char `&copy;`
```pug
div(class="copyright")
    a(href="#") School
    |  &copy; 2020 All Right Reserved
```
The result will be 

School © 2020 All Right Reserved
