### ISSUE TITLE
generating inline escaped html using Jade sintax

### ISSUE THREAD

**Issue by marek95** [jadejs/jade#2087]
Is there any way to generate escaped code using jade syntax?

This basically what i would like to do:

```
pre: code
  div
```

And the desired output would be:

```html
<pre><code>  
  &lt;div&gt; &lt;/div&gt;
</code></pre>
```

But it does not work like this. it just outputs:

```html
<pre><code>
  <div></div>
</code></pre>
```

It would be helpful for documentation for my project. Code would be shown on one half, and on the other it would be shown in action.

**Comment by vai** [comment]
Perhaps look at using https://github.com/jstransformers/jstransformer-escape-html as a filter?

**Comment by ForbesLindesay** [comment]
Currently there's no way of doing this, but jade@2.0.0 will let you do:

```jade
pre: code
  :escape-html:jade
    div
```

to get approximately what you're asking for.
