### ISSUE TITLE
server side include .JSON or .JS

### ISSUE THREAD

**Issue by diginfo** [jadejs/jade#2088]
how can I include server-side JS code into a template, this code should not be sent to the browser, but is used for variables and or functions etc ?

**Comment by ForbesLindesay** [comment]
If you're templates are being rendered on the server, just pass the functions and variables you want available as locals.  Locals are not sent to the client unless you explicitly write them into the document somewhere.

If you're rendering on the client side, then no you can't use server side code on the client.

I'm closing this as it's not an issue with jade.  Feel free to continue the discussion though.

**Comment by diginfo** [comment]
Thanks, but this has not answered the question:

How can I include a json or javascript file directly into a jade template ?

I am not referring to pushing in data from nodejs, but a physical file containing variables

i.e.
    include somefile.json

each row in jsonfile


But if I use this method, then the json data

**Comment by TimothyGu** [comment]
- var jsonfile = require('./json.json')
