### ISSUE TITLE
Deprecate or remove interpolation in attributes

### ISSUE THREAD

**Issue by TimothyGu** [jadejs/jade#2095]
Attributes themselves are already JavaScript strings. With the advent of ES2015 template strings, Jade's interpolation only adds a layer of [ugliness](https://github.com/jadejs/jade-lexer/blob/master/index.js#L763-L771) and [complexity](https://github.com/jadejs/jade-lexer/blob/master/index.js#L854-L871) that can be totally avoided without losing features.

See also #1991.

**Comment by TimothyGu** [comment]
Even more outrageous is the fact that this feature was [not even documented](http://jade-lang.com/reference/attributes/).

**Comment by vai** [comment]
Huh. I use these (on board with es-* though). I must have found them from external presentations? curious

**Comment by ForbesLindesay** [comment]
They have appeared in other places on the web/examples.  I have always recommended against them though and look forward to their demise :)
