### ISSUE TITLE
Calling mixin from a variable

### ISSUE THREAD

**Issue by diginfo** [jadejs/jade#2100]
I am trying to call a mixin or inline code from a  variable something like this:

   var head="+headmixin(title)"

I have tried the following but none appear to work:

    =head
    !{head}

But the tags are not rendered.

Can this be done ??

The head variable does not always contain a mixin and may also contain other jade inline syntax.

**Comment by jeromew** [comment]
I am not sure I understand exactly what you want to do.

The closest I can think of is this usage of the dynamic mixin notation :

    - var mixinName = "headmixin"
    - var title = "my title"
    +#{mixinName}(title)
