### ISSUE TITLE
Pass Object from Jade to function

### ISSUE THREAD

**Issue by LinkOut** [jadejs/jade#2101]
I am doing a loop to populate a table using
each obj, i in objs
How can i pass "onClick" that obj to a function?

Thanks

**Comment by TimothyGu** [comment]
Are you using Jade in the browser or in Node.js?

**Comment by LinkOut** [comment]
Node.js

**Comment by TimothyGu** [comment]
Event handlers like onclick can only be added through HTML or client-side JavaScript. This is not something Jade can help you with.

If you want to markup an `onclick` attribute, just do it like all other Jade attributes:

```jade
button(onclick='alert("clicked!")')
```

**Comment by ForbesLindesay** [comment]
The issue is that html (which is what jade generates) expects `onClick` to be a string rather than a function.  You could try using react-jade which would support what you're attempting right out of the box.

**Comment by iShawnWang** [comment]
solved at : https://github.com/pugjs/pug/issues/2933
