### ISSUE TITLE
Pagination without database of massive image gallery? Possible?

### ISSUE THREAD

**Issue by dlewand691** [jadejs/jade#2106]
Wondering if there is a way to paginate a massive image gallery of what will probably be a few thousand entries without a database or PHP? If not, any recommendations? Jquery or similar? Trying to keep the site flat and clean.

**Comment by TimothyGu** [comment]
How is this related to Jade?

**Comment by dlewand691** [comment]
I'm rebuilding a website from scratching using Jade, no CMS or back-end service so far. Was hoping there might be a solution given the rash of "flat-file", "No CMS" templating frameworks like Jekyll or Middleman. 

Looking at other systems, if there was a way to build a loop that slices X number of entries into separate pages? Have not found any suggestions yet elsewhere, so thought I'd ask here as a possibility.

**Comment by vai** [comment]
I've enjoyed success using jade in tandem with front-matter, extracting metadata from the content provided as static, then using the json result as variables in the jade build. This allows for compile-time definition of menus, pagination etc. Specifically, I've used this approach with the http://roots.cx/ and https://github.com/carrot/roots-dynamic-content tooling. The idea also applies to gulp, grunt etc.

**Comment by vai** [comment]
more direct link to the idea: https://github.com/carrot/roots-dynamic-content/blob/master/docs/intro.md

**Comment by dlewand691** [comment]
Wow thanks so much for the suggestions, I'll definitely check it out. 

What are you thoughts on Harp, Wintersmith or Sigal?

**Comment by TimothyGu** [comment]
Not a Jade issue so closing. Feel free to continue the discussion though.
