### ISSUE TITLE
Jade looks only at the last `doctype` even when they're not applied

### ISSUE THREAD

**Issue by kizu** [jadejs/jade#2108]
Here is a test-case:

``` Jade
if true
  doctype html
else
  doctype basic

input
```

If you'd remove the else part, the result would have `<input>`, right now it has `<input/>` as if the basic doctype was applied (while it obviously wasn't).

**Comment by ForbesLindesay** [comment]
The switch happens at compile time, so there's not much we can do about this.  You can force the doctype by passing `{doctype: 'html'}` as an option though.

**Comment by TimothyGu** [comment]
Closing since it is impossible to fix without major decrease in performance or major infrastructure rework.
