### ISSUE TITLE
[BUG] Processing special characters

### ISSUE THREAD

**Issue by TheFlighteur** [jadejs/jade#2112]
Currently I can't write any accents (éà...) in any string. They all translate to this : �. Is there anything to do to allow me to correct this behaviour ?

**Comment by TheFlighteur** [comment]
Is there someone to answer or resolve my bug ? sure I'm not alone, but some feedback on this would be much appreciated.

**Comment by TimothyGu** [comment]
Can you push the jade source file to a GitHub repo (to preserve character encoding)? I have a feeling that this issue is not related to Jade as most similar previous issues point to user errors (e.g. #2085)

**Comment by TheFlighteur** [comment]
Thank you ! This resolved my bug. It was indeed my IDE that was causing this. I've never thought of this. For everyone looking at this issue : I work on phpstorm, I changed the default encoding for all the files that it generate and also the files you create yourself in the encoding section to UTF-8 (that is the encoding I use on all of my projects). Then I re-saved all of my jade files in UTF-8 encoding with sublime text3.

**Comment by 22nds** [comment]
Just a note for those who might encounter this issue (like I did today). Make sure you have `meta(charset='utf-8')` in your pug/jade file - so that browser renders characters correctly.
