### ISSUE TITLE
[QUESTION] How to extract block contents from mixins via api?

### ISSUE THREAD

**Issue by mooror** [jadejs/jade#2116]
Hey there Forbes, First off I want to thank you so much for all the time and effort you have put into jade. Its and amazing open source contribution. Secondly I wanted to ask if there is any way I can use the jade api to extract the contents of a mixin block so I can manipulate it with javascript? You see, my workers and I love jade so much that we want to integrate it into our current workflow (which includes node.js and grunt). Also I know there is a grunt-contrib-jade task and was wondering if there might be any way to integrate this functionality into it.

Thank you in advance, 
Mooror

**Comment by TimothyGu** [comment]
In short: No.

To elaborate, a mixin with the block keyword is compiled to something like this:

```jade
mixin a
  block
```

```js
jade_mixins["a"] = jade_interp = function() {
	var block = (this && this.block),
		attributes = (this && this.attributes) || {};;
	block && block();
};
```

`block`, if provided, is a function that directly pushes to the main buffer. Therefore there isn't a way to manipulate the output of that.

However, there has been some work done to make this possible: from jadejs/jade-code-gen#3 to #2055. So, there is a high possibility that you'll be able to do this in the near future :)

**Comment by mooror** [comment]
Thank you so much for your quick reply. And thank you so much for your answer.Would you happen to have any kind of timeline on that new feature? I can totally understand if you don't have a timeline though lol I am also a javascript programmer so I know what its like (bugs,unexpected functionality,etc.).
Also would this new feature take care of extracting classes that have been appended to mixins as well?
Example:
+mixin('parameter')(classes=["class1","class2"])

**Comment by ForbesLindesay** [comment]
I would expect 2.0.0 to be released some time in the next few months.  I really want to get it done soon.

I'm not sure what you're asking about with that mixin case?  You can already do that by simply:

```js
mixin my-mixin
  - console.log(attributes.classes);
```

**Comment by mooror** [comment]
Thank you Forbes for your reply I had not known that you could log classes like that. So thank you. Secondly I wanted to ask if the jade.compileClientWithDependenciesTracked will display the paths to each of the files in the dependency array or only the file names?

**Comment by TimothyGu** [comment]
> Secondly I wanted to ask if the jade.compileClientWithDependenciesTracked will display the paths to each of the files in the dependency array or only the file names?

Paths.

**Comment by mooror** [comment]
Thank you both for your time. You have answered my questions promptly and for that I thank you. Though I still have more questions they stray off into other areas of jade and therefor I will ask them in different issues. Thanks again!
