### ISSUE TITLE
filter sugar

### ISSUE THREAD

**Issue by BabylonSix** [jadejs/jade#2117]
Is it possible to make the filter syntax more elegant?

currently the syntax for declaring a filter on a tag is

```jade
style: :stylus
  'stylus code'

.content: :markdown
  'markdown content'

script: :coffee-script
  'coffee-script code'
```

can it be made more succinct? so:

```jade
style::stylus
  'stylus code'

.content::markdown
  'markdown content'

script::coffee-script
  'coffee-script code'
```
it's a small change, but it will just make the code feel more clear

**Comment by BabylonSix** [comment]
oh and I understand that you can do something like

style
    :stylus
        *stylus code*

but that feels like a whole bunch of unnecessary nesting

**Comment by TimothyGu** [comment]
It would disallow marking up `<style::stylus>`.
