### ISSUE TITLE
[QUESTION] How to replace include functionality in the jade compiler

### ISSUE THREAD

**Issue by mooror** [jadejs/jade#2118]
hello again, I just wanted to know what code segment controls the include replacement functionality. I am going to be making a fork of this repo that will bridge the gap between jade and another technology me and my colleges are using. In this forked version of jade I need the compiler to replace the includes in my jade files with special tags. For instance:
example.jade (input):
`include jadeFile.jade`
example.html (output):
`[[jadeFile]]`

Is there any way to do this relatively simply(I by no means want you guys wasting all your time with my problems :D )? 

Thanks in advance,
Mooror

p.s. In case it was not clear in the example, I would like the special tag to be comprised of '[[' + jadeFileName + ']]'

**Comment by mooror** [comment]
Also I want to apologize for leaving all these questions in the issues section of git. I just don't know any where else to put them.

**Comment by mooror** [comment]
I did some looking through the jade code (and accidentally started my searching in the 9000 line jade.js file *Face Palm* ) and found the parseInclude function in the parser.js file. If I am reading the javascript correctly (which I may not be) it looks as though I will have to change this to get my wanted result

**Comment by TimothyGu** [comment]
AFAICT you are looking at the source of Jade 1.11.0 (or earlier). Don't. Jade 2.0.0, although not published yet, will have a completely different architecture that is very modularized (see #2051 for a chart describing how each module has a specific role in the new system). It will be a lot easier to just fork one file/component rather than the entire Jade repo.

Or you can choose not to fork at all.

> found the parseInclude function in the parser.js file. If I am reading the javascript correctly (which I may not be) it looks as though I will have to change this to get my wanted result

That's probably the best idea. This should suffice:

```js
var jade = require('jade')

jade.Parser.prototype.parseInclude = function () {
  var tok = this.expect('include')
  var file = tok.val.trim()
  // do whatever you need with `file`
  // this removes the .jade extension
  file = file.replace(/\.jade$/, '')
  return {
    type: 'Text',
    val: '[[' + file + ']]',
    line: tok.line,
    filename: this.filename
  }
}
```

```js
> jade.render('include abc.jade')
'[[abc]]'
```

**Comment by mooror** [comment]
Thank you so much for your amazing help. I now really feel bad for continuing to comment after the topic has been closed (I mean no disrespect). I talked with my colleague and we agreed that we only want this functionality to be used on spacific include paths. 
Example: include normal.jade Output: *Contents of that file*
And
Example include notnormal.tag.jade Output: [[notnormal]]
Would this still be possible with just changing that function?

**Comment by TimothyGu** [comment]
> I now really feel bad for continuing to comment after the topic has been closed (I mean no disrespect).

No don't worry. I just closed the issue because this isn't something we can *fix* in Jade.

> Would this still be possible with just changing that function?

You can backup the original function:

```js
var jade = require('jade')

var originalParseInclude = jade.Parser.prototype.parseInclude;
jade.Parser.prototype.parseInclude = function () {
  var tok = this.expect('include')
  var file = tok.val.trim()
  file = file.replace(/\.jade$/, '')

  if (file === 'normal') {
    // Push the token back
    this.tokens.defer(tok)
    // Call original parseInclude
    return originalParseInclude.call(this)
  }
  return {
    type: 'Text',
    val: '[[' + file + ']]',
    line: tok.line,
    filename: this.filename
  }
}
```

**Comment by mooror** [comment]
Thank you once again for your timely help. I tried your code above and ran into some problems. But before I go into the problem I'm facing I will show you my code:
Parser.js (inside the lib folder of jades npm package):
```javascript
parseInclude: function(){
    var fs = require('fs');
    var tok = this.expect('include');
    var path = this.resolvePath(tok.val.trim(), 'include');
    this.dependencies.push(path);
    // has-filter
    if (tok.filter) {
      var str = fs.readFileSync(path, 'utf8').replace(/\r/g, '');
      var options = {filename: path};
      if (tok.attrs) {
        tok.attrs.attrs.forEach(function (attribute) {
          options[attribute.name] = constantinople.toConstant(attribute.val);
        });
      }
      str = filters(tok.filter, str, options);
      return new nodes.Literal(str);
    }
    var jade = require('jade')
    var originalParseInclude = jade.Parser.prototype.parseInclude;
    jade.Parser.prototype.parseInclude = function () {
      var tok = this.expect('include')
      var file = tok.val.trim()
      file = file.replace(/\.jade$/, '')
      var regex = new RegExp(/(.*)-set/g);
      if(!file.match(regex)) {
        // Push the token back
        this.tokens.defer(tok)
        // Call original parseInclude
        return originalParseInclude.call(this)
      }
      return {
        type: 'Text',
        val: '[[$' + file + ']]',
        line: tok.line,
        filename: this.filename
      }
    }
```
home-template.jade (Part of the jade file I'm wanting to compile):
```javascript
doctype html
html(lang="en")
	head
		meta(content="text/html;charset=utf-8" http-equiv="Content-Type")
		meta(http-equiv="Content-Type" content="text/html; charset=utf-8")
		include head-styles-set.jade
		meta(name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no")
	body
		aside#offcanvas-right
		div#page-wrapper.sl-menu-push-this.sl-menu-click-off
			include ../../../stripes/sl-old-ie-warning/dist/jade/handler.jade
```

First off I'm sorry I cannot give you all the contents of the jade file. The project we are working on is not open source so...yeah. Next thing is that you may have noticed I changed the code a bit from your example. I wanted to test each file name to see if it matched the regx and if it doesn't then send it to the originalParserInclude function. When I tried to run jade it seems to go over the "include head-styles-set.jade" include fine but when it reaches the "include ../../../stripes/sl-old-ie-warning/dist/jade/handler.jade" include (on my line 14) it errors out with this:
```
Cannot read property 'defer' of undefined
```
I was trying to diagnose the problem and I'm thinking that it might have something to do with this line
`this.tokens.defer(tok)` in the if statement. Unfortunately I don't know what a token is in jade so its a bit hard to trace whats going wrong. Also I would like to know if there is any way I can log out to console certain values (for debugging purposes).

Thank you once again :D,
Mooror

**Comment by mooror** [comment]
Oh lol console.log works fine (*face palm*). So when I ran 
```
console.log("This.token is equal to " + this.tokens);
```
It returned this:
```
This.token is equal to undefined
```

**Comment by mooror** [comment]
I also ran `console.log("This object keys: " + Object.keys(this));` 
which returned:`This object keys: input,lexer,filename,blocks,mixins,options,contexts,inMixin,dependencies,inBlock`
If I did this correctly it appears as though the `this` object (at least in this scope) does not even contain a tokens key. This is my understanding, but I could be in error.

**Comment by mooror** [comment]
Interesting. I found another reference to `tokens` on line 264 (in mine any way) under the parseText function. It looks like this `var tokens = this.parseInlineTagsInText(tok.val);`. Not sure if this is perhaps what I need to add.

**Comment by TimothyGu** [comment]
No, I didn't mean for you to add my code snippet to jade's parser.js. This piece of code should be in your own application for monkey-patching the official jade module. You don't want to ever look in jade's sources ;)

**Comment by mooror** [comment]
I don't suppose it it would make to much of a difference but I'm adding these changes to the jade npm package inside  the grunt-contrib-jade plugin for grunt.js .

**Comment by mooror** [comment]
Wow...now i feel dumb *face palm*

**Comment by mooror** [comment]
So in my case since i am using the grunt-contrib-jade plugin, would you suggest I add your code to the plugin code?

**Comment by mooror** [comment]
The way I am using jade in this custom manner is through another grunt task I am creating. This task calls upon the grunt-contrib-jade plugin every time I need to compile my jade code. But I have other tasks that also call to the grunt-contrib-jade plugin (and I will need the custom functionality in those ones too)  so I was thinking if i put your code in the grunt-contrib-jade plugin that I can kill many birds with one stone. However if you think it would be better for me to put the code in my custom grunt task I will do it that way.

Thank you for your time & help

**Comment by mooror** [comment]
So I thought that i may as well make sure that the function I'm putting into the grunt-contrib-jade plugin is working so I created a simple file with only one include. `include head-styles-set.jade` This matches the regx I set up and therefor should replace the line with the tag. Thankfully I found that this indeed did work and replaced the include with a tag instead of the file contents of that jade file.
Output: `[[$head-styles-set]]`. So that's one half of the function that is definitely working.

**Comment by mooror** [comment]
If you could answer two questions I may be able to figure it out myself...(not that I don't want your help. I just don't want to waste your time). 1) What does the defer(tok) function/property do? and 2) What is `the.tokens` supposed to contain?

**Comment by TimothyGu** [comment]
Oh wait, you are using Jade 1.11.0 aren't you… then you should use this:

```js
var jade = require('jade')

var originalParseInclude = jade.Parser.prototype.parseInclude;
jade.Parser.prototype.parseInclude = function () {
  var tok = this.expect('include')
  var file = tok.val.trim()
  file = file.replace(/\.jade$/, '')

  if (file === 'normal') {
    // Push the token back
    this.lexer.defer(tok)
    // Call original parseInclude
    return originalParseInclude.call(this)
  }
  return {
    type: 'Text',
    val: '[[' + file + ']]',
    line: tok.line,
    filename: this.filename
  }
}
```

In (the unreleased) jade 2.0.0, `this.tokens` will be a [TokenStream](https://github.com/jadejs/token-stream). `this.tokens.defer` pushes the token to the beginning of the stream, so that the next time something consumes a token, that will be returned immediately.

In the older 1.11.0, TokenStream is built into the lexer. In 2.0.0 we decided the fully separate the lexer and the parser, so we need the TokenStream split out.

**Comment by mooror** [comment]
The headaches you have saved me...Thank you so much. That worked very well! No errors! Unfortunately I may have more questions later for you (lol still such a noob when it comes to jade) but you have been an amazing asset to me. 

Thanks again TimothyGu for all your help,
Mooror

**Comment by TimothyGu** [comment]
Most people I consider "good" at Jade don't delve this deep into Jade interiors, so an A+ for efforts!

**Comment by ForbesLindesay** [comment]
You could simplify this slightly by using `peek` to get the next token without actually removing it from the stream, that way you wouldn't need to call `defer` afterwards. You then call `expect` (to actually consume the token) only if you've decided you want this special handling.

I can't wait to see how easy this stuff is once we release 2.0.0 and it can just be a "plugin"

**Comment by mooror** [comment]
Sorry for the late reply. Thank you TimothyGu for your kind words, and Forbes I also cannot wait to see 2.0.0's awesome new features :D .
