### ISSUE TITLE
Bug when escaping arrays as attribute for mixins

### ISSUE THREAD

**Issue by chris-scheurle** [jadejs/jade#2119]
*Jade 1.11.0:*
```jade
mixin list
	if(typeof(attributes.entries) === 'object' && (attributes.entries instanceof Array) && attributes.entries.length > 0)
		ul
			each entrie in attributes.entries
				li !{entrie}
	else
		p Not a list!

//- works fine
+list(entries=['1','2','3'])
//- "entries" gets converted from array to string
+list(entries=['1','2&3'])
```
compiles to:
```html
<ul>
	<li>1</li>
	<li>2</li>
	<li>3</li>
</ul>
<p>Not a list!</p>
```
This is just a simple example, but I have a lot of mixins that rely on arrays beeing passed as attributes.

**Comment by ForbesLindesay** [comment]
To do this, you must pass them un-escaped and then escape them inside the mixin.  i.e.

```jade
mixin list
    if(typeof(attributes.entries) === 'object' && (attributes.entries instanceof Array) && attributes.entries.length > 0)
        ul
            each entrie in attributes.entries
                li #{entrie}
    else
        p Not a list!

//- works fine
+list(entries!=['1','2','3'])
//- "entries" gets converted from array to string
+list(entries!=['1','2&3'])
```

This is because jade has to play it safe and escape the array (converting it to a string in the process).

**Comment by chris-scheurle** [comment]
Like I said: the code above is just a *simple* example. Passing attributes un-escaped and then escaping them again works fine when you *know* what attributes there are to be expected. But in my real world use cases I use code like
```
+list()&attributes([some object with (any number of) attributes/values from somewhere else])
```
and then things start to get *really* confusing (no way to use `!=` here, and no way to know which arguments originally were an array).

**As to playing it safe:** like my example shows, there is no 'playing it safe', when an attribute is *not* escaped by jade. So, *imho.* it would be far more *consistent* (and thus *safer*) to do something like
```javascript
    if(typeof(attributes[attribute]) === 'object' && (attributes[attribute] instanceof Array)){
        for(var i = 0; i < attributes[attribute].length; i++){
            attributes[attribute][i] = escape(attributes[attribute][i]);
        }
    }
    else{
        // normal escaping ...
    }
```
in your code that escapes the arguments.

**Comment by TimothyGu** [comment]
Why are you using attributes for arrays? Attributes are what they are – HTML attributes, and thus has built-in architecture for escaping. Forcing the attribute infrastructure to do something it is not designed to do is never a good idea.

Assuming that you really want to use attributes:

> (no way to use `!=` here, and no way to know which arguments originally were an array)

`&attributes` is not escaped.

> ```js
attributes[attribute][i] = escape(attributes[attribute][i]);
```

This is exactly what @ForbesLindesay is doing:

```jade
each entrie in attributes.entries
    li #{entrie}
```

----

All in all, something like this would work (Jade syntax and JS cleaned up a bit):

```jade
mixin list
    if Array.isArray(attributes.entries) && attributes.entries.length > 0
        ul
            each entrie in attributes.entries
                li #{entrie}
    else
        p Not a list!

+list&attributes({entries: ['1','2','3']})
+list&attributes({entries: []})
+list
```


```html
<ul>
  <li>1</li>
  <li>2</li>
  <li>3</li>
</ul>
<p>Not a list!</p>
<p>Not a list!</p>
```

**Comment by ForbesLindesay** [comment]
Yes, we could handle arrays of strings by escaping them individually, rather than converting them to a string and then escaping that.  However, we would have to handle arbitrary data-structures with arbitrary levels of nesting, so it's simpler in this instance for the user to handle this by disabling jade's escaping at the level of the mixin arguments, and then escaping when they actually use the values.

**Comment by chris-scheurle** [comment]
> Why are you using attributes for arrays?

Long story. Short version: to keep my code clean and the document structure more readable. I *could* write a lot of `if`s and `else`s in my individual pages' code, but it seems much tidier to wrap that logic into the mixin and let the *mixin* chose the concrete value of an attribute out of a set of supplied alternatives.

> &attributes is not escaped.

*Thanks!* While I'd *still* like for this issue to be addressed, your suggestion *kind of* fixes my problem. :smile:

> However, we would have to handle arbitrary data-structures with arbitrary levels of nesting

Simple arrays would be enough for *me* :wink:. But does anything speak against definig the functionality in some function that calls itself recursively?

I don't want to be a pain in the ass\*, it's just that the solution proposed by @TimothyGu still leaves me with a lot of ugly code (a lot of `+list&({...})`s, in there and i still haven't figured out how all of this affects my logic) and it's my understanding that the goal of **Jade** is to provide a *simple*, *structured*, *intuitive* way of writing large portions of markup.

**___**
\* *Please pardon my English, I am not a native speaker and it's sometimes hard for me to come up with a fitting, polite figure of speech.*

**Comment by TimothyGu** [comment]
Oh I get what went wrong. If you want to pass attributes with the `()` syntax, you have to disambiguate it with mixin arguments. So:

```jade
//- work
+list&attributes({entries: ['1','2','3']})
+list()(entries!=['1','2','3'])

//- doesn't work
+list(entries!=['1','2','3'])
//- above equivalent to:
//- var arg = entries!=['1','2','3']
//- +list(arg)
//- or
//- +list(false)
```

**Comment by chris-scheurle** [comment]
> Oh I get what went wrong.

If you mean what went wrong in *my* scenario: *nope*.
But I'm glad I inadvertently inspired some improvement. :grinning:

**Comment by ForbesLindesay** [comment]
@TimothyGu we auto-detect attributes in a lot of cases, maybe we should auto-detect even for `!=`?

https://github.com/jadejs/jade-lexer/blob/master/index.js#L630

**Comment by TimothyGu** [comment]
@ForbesLindesay, we can, but I'm concerned with disallowing too many legitimate JavaScript expressions as mixin arguments.

**Comment by ForbesLindesay** [comment]
True, the alternative, which I quite like in a way, would be to force users to always specify the empty arguments (via `()`) regardless of what they put for attributes.
