### ISSUE TITLE
Make AST more consistent

### ISSUE THREAD

**Issue by TimothyGu** [jadejs/jade#2124]
First, this has to be decided before the release of 2.0.0.

While writing the [Jade AST Specification](https://github.com/jadejs/jade-ast-spec/blob/master/SPEC.md), I found a few inconsistencies/points of improvements:

- `yield` statements correspond to a Block, which is inconsistent with NamedBlock (also `yield` keyword is not documented)
- Tag.buffer doesn't do what it says (fortunately it's documented in the parser)
- Conditional and While use `test` as the property name of the JavaScript expression, while Case and When use `expr`. Even though "test" is correct in describing what it does, it could be made more consistent with others
- Conditional uses `alternate`, while `Each` uses `alternative`

**Comment by ForbesLindesay** [comment]
* Lets change the type of the `yield` ast nodeo to be `YieldBlock` or something similar.  I'm not too worried about documenting it as it will be deprecated in favour of `@block` as part of v3.0.0.  If someone wants to step up and document it in the mean time, that would be cool though.  We will need to at least somewhat document it when we write migration docs for 2.0.0 -> 3.0.0
* Similarly for `Tag.buffer`, lets rename the type of that node to `InterpolatedTag` and remove the `buffer` property.
* I don't have too much of a problem with `expr` vs. `test`.  I was aiming to match the JavaScript AST (As per acorn/esprima/babylon) when I named it `test`.
* We should use `alternate` in `Each` as well as in `Conditional`.

**Comment by TimothyGu** [comment]
Fair enough for the property name of `test.

See jadejs/jade-parser#16 and jadejs/jade-ast-spec#2.
