### ISSUE TITLE
Self Closing Tags not generate " /> "

### ISSUE THREAD

**Issue by marti1125** [jadejs/jade#2125]
an example

![jade](https://cloud.githubusercontent.com/assets/223240/10350786/a3771656-6d0b-11e5-8635-329701760385.png)

**Comment by marti1125** [comment]
https://github.com/jadejs/jade-code-gen/commit/5494e377989fb3848b1a1aac4124afbfc9359193

**Comment by ForbesLindesay** [comment]
This bug has been resolved as part of 2.0.0.  The fix will be released no later than 2015-11-01.

**Comment by marti1125** [comment]
ok...

**Comment by shaekuronen** [comment]
@ForbesLindesay Currently using 2.0.0-beta6 and seeing this issue. Is there any configuration that needs to be done to get it working?

**Comment by TimothyGu** [comment]
@shaekuronen, can you give an example?

**Comment by shaekuronen** [comment]
@TimothyGu Hold on this, just realized we're running htmlmin after pug.renderFile, which was responsible for stripping the img closing tag. Still looking into why it's not on the source tag in a picture element.

**Comment by shaekuronen** [comment]
Sorry for the false alarm guys, was all gulp-htmlmin config issue
