### ISSUE TITLE
Nesting filters for includes

### ISSUE THREAD

**Issue by xzfc** [jadejs/jade#2126]
Nesting filters for plain text blocks was added in #1997, but not for includes.

Input:
```jade
script
  include:babel:uglify-js script.js
```
```javascript
// script.js
let foo = 10
```

And the output is not what it is supposed to be:

    <script><include:babel:uglify-js>script.js</include:babel:uglify-js></script>

**Comment by TimothyGu** [comment]
This was fixed some time ago.
