### ISSUE TITLE
[QUESTION] Get all dependencies from all jade includes with jade.compileClientWithDependenciesTracked(source, options)

### ISSUE THREAD

**Issue by mooror** [jadejs/jade#2129]
Is there a way to get all the dependencies of a jade file, even the nested ones?Example: Jade-template.jade needs jade-piece.jade. jade-piece.jade needs another.jade. Dependencies = jade-piece.jade,another.jade

**Comment by TimothyGu** [comment]
`compile` and `compileClientWithDependenciesTracked` should return all dependencies. If not, then that's a bug. Put all files in a git repo or gist and I'll check it out.

**Comment by mooror** [comment]
Unfortunately due to the nature of the project I cannot give you are code exactly but I can give you an example.

```javascript
var filepath = 'path/to/home-template.jade';
var homeTemplate = grunt.file.read('path/to/home-template.jade');
var dep = jade.compileClientWithDependenciesTracked(homeTemplate,{filename:filepath});
```
The jade Im trying to compile
```
include ../../../components/stripes/old-ie-warning/dist/jade/handler.jade
include ../../../components/stripes/col-three/dist/jade/handler.jade
include header-set.jade
include footer-set.jade
include scripts-set.jade
```
dep.dependencies returns
```
>> components\stripes\old-ie-warning\dist\jade\handler.jade,
components\stripes\old-ie-warning\dist\jade\modx.jade,
components\stripes\old-ie-warning\dist\jade\wordpress.jade,
components\stripes\old-ie-warning\dist\jade\html.jade,
components\stripes\col-three\dist\jade\handler.jade,
components\stripes\col-three\dist\jade\modx.jade,
components\stripes\col-three\dist\jade\wordpress.jade,
components\stripes\col-three\dist\jade\html.jade
```
This is correct for the first two includes and their respective dependencies however the last 3 includes don't even show up. So I'm thinking that perhaps the includes have to have slashes in the paths or something

**Comment by mooror** [comment]
Interesting. When I turn on the debug functionality I get : 
```
buf.push("[[$header-set]][[$footer-set]][[$scripts-set]]");
```
when its running through the last three includes. I hope it makes more sense to you then it does to me :D 

Thanks again, 
Mooror

**Comment by mooror** [comment]
Oh lol I just thought about it and realized that this must be due to the changes I made to the parser with that code we did up. The parser must be replacing the paths before the compiler reads them (*face Palm*). with this knowledge I should be able to get it. You can close this topic if you wish.I don't think this is a bug but just something specific to my setup. I will post any more details here.

**Comment by mooror** [comment]
Confirmed my suspicions. It was that new piece of code we added. When I removed it all the dependencies showed up. Lol sorry about that. And thanks for all your help.

**Comment by mooror** [comment]
Hey there again timothy. So I was successfully able to get all the dependencies from the jade but only 
after I had remove the code snippet to change the parseInclude function from my other question. This was good to know as now I know what the cause of the dependency problem is, however I am still unsure of a solution. I wont reopen the issue since I still don't think its a jade bug however I will continue to post my status and questions here. Also Is there any way you can think of to modify this code to get it to work with dependency tracking?
```
var jade = require('jade')

var originalParseInclude = jade.Parser.prototype.parseInclude;
jade.Parser.prototype.parseInclude = function () {
  var tok = this.expect('include')
  var file = tok.val.trim()
  file = file.replace(/\.jade$/, '')

  if (file === 'normal') {
    // Push the token back
    this.lexer.defer(tok)
    // Call original parseInclude
    return originalParseInclude.call(this)
  }
  return {
    type: 'Text',
    val: '[[$' + file + ']]',
    line: tok.line,
    filename: this.filename
  }
}
```

You have my gratitude,
Mooror

**Comment by TimothyGu** [comment]
Not really sure what you want here. Say you have this:

```jade
include normal
include abnormal
```

Do you want the dependencies to include `abnormal` even if `include abnormal` is simply equivalent to `| [[$abnormal]]`?

**Comment by mooror** [comment]
Hello again timothyGu, I was away from my main computer when I sent the last message so the code above is a little outdated. So here is the new code: 
```
var jade = require('jade');
  var originalParseInclude = jade.Parser.prototype.parseInclude;
  jade.Parser.prototype.parseInclude = function () {
    var tok = this.expect('include');
    var file = tok.val.trim();
    file = file.replace(/\.jade$/, '');
    var regex = new RegExp(/(.*)-set/g);
    if(!file.match(regex)) {
      // Push the token back
      this.lexer.defer(tok);
      // Call original parseInclude
      return originalParseInclude.call(this);
    }
    return {
      type: 'Text',
      val: '[[$' + file + ']]',
      line: tok.line,
      filename: this.filename
    }
  }
```
And as for your question, the parserInclude would only trigger on includes that have a filename with -set, so this 
```
include normal.jade
``` 
would run as normal while this
```
include normal-set.jade
```
would trigger the new parser functionality. Finally to actually answer your last question (because I guess I was just clarifying what the code I pasted above does), Yes I want  dependencies to include the normal-set.jade. The reason for this is we have a static work envoronment that will use the dependency check and we have a server side environment that needs the [[$normal-set]] syntax.
I hope that makes sense :D 

Thanks again,
Mooror

**Comment by TimothyGu** [comment]
> Yes I want dependencies to include the normal-set.jade. The reason for this is we have a static work envoronment that will use the dependency check and we have a server side environment that needs the [[$normal-set]] syntax.

Okay, this will be different for Jade v1 and v2 (scheduled to be released next month).

For right now, something like this should work:

```diff
    var originalParseInclude = jade.Parser.prototype.parseInclude;
    jade.Parser.prototype.parseInclude = function () {
      var tok = this.expect('include');
      var file = tok.val.trim();
      file = file.replace(/\.jade$/, '');
      var regex = new RegExp(/(.*)-set/g);
      if(!file.match(regex)) {
        // Push the token back
        this.lexer.defer(tok);
        // Call original parseInclude
        return originalParseInclude.call(this);
      }
+     this.dependencies.push(file);
      return {
        type: 'Text',
        val: '[[$' + file + ']]',
        line: tok.line,
        filename: this.filename
      }
    }
```

You might want to customize what's pushed though: absolute path, file extends, etc.

And see https://github.com/jadejs/jade/blob/v1.x.x/lib/index.js#L151 and https://github.com/jadejs/jade/blob/v1.x.x/lib/parser.js#L586.

**Comment by mooror** [comment]
Thank you so much for the quick reply. So I tried your example and had some small issues. 1. When I used your code I had to move added line above the second file variable to get it to change my dependency output. 2 When I did that it worked fine except it had duplicates of all the already listed dependency paths. So I tried this code:
```
var jade = require('jade');
  var originalParseInclude = jade.Parser.prototype.parseInclude;
    jade.Parser.prototype.parseInclude = function () {
      var tok = this.expect('include');
      var file = tok.val.trim();
      var path = this.resolvePath(tok.val.trim(), 'include');
      file = file.replace(/\.jade$/, '');
      var regex = new RegExp(/(.*)-set/g);
      if(!file.match(regex)) {
        // Push the token back
        this.lexer.defer(tok);
        // Call original parseInclude
        return originalParseInclude.call(this);
      }
      else{
        this.dependencies.push(path);
      }
      return {
        type: 'Text',
        val: '[[$' + file + ']]',
        line: tok.line,
        filename: this.filename
      }
    }
```
Which took care of the duplicates and still listed the -set.jade files as dependencies! Awesome. But then I realized that the way we are doing it wont allow me to get the -set.jade files dependencies will it? I mean it looks like our code (and I am by no means complaining for the code :D) checks whether or not the filename is a -set.jade file and then if it is will completely skip over any parsing into that file. This was okay for what I needed before but now that I am trying to use jades dependency system I don't know if it will work. I really hope we can make this work..I hate to feel like I wasted your time.

Sorry for any lost time,
Mooror

**Comment by mooror** [comment]
I wonder is there any kind of callback system that would allow me to parse all the files and then change the `include example-set.jade` to `[[$example-set]]` ? That might fix our problem.

**Comment by ForbesLindesay** [comment]
You could do that by wiring together the jade@2.0.0 modules (which will get their first stable release on 1st November).  That way what you would do is write a very simple plugin that ran after the loader and before the linker.  At that point, you would simply walk the tree using jade-walk and replace the relevant `Include` nodes with whatever you want in their place.  The advantage to this would be:

1. Because it would happen after the loading phase, all the dependencies would already be tracked by this point.
2. You wouldn't have to override any of jade's internals, so it would be a lot less brittle/error prone.

As for doing it with the currently published version of jade, I would suggest something along the lines of:

```js
var jade = require('jade');
  var originalParseInclude = jade.Parser.prototype.parseInclude;
    jade.Parser.prototype.parseInclude = function () {
      var tok = this.expect('include');
      var file = tok.val.trim();
      var path = this.resolvePath(tok.val.trim(), 'include');
      file = file.replace(/\.jade$/, '');
      var regex = new RegExp(/(.*)-set/g);
      if(!file.match(regex)) {
        // Push the token back
        this.lexer.defer(tok);
        // Call original parseInclude
        return originalParseInclude.call(this);
      }
      this.dependencies.push.apply(this.dependencies, jade.compileFile(path).dependencies);
      return {
        type: 'Text',
        val: '[[$' + file + ']]',
        line: tok.line,
        filename: this.filename
      }
    }
```

On the other hand, if you're using jade for that much of it, I'm starting to wonder why you want this feature in the first place?  What are you doing with the `[[$filename]]` afterwards?

**Comment by mooror** [comment]
Hello there agian, sorry for the late reply. So I was able to use your code with a slight modification to get everything working. Heres the end code: 
```
var jade = require('jade');
  var originalParseInclude = jade.Parser.prototype.parseInclude;
    jade.Parser.prototype.parseInclude = function () {
      var tok = this.expect('include');
      var file = tok.val.trim();
      var path = this.resolvePath(tok.val.trim(), 'include');
      file = file.replace(/\.jade$/, '');
      var regex = new RegExp(/(.*)-set/g);
      if(!file.match(regex)) {
        // Push the token back
        this.lexer.defer(tok);
        // Call original parseInclude
        return originalParseInclude.call(this);
      }
      else{
        this.dependencies.push(path);
      }
      this.dependencies.push.apply(this.dependencies, jade.compileFile(path).dependencies);
      return {
        type: 'Text',
        val: '[[$' + file + ']]',
        line: tok.line,
        filename: this.filename
      }
    }
```
Not sure why but I couldn't get both the example-set.jade and its includes as dependencies unless I had the
```
else{
    this.dependencies.push(path);
}
```
part. But in the end everything worked out, so I want to thank you guys so much. You have been a real blessing to me and saved me a lot of head aches. Also to answer you question ForbesLindesay I need this feature because our company uses two systems (one on each devs computer and one on the server) and so this feature helps me with the conversion from one system to the other. I would love to give you more details on exactly what we are doing with your marvelous technology (jade). But I don't want there to be any legal problems between me and my company.
But thank you both so much and just as a small aside (hopefully :D ) is there any way to use the dependency system to also track all the asset links on a page? Like my js,css,images,fonts? I didn't imagine your system would do this however I always think that if there is a tech. I'm already using that is doing something similar to what I'm doing, its always nice to piggy back things.

Thank you again gentlemen,
Mooror

**Comment by mooror** [comment]
Actually just tracking all the assets with a specific word in the path would be great. For example if I only wanted assets with the word global-assets to be tracked on some jade code like this:
```
link(href='../../../components/stripes/sl-slick-slider-thumb/source/slick/slick.css', rel='stylesheet')
link(type="text/css" rel="stylesheet" href=" ../global-assets/css/core/core.css")
link(type="text/css" rel="stylesheet" href="../global-assets/css/home-main/home.css")
```
I would get back an array (or string) containing 
```
../global-assets/css/core/core.css,../global-assets/css/home-main/home.css
```
But like I said I don't have the unreal expectation of jade being a fully fledged dependency tracker and if this just is not plausible to do in jade I 'm sure I can think of another way.

Cheers,
Mooror

**Comment by ForbesLindesay** [comment]
I promise you (I would stake my job on this), you can swap:

```js
      else{
        this.dependencies.push(path);
      }
```

for

```js
this.dependencies.push(path);
```

without it making any difference whatsoever to the behaviour of the code you posted.

As for tracking other dependencies, you could override the `parseTag` function of parser.  This won't allow you to catch any dynamic paths in those templates, but should work providing the attribute values are constant:

```js
var jade = require('jade');
var constantinople = require('constantinople');

var originalParseTag = jade.Parser.prototype.parseTag;
jade.Parser.prototype.parseTag = function () {
  var tag = originalParseTag.call(this);
  var deps = this.dependencies;
  tag.attrs.forEach(function (attr) {
    if (attr.name === 'href' || attr.name === 'src') {
      // this will throw an error if `href` or `src` are ever assigned dynamic values,
      // if you want you could check for dynamic values using `constantinople.isConstant(attr.val)`
      deps.push(constantinople. toConstant(attr.val));
    }
  });
  return tag;
}
```

**Comment by mooror** [comment]
Thank you for your reply. I was just wondering, by dynamic values are you referring to javascript variables and jade parameters? For Example would this code be a problem for this type of parseTag modification?:
```
mixin example(url)
   link(type="text/css" rel="stylesheet" href=#{url})
```

Thanks,
Mooror

**Comment by TimothyGu** [comment]
> ```jade
mixin example(url)
   link(type="text/css" rel="stylesheet" href=#{url})
```

Yes, this won't work. (Pro tip, in Jade 2.0.0 `#{}` support in attributes will be removed. Use ES6 template strings or just a JavaScript expression)

**Comment by mooror** [comment]
Thank you for the quick reply. As to the protip I was woundering. Will Jade 2.0.0 support the ES6 String Substitution using the ${ } syntax? [Code Example](https://developers.google.com/web/updates/2015/01/ES6-Template-Strings#string-substitution)

**Comment by TimothyGu** [comment]
> Will Jade 2.0.0 support the ES6 String Substitution using the ${ } syntax?

Yes, that's what I meant by "ES6 template strings." Use something like this:

```jade
- var str = 'blah'
p(data-str=`text is ${str}`)
```

This is already supported in 1.11.0 so try this code on jade-lang.com with a browser that supports it!

**Comment by mooror** [comment]
Ahh ok that makes sense. Thank you for clarifying that. Also I was wondering, when jade 2.0 comes out will there be any way to allow for dynamic paths in the templates to be tracked as dependencies?

P.s. I really like the live jade compiling on your website, its awesome!
Mooror

**Comment by ForbesLindesay** [comment]
You would have to add code to be run at compile time (which could be done via a plugin)

**Comment by mooror** [comment]
Sounds very good ForbesLindesay, I look forward to using the new plugin system. Also for the time being, is there any way that I can replace the values of the href and src attributes with a new path (perhaps using the attr.val in some way). Basically I need my script to go through all these paths in the href and src tags and change them to a path using the special tag syntax that our server side environment uses. 
So this code:
```
src="../assets/images/slider/slide-7.jpg"
```
would be compiled to this:
```
src="[[++deploy.assets_url]]images/slider/slide-7.jpg"
```
I was just going to run the outputted html source file through a simple javascript regex replacement, but then I realized that because of the changing of some of the jade includes to [[tags]] the outputted source would actually not have the entire contents of the compilation. Also I just wanted to thank you both once more for all your fantastic help and guidance on this matter. 

Thanks again guys!, 
Mooror
P.s. I am really glad you guys are going to be implementing a plugin system in the new jade. I cannot wait to see what else will be possible with jade in the future!

**Comment by ForbesLindesay** [comment]
Yes, just replace `attr.val` with `JSON.stringify(newValue)`
