### ISSUE TITLE
case statement

### ISSUE THREAD

**Issue by oculushut** [jadejs/jade#2135]
I pass the following in from my nodejs code:

```
{"number": "0"}
```

My jade template then has the following:

```
- var friends = number
case friends
  when 0
    p you have no friends
  when 1
    p you have a friend
  default
    p you have #{friends} friends, #{number}
```

Why does it not display the following?

```
<p>you have no friends</p>
```

I always get this:

```
<p>you have 0 friends, 0</p>
```

What input do I need to provide the template in order to generate the "0" case rather than the "default" case?

**Comment by TimothyGu** [comment]
You are passing in a string. Either convert the string to a number or use a string in `case`, just like regular JavaScript.
