### ISSUE TITLE
jade index.jade : character "d" not allowed in prolog

### ISSUE THREAD

**Issue by 1303110335** [jadejs/jade#2136]
root@vagrant-ubuntu-trusty-64:/vagrant/www/nodejs/imoc/views# jade index.jade
jade:index.jade:1:0:E: character "d" not allowed in prolog
jade:index.jade:6:24:E: end of document in prolog
jade:E: cannot find "index.dsl"; tried "index.dsl", "/usr/local/share/sgml/index.dsl", "/usr/share/sgml/index.dsl"
jade:E: specification document does not have the DSSSL architecture as a base architecture

**Comment by TimothyGu** [comment]
This is not Jade, but [OpenJade](http://sourceforge.net/projects/openjade/). Check `jade --version`.
