### ISSUE TITLE
Fragile block code 

### ISSUE THREAD

**Issue by X-O** [jadejs/jade#2138]
This will error on line 4|  each item in list
Cannot read property 'length' of undefined

```JADE
- 
	list = ["Uno", "Dos", "Tres",
		"Cuatro", "Cinco", "Seis"]
each item in list
	li= item
```
This is because of the space after "-".
I think we can ignore any whitespace directly after "-" for the block classification.

**Comment by TimothyGu** [comment]
This has been fixed in the master branch.
