### ISSUE TITLE
Jade fails to parse attributes that starts with colon

### ISSUE THREAD

**Issue by fullfs** [jadejs/jade#2139]
Hello!
This code is okay:
```
div(:name="something")
```

This code will fail:
```
div(:name="something" :title="other")
```

In the case lexer parses ```:name``` value as ```something" :title="other"```

**Comment by ForbesLindesay** [comment]
If your attributes start with a `:` you should enclose them in speaks marks:

```jade
div(":name"="something" ":title"="other")
```

**Comment by fullfs** [comment]
@ForbesLindesay okay, thanks.
I'd like too ask. Is there any light version of Jade? The one without any extra features like variables, filters, includes, etc. Just HTML in Jade syntax?

**Comment by TimothyGu** [comment]
@fullfs none officially supported.

**Comment by BYODKM** [comment]
Sorry for interrupt. But mixins can't parse attributes start with colon.

```
mixin foo
  div.foo&attributes(attributes)
    block

+foo(":attr"="something")
```

Is there any way to do that?

**Comment by TimothyGu** [comment]
@BYODKM, in your case, the attributes are treated as mixin arguments. To work around this, make it clear that it's attributes:

```jade
mixin foo
  div.foo&attributes(attributes)
    block

+foo()(":name"="something" ":title"="other")
```

**Comment by BYODKM** [comment]
@TimothyGu Oh! Great! Thanks!!
