### ISSUE TITLE
Globals Usage

### ISSUE THREAD

**Issue by arb** [jadejs/jade#2141]
I'm confused how to use global in Jade templates. Looking at the docs, it looks like `globals` is listed as an array of strings. Suppose I have a "CSS" option that I want globally available, how do I set that? How can I reference it in templates? If globals is an array of strings, how can I access a specific one. Also, is there a different syntax for accessing global values?

**Comment by ForbesLindesay** [comment]
`globals` is just a performance optimisation.  It's intended for if you know you're going to be using certain globals (e.g. `window`, `Buffer`, `String` etc.).  It's not intended for setting derfaults.  For setting defaults you should use your own JavaScript structures.  e.g. you could simply define something like:

```js
function renderWithDefaults(filename, locals) {
  locals = locals || {};
  if (!locals.css) locals.css = 'whatever';
  return jade.renderFile(filename, locals);
}
````
