### ISSUE TITLE
[QUESTION] Editing jade parse r to allow for mixin end tags

### ISSUE THREAD

**Issue by mooror** [jadejs/jade#2143]
Hello again, [In This Issue](https://github.com/jadejs/jade/issues/2116) I had asked if it was possible "to extract block contents from mixins via api", I was told that at present this is not possible. So I though to myself how I might get around this problem as I use mixin blocks very often. So if I cannot use a feature of jade to extract the mixin block data I thought that perhaps I could use a regx to retrieve this data. This I quickly realized might get complex unless I can somehow allow jade mixins to have end tags like this : 
```
+example-mixin(parameters)
   p block contents go here
   p and here
   p and...you get the idea
-example-mixin //This would be the end tag. Syntax can be different but I need an end tag
``` 
If so, then I can get the contents of the block with a regex something like:
```
/\+example-mixin(.*)\-example-mixin/g
```
Is there a better way to do what I'm doing and if not can I add end tag functionality to jade so that I wont get any errors or weird quirks on compilation.

Thanks again,
Mooror

**Comment by ForbesLindesay** [comment]
Just split on new line then loop through the lines.  When you see a mixin call, note how long the indentation is.  Keep reading until the indentation is reduced again.
