### ISSUE TITLE
URL string "http://xxx" in a nested tag syntax #[] causes error

### ISSUE THREAD

**Issue by laggingreflex** [jadejs/jade#2144]
This jade fails to render:

    p See #[a(href="http://example.com/help/123") http://example.com/help/123]

I've narrowed down the issue to be that the string `:/` (colon forward-slash) inside a nested tag `#[]` causes the crash. So the following doesn't work either:

    p #[p :/]

Tested with jade@1.11, express@4.13
[Original question on SO](http://stackoverflow.com/questions/33283549/in-a-jade-template-how-do-i-put-a-literal-url-as-a-link-anchor)

**Comment by ForbesLindesay** [comment]
This has already been resolved in jade 2.0.0 (which will be released very soon). In the mean time you can do:

```jade
p See #[a(href="http://example.com/help/123")= "http://example.com/help/123"]
```
