### ISSUE TITLE
How to use jstransformer for included:scss?

### ISSUE THREAD

**Issue by episodeyang** [jadejs/jade#2145]
Hi ,

I have seen multiple syntaxes, but not sure which one is the official one. 

I am trying to use scss filter in the following way:

```javascript
var jade = require('jade');
var jstransformer = require('jstransformer');
var scssTransformer = require('jstransformer-scss');
/* this is working in express, but does not work with gulp-jade using the newest version of jade. */
jade.filters.scss = jstransformer(scssTransformer);

/* this is working */
jade.filters.scss = function (string) {
    var output = scssTransformer.render(string);
    if (output && output.body) return output.body;
    return null;
};
```

Jade version: 1.11.0

**Comment by episodeyang** [comment]
k so I read the source code. 

What is really strange is that the source try to `require` the `jstransformer-<filter name>` module but itself, and it ignores the jstransformer passed into the filter. 

I wish this is explained better in the documentation. What is the official way to add jstransformer filters?

Thanks.

**Comment by ForbesLindesay** [comment]
If it doesn't work with gulp-jade because gulp-jade is loading an out of date version of jade that does not match the version you are loading/extending.  Either make sure you require the exact same version of jade as gulp-jade does (and make sure that there's only a single copy by running `npm dedupe`) or send gulp-jade a pull request to update their version of jade.

**Comment by ForbesLindesay** [comment]
It looks like gulp-jade actually is using an up to date version of jade, in which case the answer is:

1. for custom filters, you need to ensure that only a single copy of jade is loaded.  If there are two separate copies then custom filters won't work.
2. for jstransformers you don't need to do anything, they are just automatically supported as you have now discovered.

**Comment by episodeyang** [comment]
Right. The nice thing is that there is the source so I just read it and it was clear. And `gulp-jade` has been updated to 1.11.0 for a while.

Thanks for your work!
