### ISSUE TITLE
Why require explicit body and head tags?

### ISSUE THREAD

**Issue by pandorahlz** [jadejs/jade#2147]
HTML5 explicitly permits one to omit these auto-implied tags. Why does jade demand them?

Could we make it smarter and not mind what it's translating, just convert the syntax and not be such a busy-body to worry about the hierarchy of the tags?

Or am I missing something?

**Comment by TimothyGu** [comment]
We don't.

```jade
p See?
```

```html
<p>See?</p>
```

**Comment by pandorahlz** [comment]
Weird, now I can compile without those. But I was getting errors before.
