### ISSUE TITLE
Cannot seem to use inline javascript to create mixin calls

### ISSUE THREAD

**Issue by mooror** [jadejs/jade#2148]
So Im trying to create use inline javascript in jade to create mixin calls. However I seem to be hitting some problems (perhaps javascript is handled after the jade has already done its mixin parsing?). For example, this simple example:
```
- var mixinCall = "+sl-reversal('reverse')";
#{mixinCall}
```
compiles to this
```
<+sl-reversal('reverse')></+sl-reversal('reverse')>
```

Not sure why this is but I would love if someone would tell me how to fix this.

Thanks in advance,
Mooror

**Comment by TimothyGu** [comment]
Use one of these:

```jade
- var mixinCall = "sl-reversal";
+#{mixinCall}('reverse')
```

```jade
- var mixinCall = "sl-reversal";
- var mixinArg = "reverse";
+#{mixinCall}(mixinArg)
```

```jade
- var mixinCall = function () {
  +sl-reversal('reverse')
- }

- mixinCall()
```

For future questions, please consider using our [Gitter chatroom](https://gitter.im/jadejs/jade) rather than our _issue_ tracker. Thanks.

**Comment by mooror** [comment]
Thank you for the reply. And I,m so sorry if I have been some what of a spammer on your github issues page. I had no idea about the gitter chatroom. I will make sure to use that in the future for questions.
