### ISSUE TITLE
Conditional comment will not be complides as wished.

### ISSUE THREAD

**Issue by vrbvillor** [jadejs/jade#2149]
```jade
body
  //if IE
    a(href='http://www.mozilla.com/en-US/firefox/') Get Firefox
```

WILL NOT BE COMPILED AS BELOW

```HTML
<body>
  <!--[if IE]>
    <a href="http://www.mozilla.com/en-US/firefox/">Get Firefox</a>
  <![endif]-->
</body>
```

BUT THE ANCHOR WILL BE OUTPUT AS NORMAL TEXT LIKE THIS

```HTML
<!--if IEa(href='http://www.mozilla.com/en-US/firefox/') Get Firefox
-->
```

I use JADE in Sublime. Download it using package control at 2015-10-29......

Please help, thanks.

**Comment by TimothyGu** [comment]
See http://jade-lang.com/reference/comments/ for how to use conditional comments. In short, there are no special Jade syntax:

```jade
body
  <!--[if IE]>
  a(href='http://www.mozilla.com/en-US/firefox/') Get Firefox
  <![endif]-->
```

**Comment by vrbvillor** [comment]
The documentation of Chinese tutorial has told that (conditional comment),  please tell the writer to correct them,  thanks for answering my two questions.   ^3^

**Comment by TimothyGu** [comment]
The author hasn't been active in Jade for quite some time now, so I fixed it: 2c9bee7e9568cf40b72dacd305ac9d2a3a0fe804 & 5122443445ea23615be45d639a349c8fadf9bbc3.

（我的中文可能有些生疏，请多多谅解。）

**Comment by vrbvillor** [comment]
I've seen before that JADE doesn't support CASE fall through. But in the reference you've given to me ,  that says JADE supports CASE fall through,  so I think you should add it upto the DOC.

**Comment by ForbesLindesay** [comment]
Pull requests for updates to the Chinese documentation are always welcome.
