### ISSUE TITLE
How to loop classnames?

### ISSUE THREAD

**Issue by vrbvillor** [jadejs/jade#2150]
```jade
		-colors = ["red","yellow","blue","green"]
		each color,index in colors
			p.#{color} colors[#{index}]=#{color}
```

I want to build into a HTML like this

```html
<p class="red">color[0]=red</p>
<p class="yellow">color[1]=yellow</p>
<p class="blue">color[2]=blue</p>
<p class="green">color[3]=green</p>
```

But I fail.... How to achieve it ?

**Comment by TimothyGu** [comment]
```jade
        - colors = ["red","yellow","blue","green"]
        each color,index in colors
            p(class=color) colors[#{index}]=#{color}
```

**Comment by vrbvillor** [comment]
I've just think the way out....   but can it be shorter?  Have I to use (class="") instead of `.` the dot?

**Comment by TimothyGu** [comment]
> but can it be shorter?

No.

> [Do I have] to use (class="") instead of `.` the dot?

Yes.

**Comment by vrbvillor** [comment]
I've found that I can't build WHILE LOOP example in sublime, after I press ctrl+b ,  it seems to death....

http://jade-lang.com/reference/iteration/

```jade
- var n = 0
ul
  while n < 4
    li= n++
```
