### ISSUE TITLE
Evaluating variables from string reference

### ISSUE THREAD

**Issue by pmhpereira** [jadejs/jade#2152]
Hi guys,

I want to be able to generate a simple webpage by parsing a JSON file in Jade.

I'd like to know if it is possible to reference variable names from a JSON file and have them evaluated before the webpage is displayed.

Example:

mixins.jade

    mixin input_from_json(attr)
        input&attributes(attr)

index.jade

    - var json_file = { "value": "#{owner.username}" }

    // I need something like
    +input_from_json(json_file)

    // to work the same as
    +input_from_json({ value: owner.username })

Is there any way to make this work **on the rendering side**? The alternative on the server-side (Express.js) would be to set the correct values for the resultng JSON object before calling res.render().

Best regards,
Pedro

**Comment by jeromew** [comment]
Have you tried

    - var json_file = { "value": owner.username }

**Comment by pmhpereira** [comment]
The JSON file is `required()` in the server route and is then passed onto the Jade renderer, so if I try to require it with `owner.username` I receive a `json_file.json: Unexpected token o` error.

---

Imagine the following. I'd like this code to generate `<input type="text" value="pmhpereira">`

index_layout.json

    {
        "type": "text",
        "value": "owner.username"
    }

routes.js

    res.render('index.jade', {
        layout: require('./index_layout.json'),
        owner: { username: 'pmhpereira' }
    });

index.jade

    input(type=layout.type value=layout.value)

---

Is it possible to use the `layout.value` string in some way and get the `username` value from the `owner` object?

**Comment by TimothyGu** [comment]
`eval`?

**Comment by pmhpereira** [comment]
Thanks, it worked! I thought `eval()` would only work inside `.js` files so I didn't even bother trying.

**Comment by TimothyGu** [comment]
I assume you have already known the [classic speech](https://24ways.org/2005/dont-be-eval) about the dangers with using `eval` though. Of course, the best solution to the problem is to refactor your code.

**Comment by pmhpereira** [comment]
I'm aware of the dangers of `eval`. I'll probably code a better way to make this work. 
Thanks for your time and for the warning!
