### ISSUE TITLE
extends + multiline code issue

### ISSUE THREAD

**Issue by Overdrivr** [jadejs/jade#2157]
How can I write multiline code in a block ?

I tried the following that did not work:
```
-
  list = ["Uno", "Dos", "Tres",
          "Cuatro", "Cinco", "Seis"]  
block content
  each item in list
    li= item
```
and the following is impossible:
```
block content
-
  list = ["Uno", "Dos", "Tres",
          "Cuatro", "Cinco", "Seis"]  
  each item in list
    li= item
```
Because then the iteration gets treated as javascript. How can I achieve that ?

**Comment by ForbesLindesay** [comment]
Fix your indentation. The code needs to be indented inside a block or it will be ignored.  The each needs to not be indented inside the code or it is treated as JavaScript
