### ISSUE TITLE
for/each not working

### ISSUE THREAD

**Issue by Overdrivr** [jadejs/jade#2158]
I get a syntax error if I use `for` or `each` in my page, the error message does not provide relevant information. Commenting the line of the `each` instruction clears the issue.
Line number doesn't seem to match, I suppose this is because I have a layout file.

```
extends layout

block scripts
  script(type="text/javascript" src="/javascripts/init_datepicker.js")

block content
  h3 Search a run
  - var test = [1,2,3]
  ul
    each entry in test 
      li= entry

```
This is the error message:
```
Unexpected token (1:15) 
SyntaxError: Unexpected token (1:15)
```
I have jade 1.11.0

**Comment by lutzhorn** [comment]
This works:

```
h3 Search a run
- var test = [1,2,3]
ul
    each entry in test
        li= entry
```

So the problem might be related to the rest of your code.

**Comment by Overdrivr** [comment]
I removed everything from the file, my new code is now

```
- var test = [1,5,3]

ul
  each entry in test
    li= entry
```
I still get the issue.

Also for that
```
ul
  each entry in [1,5,3]
    li= entry
```
I don't see where in my code there can be an issue. Do you have an idea ? 

But on the other hand this works
```
- var test = [1,5,3]

ul
- test.forEach(function(entry){
  li= entry
- });
```
How can I get a clearer error message ?
Thanks

**Comment by Overdrivr** [comment]
Ok that's super weird. I had to reinstall jade module to fix it.
Problem is now gone.

Initially, package.json contained this 
```
"dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.13.1",
    "i18n": "^0.5.0",
    "jade": "~1.11.0",
    "morgan": "~1.6.1",
    "serve-favicon": "~2.3.0"
  }
```
it now contains this
```
"dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.13.1",
    "i18n": "^0.5.0",
    "jade": "^1.11.0",
    "morgan": "~1.6.1",
    "serve-favicon": "~2.3.0"
  }
```
As you can notice for jade ~ was replaced by ^

**Comment by TimothyGu** [comment]
I don't think this matters at all, but rather a mess up made by me in ForbesLindesay/acorn-globals#10.
