### ISSUE TITLE
Include with concat in the path? (Dynamic include)

### ISSUE THREAD

**Issue by saviomd** [jadejs/jade#2159]
I am making a multi-language site that is organized as follow:
- i18n files that have key and values
- a lot of pages and all of them exists in every language (one page file is built several times, one for each language)
- each page has a variable "page.lang = {{lang}}" ({{lang}} is replaced with the language that is currently being built)

The problem is that in the template, I use this page.lang variable to know which i18n to use.
I did this:
```
if page.lang === 'en'
	include ../data/i18n-en.jade
if page.lang === 'pt'
	include ../data/i18n-pt.jade
```

But for every new language, I will have to include a new if.
Something like the following would be much better, but I didn't managed to make it work. Includes don't seem to like strings and concats..
```
include '../data/i18n-' + page.lang + '.jade'
```

Is possible to do this in some way?

**Comment by ForbesLindesay** [comment]
Read existing issues, open and closed.

**Comment by saviomd** [comment]
ops.. sorry
i'll take a look at them
