### ISSUE TITLE
Bad expanding

### ISSUE THREAD

**Issue by diegoaguilar** [jadejs/jade#2160]
I'm making jade convert `div(ui-view)` to HTML but the result is `<div ui-view='ui-view'></div>` which is clearly not what it should be rendered. Any suggestion on it?

**Comment by ForbesLindesay** [comment]
Set the doctype option to html

**Comment by diegoaguilar** [comment]
It's Sublime (Jade build](https://packagecontrol.io/packages/Jade%20Build) which I'm using
