### ISSUE TITLE
[Help] You should not have jade tags with multiple attributes.

### ISSUE THREAD

**Issue by marti1125** [jadejs/jade#2163]
mixin icon-input-text-datepicker-2-10(icon_class,id,name,value)
      .row.collapse.prefix-radius
        .small-2.columns
          span.prefix.icon_input_style
            i(class=icon_class).input
        .small-10.columns
            input(id=id).fdatepicker(type='text',name=name,value=value)

    +icon-input-text-datepicker-2-10("fi-calendar","inicio-als-date","","")

https://gist.github.com/marti1125/37e405f61ca146125936

**Comment by TimothyGu** [comment]
```jade
input(id=id).fdatepicker(type='text',name=name,value=value)
```

For whatever reason, you have two attributes here.

**Comment by TimothyGu** [comment]
BTW, I just checked, on Jade 1.11.0 (the newest version of Jade), the two attributes work fine, so please ignore my previous comment.

**Comment by marti1125** [comment]
ok :D thanks

**Comment by marti1125** [comment]
I am using jade 1.11.0

**Comment by marti1125** [comment]
could you test my mixin @TimothyGu

**Comment by TimothyGu** [comment]
I told you it works fine.

**Comment by bfred-it** [comment]
Is this an important warning? It seems to work fine with both attribute groups and I find this useful to keep features separated/grouped. e.g.

```jade
img(src="img.jpg" alt="My image")(data-foo="bar" data-foo-extra)
```

**Comment by marti1125** [comment]
@bfred-it thanks
