### ISSUE TITLE
ES6 class object in locals

### ISSUE THREAD

**Issue by fusepilot** [jadejs/jade#2168]
I'm passing a class object with a few methods on it to the locals. I'm using babel as the transpiler.

````
class Page {
  constructor({title, date}) {
    Object.assign(this, {title, date})
  }

  getDate() {
    return moment(this.date).format('YYYY MM DD / HH:MM')
  }
}

let locals = {
  page: new Page('My Page', new Date()),
}

templateFunction = jade.compile(templateString)
let html = templateFunction(locals)
````

If I call ````page.getDate()```` in the template, I get this error "page.getDate() is not a function". It seems jade is mutating the class object.

My way around this is to bind a variable to the function in the constructor.

````
class Page {
  constructor({title, date}) {
    Object.assign(this, {title, date})

    this.getDate = this._getDate.bind(this)
  }

  _getDate() {
    return moment(this.date).format('YYYY MM DD / HH:MM')
  }
}
```

Then it works.

Is this something that will be fixed in 2.0? Sorry if this has been brought up before, I couldn't find anything about it.

node 5.0.0
jade 1.11.0
babel 5.8.29

**Comment by TimothyGu** [comment]
I'm not sure if this is one of the reasons, but this snippet in your code doesn't work (or at least shouldn't work):

```js
class Page {
  constructor({title, date}) {
    Object.assign(this, {title, date})
  }

  getDate() {
    return moment(this.date).format('YYYY MM DD / HH:MM')
  }
}

let locals = {
  page: new Page('My Page', new Date()),
}
```

The constructor takes an object with `title` and `date` properties, not two parameters.

After fixing that and adding [some other things](https://www.diffchecker.com/1epi0d5p) that allow me to test the code, the code works as expected here, outputting:

```html
<!DOCTYPE html><html><body><p>Tue Nov 17 2015 22:59:51 GMT-0800 (PST)</p></body></html>
```

in the console.

**Comment by ForbesLindesay** [comment]
This isn't a bug with jade.  Somehow you're not passing in the object you think you are.  Have you tried calling `page.getDate()` immediately before rendering the jade template to check that it works.  I'm closing this since it's not a jade bug, but please feel free to continue discussion.

**Comment by fusepilot** [comment]
My bad, yes it should have been ```` page: new Page({title: 'My Page', date: new Date()}),````.

It still doesn't work in the code base I pulled it from. But it works in the stand alone test I just made (which I should have done first), so the problem must somewhere else on my end.

Thanks, and sorry for the bother.
