### ISSUE TITLE
block inside for loop

### ISSUE THREAD

**Issue by PinkyJie** [jadejs/jade#2177]
I want to dynamically define block name inside a for loop like this:
``` jade
.section
    - for (var i = 0; i < 3; i++)
        block #{'image'+i}
        block #{'heading'+i}
```

Unfortunately, it's not working. Is there a work around for this?

**Comment by jeromew** [comment]
I am not sure but I don't think block can be invoked dynamically.

you can use dynamic mixins

    mixin image0()
      img(href='...')

    +#{'image'+'0'}()

**Comment by PinkyJie** [comment]
@jeromew yes, I also googled dynamic mixin, but mixin is not fitable for my case.

**Comment by mcpDESIGNS** [comment]
This is more of a stackoverflow issue than a Jade issue

**Comment by TimothyGu** [comment]
No. Blocks for extends are static.
