### ISSUE TITLE
Link within inline element

### ISSUE THREAD

**Issue by smaili** [jadejs/jade#2181]
Originally, I was trying to do an inline link to another website:

```Jade
p.
    Go to #[a( href='http://google.com' ) http://google.com].
```

I thought it might be because there's two urls, but after doing some more testing, it seems for any inline element it will fail:
```Jade
p.
    Go to #[span http://google.com].
```

Here is the error message:
```
The end of the string was reached with no closing bracket found.
```

However, if I remove the `http://` from the text it works.
```Jade
p.
    Go to #[a( href='http://google.com' ) google.com].
```

So the issue seems to be when a link is present in the text of an inline element.

**Comment by TimothyGu** [comment]
This has been fixed in Jade 2.0.0. There was another ticket for this same bug.
