### ISSUE TITLE
that Readme.md is dated

### ISSUE THREAD

**Issue by kelthenoble** [jadejs/jade#5]
> the `README.md` is so old  it was hanging around before dinosaurs walked the earth. :+1:  

But for the `serious part`: I'm trying to do a few changes to the website, & it's very hard to contribute to 
something when the path is out of date. I'm just trying to get this puppy running on `localhost`. How can i do this? @niftylettuce  @alubbe

**Comment by niftylettuce** [comment]
See https://github.com/pugjs/jade/issues/2184, that's the repo

**Comment by kelthenoble** [comment]
I see, thanks @niftylettuce
