### ISSUE TITLE
Multi-Line Array Literal

### ISSUE THREAD

**Issue by zfogg** [jadejs/jade#502]
Is it possible? I want to make an array like this:

    - var myArray = [
        'one',
        'two',
        'three'
    ]

I want to pass this array to a mixin as an argument. This will make my code much less verbose.. but if it would be silly to have all my items on a single line. Why does this not compile?

**Comment by ForbesLindesay** [comment]
We will be adding support for importing JavaScript from other files as part of 2.0.0.  That should solve most people's use case here.  If you feel this remains an issue in 2.0.0, please open a new issue so that it can be resolved.

**Comment by jjhoncv** [comment]
I leave some aid.

look this:

Is only jade with var text type
```jade
- var list = []
- list.push({status: "active", text: "option 1"})
- list.push({status: "", text: "option 2"})
- list.push({status: "", text: "option 3"})

each(item, index in list)
  li(class="#{item.status}")
    a= item.text
```

Is only jade with var type text and var html type.
```jade
- var list = []
- list.push({status: "active", text: "option 1"})
- list.push({status: "", text: "<strong>option 2</strong>"})
- list.push({status: "", text: "option 3"})

each(item, index in list)
  li(class="#{item.status}")
    a= !{item.text}
```

Now for other language side back for example PHP:
```jade
- var list = []
- list.push({status: "<?php echo $status1;?>", text: "option 1"})
- list.push({status: "<?php echo $status2;?>", text: "<strong>option 2</strong>"})
- list.push({status: "<?php echo $status3;?>", text: "option 3"})

each(item, index in list)
  li(class!="#{item.status}")
    a= !{item.text}
```

**Comment by TimothyGu** [comment]
You can also use block code:

```jade
-
  var list = [
    {status: "<?php echo $status1;?>", text: "option 1"},
    {status: "<?php echo $status2;?>", text: "<strong>option 2</strong>"},
    {status: "<?php echo $status3;?>", text: "option 3"}
  ]

each(item, index in list)
  li(class!="#{item.status}")
    a= !{item.text}
```

**Comment by ahmadalfy** [comment]
@TimothyGu Thank you this is the best solution so far

**Comment by ForbesLindesay** [comment]
Or even:

```jade
-
  var list = [
    {status: "<?php echo $status1;?>", text: "option 1"},
    {status: "<?php echo $status2;?>", text: "<strong>option 2</strong>"},
    {status: "<?php echo $status3;?>", text: "option 3"}
  ]

each(item, index in list)
  li(class!=item.status)
    a!= item.text
```

since `a= !{item.text}` shouldn't even work, and `class!="#{item.status}"` is vastly over complicated.

**Comment by TimothyGu** [comment]
> since `a= !{item.text}` shouldn't even work, and `class!="#{item.status}"` is vastly over complicated.

Both of which are disallowed in Jade 2.0.0.

```
> var jade = require('jade')
> jade.render('a= !{"abc"}')
Error: Jade:1
  > 1| a= !{"abc"}

Syntax Error: Unexpected token }
    at compileBody (/home/timothy_gu/jade/lib/index.js:107:9)
    at Object.exports.compile (/home/timothy_gu/jade/lib/index.js:164:16)
    at handleTemplateCache (/home/timothy_gu/jade/lib/index.js:137:25)
    at Object.exports.render (/home/timothy_gu/jade/lib/index.js:298:10)
    at repl:1:14
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:393:12)
    at emitOne (events.js:82:20)
> jade.render('p(class!="#{item.status}")')
'<p class="#{item.status}"></p>'
```

**Comment by mehas** [comment]
>You can also use block code:

    -
      var list = [
        {status: "<?php echo $status1;?>", text: "option 1"},
        {status: "<?php echo $status2;?>", text: "<strong>option 2</strong>"},
        {status: "<?php echo $status3;?>", text: "option 3"}
      ]

This gives me the error "unexpected text" text error on the first line following the `-`

**Comment by TimothyGu** [comment]
@mehas You need to use the latest version of Jade (≥1.11.0)

**Comment by briantuju** [comment]
Writing javascript code on one line was becoming unmanageable until I found this post.
Though I may be late to the party

Thanks a lot :smiley:
