### ISSUE TITLE
Data Attribute shorthand

### ISSUE THREAD

**Issue by guybedford** [jadejs/jade#670]
Since Jade is all about writing less unnecssary html syntax, it could be really useful having a shorthand for data attributes.

So instead of writing:

div(data-attribute=data.value)

Being able to write:

div(:attribute=data.value)

Since its detecting the "data" part now anyway for string escaping ((https://github.com/visionmedia/jade/commit/bef31f8ed3620adaef6385b1c60e9e1ae7bb93b9), it would just be one extra additional attribute parse check.

There may be a better symbol to use here than a colon as well.

It's a simple feature to add in, and would make templates that feature the use of data-attributes a lot more readable.

**Comment by ForbesLindesay** [comment]
This will be considered as part of the 2.0.0 release.  If you still feel this is an issue after 2.0.0 has been released, please open a fresh issue.

**Comment by matthewjumpsoffbuildings** [comment]
Sorry to comment on an old closed issue, but whats the status with this?

Im using a lot of data-attributes and its getting really ugly having to type `data-` in front of them all, is there a cleaner way to do it?

**Comment by xanderiel** [comment]
Agree, highly interested in a shorthand for data attributes.
