### ISSUE TITLE
Allow multiline JS var definition

### ISSUE THREAD

**Issue by kinergy** [jadejs/jade#796]
Similar to how this works in Jade:

    input(
      type='checkbox'
      name='agreement'
      checked)

I'd like to be able to do this:

    config = {
      a: 'something',
      b: 'something-else'
    }

instead of having to write:

    config = { a: 'something', b: 'something-else' }

This is a short example, however as config grows it would be much prettier if funky spacing was allowed.

**Comment by TimothyGu** [comment]
I am going to go ahead and unlock this issue. Please refrain from adding more +1’s, and limit your comments to constructive implementation details.

**Comment by iliakan** [comment]
+1, it worked for me as Forbes said here https://github.com/jadejs/jade/issues/796#issuecomment-39235865, but only with debug disabled.

**Comment by TimothyGu** [comment]
@iliakan it is expected that !debug works as debugging "symbols" are attached in between lines.

**Comment by iliakan** [comment]
@TimothyGu yes, I felt it's the reason :/
Is it possible to do something with it? Maybe something like `js:`, to let jade know we're including a non-breakable js...

**Comment by TimothyGu** [comment]
@iliakan I'm not extremely motivated to do this. We will accept pull requests for the following syntax though:

```jade
-
  var af = {
    prop: 1
  }
```

See https://github.com/jadejs/jade/issues/796#issuecomment-39235865

**Comment by acidjazz** [comment]
If we do need this or think it's helpful I'd say a more generic, faster, and safer implementation would be that of a multi-line JS block similar identifier like /* */ or .  

This sort of also bumps into the factor of functionality balance though, if I have am doing THIS much in jade that I require such a feature, should this be in Jade?

**Comment by TimothyGu** [comment]
@acidjazz said:

> If we do need this or think it's helpful I'd say a more generic, faster, and safer implementation would be that of a multi-line JS block similar identifier like /* */ or .

I'd rather use the syntax proposed by @ForbesLindesay to be more consistent with the currently used `-`.

> This sort of also bumps into the factor of functionality balance though, if I have am doing THIS much in jade that I require such a feature, should this be in Jade?

+1, although in many cases it's just a simply look-up table or loop array, so I guess it's fine.

**Comment by boompig** [comment]
+1

**Comment by dogancelik** [comment]
:+1: I would be happy if someone could implement multi-line JS.

**Comment by AbraaoAlves** [comment]
+1

**Comment by ironmancris** [comment]
+1

**Comment by alephyud** [comment]
Had the same issue - put together a [patch](https://github.com/jadejs/jade/pull/1965) to handle block code like:

    -
      var a = {
        prop: 1
      }

**Comment by alephyud** [comment]
Thank you! Understood about /jade.js .

On 2) - could you please clarify your idea? Not sure if we really should make trailing whitespace an error: first, in many cases it appears by accident and makes no harm, and second, in the current version strings like `"-    \n"` do not cause a syntax error and are accepted as (empty) code, since any whitespace is parsed as code due to the greedy evaluation of the `/^(!?=|-)[ \t]*([^\n]+)/` in `Lexer.prototype.code()`. So, with `/^-\n/` pattern for block code, a code like

    - [whitespace]
      p=5

would yield different results from this

    -
      p=5

not something we would probably want...

**Comment by jjhoncv** [comment]
For make object with jade and array is this best solution: https://gist.github.com/jjhoncv/a6efea5eeb7937cb6f90

**Comment by jjhoncv** [comment]
I leave some aid.

look this:

Is only jade with var text type
```jade
- var list = []
- list.push({status: "active", text: "option 1"})
- list.push({status: "", text: "option 2"})
- list.push({status: "", text: "option 3"})

each(item, index in list)
  li(class="#{item.status}")
    a= item.text
```

Is only jade with var type text and var html type.
```jade
- var list = []
- list.push({status: "active", text: "option 1"})
- list.push({status: "", text: "<strong>option 2</strong>"})
- list.push({status: "", text: "option 3"})

each(item, index in list)
  li(class="#{item.status}")
    a= !{item.text}
```

Now for other language side back for example PHP:
```jade
- var list = []
- list.push({status: "<?php echo $status1;?>", text: "option 1"})
- list.push({status: "<?php echo $status2;?>", text: "<strong>option 2</strong>"})
- list.push({status: "<?php echo $status3;?>", text: "option 3"})

each(item, index in list)
  li(class!="#{item.status}")
    a= !{item.text}
```

**Comment by RSamokhin** [comment]
+

**Comment by maxingchi** [comment]
+1
